### ISSUE TITLE
kebab-case naming support

### ISSUE THREAD

**Issue by mamat-rahmat** [coala/coala-bears#1013]
Will FilenameBear support kebab-case? See [this wiki](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles)

There isn't a single widely-accepted name for this case convention analogous to snake_case or camelCase. But, Lisp has used this convention for decades as described in [this wiki](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Lisp). 
[More Discussion](http://softwareengineering.stackexchange.com/questions/104468/if-this-is-camelcase-what-is-this)

**Comment by Makman2** [comment]
looks sane, why not :)

**Comment by dosarudaniel** [comment]
I would like to work on this issue.

**Comment by gs0510** [comment]
@dosarudaniel  Are you working on this?

**Comment by gs0510** [comment]
From what I understand, I will have to add a to_kebabcase function to rom coalib.bearlib.naming_conventions file. Also, there is no uniform standard for some of the conversion for kebab case. For example, __Init__File__ is converted by some online kebab-case converters to -init-file-, some convert it to --init--file-- . What should we consider as a standard?

**Comment by Makman2** [comment]
@gs0510 feel free to implement one that is reasonable for you :)

**Comment by yash-nisar** [comment]
This can be closed. @Mixih @meetmangukiya
