### ISSUE TITLE
PyUnusedCodeBear.remove_all_unused_imports must default to False

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1016]
PyUnusedCodeBear.remove_all_unused_imports was introduced in https://github.com/coala/coala-bears/pull/991 without a default.

Without a default, it will cause a failure for existing coala implementations using PyUnusedCodeBear when they upgrade.

**Comment by sils** [comment]
I already did set it to false by default (merged 30 mins ago), builds are passing again.
