### ISSUE TITLE
[Bear Proposal] rst-lint for PYPI README.rst

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1028]
Python package [`restructuredtext_lint`](https://pypi.python.org/pypi/restructuredtext_lint) has a command line program `rst-lint`, which can be used to verify that `README.rst` uses correct syntax for use on PYPI.

**Comment by Mixih** [comment]
Assign me please.

**Comment by Mixih** [comment]
We seem to already have this bear: https://github.com/coala/coala-bears/blob/master/bears/rest/reSTLintBear.py . Please clarify if this is incorrect.

**Comment by jayvdb** [comment]
ah yes, whoops ;-)
