### ISSUE TITLE
Generate bear-requirements.txt from metadata in the bears

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1044]
Many of the bears have `PipRequirement` metadata.
It would be lovely to have a script that can generate a `requirements-bears.txt` file from all of those bears.

That file might be included in the main `requirements.txt`, which would be a small step towards https://github.com/coala/coala-bears/issues/1000 .

**Comment by jayvdb** [comment]
This task has now been loaded into GCI as https://codein.withgoogle.com/tasks/6276537751961600/ . It may take a little while to be published.

**Comment by yukiisbored** [comment]
Can I do this one, desu?

**Comment by sils** [comment]
The issue or the task @yukiisbored ? The task doesn't seem to be published yet, any maintainer can assign you the issue here if/when you want.

**Comment by sils** [comment]
whoops sorry GitHub didn't update the issue when I wrote my comment apparently
