### ISSUE TITLE
Warning in RELEASE_NOTES.rst

### ISSUE THREAD

**Issue by Mixih** [coala/coala-bears#1046]
rst2html throws a warning in the RELEASE_NOTES.rst file:
`RELEASE_NOTES.rst:351: (WARNING/2) Duplicate explicit target name: "here".`

**Comment by atemafac** [comment]
hello , please i will like to have more information concerning this issue.

**Comment by Mixih** [comment]
Welcome to the community!
Please make sure you have followed the Newcomer's guide and the Development setup guide before working on an issue.
Make sure you fork the repository and make a new branch for your modifications. Never develop on master.

Ok so to break the one-liner down: 
`RELEASE_NOTES.rst:                                             351:`
^This part tells what the file is called and where it is  ^this tells you the line number where the issue is(very approximate, look around)(in this case, it's more like 354 or 359 now)
`(WARNING/2)                                       Duplicate explicit target name: "here"`
^This tells you the severity of the issue  ^this tells you what the issue is

in this case, the reference `here` is attached to 2 urls. You will need to read up on restructured text to fix it

**Comment by atemafac** [comment]
from what i have here in my pc the number of lines of codes ends at 264. i cloned it 3 days ago.  what i am i to do now that i dont yet have the complete file.

**Comment by Mixih** [comment]
1) Make sure you are in the correct repo. Coala also has one.
2) Follow the instructions for rebasing in https://docs.coala.io/en/latest/Developers/Git_Basics.html

**Comment by arghyatiger** [comment]
i would like to work on this issue. i read all the developing instructions for joining coala.

**Comment by aptrishu** [comment]
There you go. :) @arghyatiger

**Comment by arghyatiger** [comment]
solved the issue and created a pull request . please review @aptrishu

**Comment by SanketDG** [comment]
unassigned due to inactivity
