### ISSUE TITLE
Update the number of supported langauges in README

### ISSUE THREAD

**Issue by adtac** [coala/coala-bears#1053]

**Comment by adtac** [comment]
Or we could look into writing a cron job to do this like every day.

**Comment by LWJensen** [comment]
I can take this issue for now, just to update until a consistent solution is written.

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by Nosferatul** [comment]
@LWJensen go ahead!
