### ISSUE TITLE
LocalBearTestHelper: delete unused import `collections`

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala-bears#1057]

**Comment by atemafac** [comment]
please i will need more information on this issue.

**Comment by Mixih** [comment]
@atemafac didn't you already request an issue?

**Comment by sounak98** [comment]
I can take this up.

**Comment by Mixih** [comment]
@sounak98 Aren't you already working on a newcomer issue? If you are and have finished, check out a difficulty/low issue!

**Comment by CormacGG** [comment]
Hi, I would like to try this one out :)

**Comment by Mixih** [comment]
I don't think you're assigned to anything else so sure@CormacGG

**Comment by Mixih** [comment]
@CormacGG wait.... I can't assign you until you join the group. Goto the gitter(https://gitter.im/coala/coala) and type `hello world`

**Comment by CormacGG** [comment]
Okay, just joined

**Comment by CormacGG** [comment]
Could I be assigned to this now?

**Comment by Makman2** [comment]
sure :)
