### ISSUE TITLE
Windows installation broken

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1062]
Seems to be an upstream issue, so I raised the bug in setuptools.
https://github.com/pypa/setuptools/issues/861

Probably also need to notify the `safety` maintainer.

**Comment by jayvdb** [comment]
If the requirement is changed to `setuptools<=28.8.0`, we see the following error:

```
%CMD_IN_ENV% python setup.py install
...
Installed c:\python34\lib\site-packages\coala-0.10.0.dev99999999999999-py3.4.egg
Processing dependencies for coala==0.10.0.dev99999999999999
error: setuptools 18.2 is installed but setuptools>=19.2 is required by {'PyPrint'}
```

**Comment by Mixih** [comment]
This has been temporarily patched by coala/coala#3119. Keep this issue open until upstream updates and we can remove the hotpatch.

**Comment by Mixih** [comment]
Upstream has patched. @jayvdb @sils How should we remove the hotpatch?

**Comment by jayvdb** [comment]
Revert the patch should be enough.
IMO it isnt worthwhile listing this or any other broken setuptools version as incompatible; there are too many to list, especially .0 releases.

**Comment by sils** [comment]
nice :) I agree if it works, just revert the patch
