### ISSUE TITLE
Elm Linting

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#1073]
There's a few elm linting and formatting tools out there that we can integrate.

I'm thinking about using elm for [the new gitmate](https://gitlab.com/gitmate/gitmate-2/) so we probably wanna have elm linting :)

So... which tools are best?

**Comment by sils** [comment]
- https://github.com/avh4/elm-format for auto formatting

**Comment by sounak98** [comment]
I'll take this up?

**Comment by sils** [comment]
yes please :)

**Comment by Shade5** [comment]
Hey, still working on this?

**Comment by yash-nisar** [comment]
This hasn't been touched for 3 months. Can I take this up @meetmangukiya @aptrishu ?
