### ISSUE TITLE
The bear HaskellLintBear raised an exception

### ISSUE THREAD

**Issue by wisn** [coala/coala-bears#1079]
I've used HaskellLintBear to linting https://github.com/wisn/elm-reactor/

Here is the log
https://travis-ci.org/wisn/elm-reactor/builds/180417562

The build result is green, but the bear HaskellLintBear raised an exception.

It seems HaskellLintBear have a problem
```
[WARNING][14:56:00] Bear HaskellLintBear failed to run. Take a look at debug messages (`-V`) for further information.
```

I've collected the traceback information:
```
Traceback (most recent call last):
  File "/coala-bears/bears/haskell/HaskellLintBear.py", line 41, in process_output
    assert issue['startLine'] == issue['endLine']
  AssertionError

  File "/coala-bears/bears/haskell/HaskellLintBear.py", line 45, in process_output
    newline = line_to_change.replace(issue['from'], issue['to'])
  TypeError: Can't convert 'NoneType' object to str implicitly
```

I think `TypeError: Can't convert 'NoneType' object to str implicitly` is the main problem.
Then, followed by `AssertionError`.

Unfortunately, I can't trace manually with `hlint` because my PC freezes when compiling (in installing) it. Hope this information will be helpful. Thanks and sorry for my bad English...

**Comment by Makman2** [comment]
Thanks for the report, appreciate it :+1:
