### ISSUE TITLE
FilenameBear: default naming convention should be language specific in some cases

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1083]
Each language has different naming conventions that are very widely accepted.

- python: snake
- javascript: snake with hyphens
- java: pascal

If it is too controversial to add this to the bear, setting the better default could be done in [coala-quickstart](https://github.com/coala/coala-quickstart), or quickstart could detect the predominate style.  This problem came up regularly in the GCI linting tasks done by Besut Kode Universitas participants.

**Comment by jayvdb** [comment]
See https://github.com/bartvandebiezen/file-name-conventions for some collected notes on this topic.

**Comment by meetmangukiya** [comment]
`coala` itself doesn't use snake case for filenaming :worried:

**Comment by Makman2** [comment]
it's just about defaults, coala would obviously not stick to the python default :)

**Comment by yash-nisar** [comment]
So should we ask the user to define the file naming convention instead ? @jayvdb @Makman2

**Comment by Makman2** [comment]
this is already possible, though sometimes you want to rely on the default settings for your language without specifying the naming-convention-setting.

**Comment by meetmangukiya** [comment]
This can be better implemented and maintained this way IMO:
- Create a dict that contains extensions as keys and lambdas that accept filename as argument and return the standard naming convention compliant name
- Then try 
```
try: 
  dict[extension](filename) 
except KeyError:
  # some nice message ?
```

This way there will be much less `if`s if we want to add other language supports in future :)

**Comment by jayvdb** [comment]
The default is currently `snake`.

Ideally, we change the default `file_naming_convention` to `None`, but then we have two paths forward if the user doesnt set a value

1. use `snake`, but warn the user that they should be explicit, and allow `auto` for the user to explicitly request that we guess the right convention
2. guess the `file_naming_convention`, and fall back to `snake` if not known
3. guess the `file_naming_convention`, and skip the file if not known

Only the first is backwards compatible.  The other two are reasonable changes of behaviour.

Can we think of any other strategies?

**Comment by Makman2** [comment]
maybe make use of the `language` setting?

**Comment by yash-nisar** [comment]
We have indirectly implemented 2 currently and the user can explicitly specify the `file_naming_convention` in the `language` setting of the `.coafile`. Now the main question is should we go with `snake` as the default one or set it to `None` ? CC @jayvdb @Makman2

**Comment by yash-nisar** [comment]
Can be merged after https://github.com/coala/coala-bears/issues/1533

**Comment by Makman2** [comment]
I'm for setting it to `None`, it's imo the better default behaviour.

**Comment by yash-nisar** [comment]
Roger that @Makman2 :)

**Comment by Makman2** [comment]
> 1. use snake, but warn the user that they should be explicit, and allow auto for the user to explicitly request that we guess the right convention

I would use `auto` in that case, it confuses the user if we directly choose a non-fitting convention for the given language.
