### ISSUE TITLE
XMLBear: Add severity to messages

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1099]
XMLBear emits all messages at the same severity "NORMAL", however the underlying linter has errors, warnings and it emits formatted XML which the bear is treating as gospel when in fact its formatting is terrible.
(with some caveats: https://github.com/coala/coala-bears/issues/1098)

MAJOR should be for errors, and maybe some of the more critical warnings, NORMAL for all other warnings, and INFO for miscellaneous information and its default style choices.

With proper severity for this bear, the user can then say they only want MAJOR to know about real problems, and INFO if they want to adopt the default xmllint style.

**Comment by yukiisbored** [comment]
May I take this one?

**Comment by sils** [comment]
@yukiisbored sure!

@jayvdb why is this medium and not low difficulty?

**Comment by jayvdb** [comment]
medium, because the unit tests are going to need to be revised quite a bit to properly test the new severities.
