### ISSUE TITLE
InvalidLinkBear: Ignore multiple urls 

### ISSUE THREAD

**Issue by svx** [coala/coala-bears#1106]
Hi,

question, we are using coala for running multiple checks against our documentation, is there an easy way to tell  InvalidLinkBear to ignore various links like for example 127.0.0.1, localhost:8080 etc ?

We tried that with:
```
link_ignore_regex = .....
```

Thing is, this is getting 'messy' if you have more than a couple of links and at least for us, it is also not working well, yet :)

Thanks !

**Comment by sils** [comment]
Hi, I don't think there's an option but we should certainly introduce one, I'm looking into the source right now.

**Comment by sils** [comment]
Ok, there's definitely no such thing but it's probably easy to implement:

@svx what would be your ideal way to configure this?

**Comment by svx** [comment]
@sils I guess there are different options, personally I would like to do that in my .coafile, so that I have all configuration in one place, maybe something like:

```
links_to_ignore  = """http://coalaisthebest.com/
        http://httpbin.org/status/404
        localhost:8080
        http://httpbin.org/status/410
        http://httpbin.org/status/500
        http://httpbin.org/status/503
        http://www.notexample.com/404
        http://exampe.com/404
        http://example.co.in/404"""
```

**Comment by sils** [comment]
maybe allow a list of globs instead of the regex? Like `http://coalaisthebest.com/**` or `http://coalaisthebest.com/*/index.html` and allow it to be ]comma separated?

**Comment by svx** [comment]
Yeah that would be awesome !

**Comment by sils** [comment]
Ok, this is super simple to implement, add the setting and use coala's fnmatch function to match the URL in line 52 of InvalidLinkBear.py. @svx interested in helping out?

As soon as the fix is on master, it'll be available as a prerelease on pypi so you can use it right ahead even without a major release.

**Comment by svx** [comment]
@sils I am more than willing to contribute nice docs and a asciinema, unfortunately I do not speak python but if I can help in another way let me know !

**Comment by sils** [comment]
Cool, we'll get it done within a week or so I guess. Ping me if not, I'll then take care of this but ATM I'm too busy ;)

**Comment by sils** [comment]
Assiging @dracarys09 due to interest on gitter.

**Comment by dracarys09** [comment]
@sils Can you  please guide me a little about how to reproduce this issue and what is needed to be changed to solve this issue ?

**Comment by svx** [comment]
Nice ! Awesome ! Cool !

**Comment by sils** [comment]
@dracarys09 just add a setting to the InvalidLinkBear as described in the discussion. Ask on gitter if you need more info, I'm busy with other stuff right now.

**Comment by dracarys09** [comment]
@sils @Mixih as we discussed earlier, I figured out a way to use coala's fnmatch function to solve this.
The only thing I don't understand is if someone mentions ```links_to_ignore``` in .coafile how to pass the same in find_links_in_file() method in InvalidLinkBear.py

Present Code : ```find_links_in_file(file, timeout, link_ignore_regex)```
Required Change : ```find_links_in_file(file, timeout, link_ignore_regex, links_to_ignore)```
where links_to_ignore is defined in .coafile in a format mentioned by @svx in https://github.com/coala/coala-bears/issues/1106#issuecomment-265699985

**Comment by Makman2** [comment]
Please read bear docs on how to define/receive settings from a coafile, https://api.coala.io/en/latest/Developers/Writing_Bears.html#communicating-with-the-user

**Comment by dracarys09** [comment]
@Makman2  Thanks a lot...
