### ISSUE TITLE
Remove star imports

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1125]
Replace the following `*` imports with explicit imports, to help prepare for https://github.com/coala/coala/issues/3066

```
tests/BearTestHelper.py:6: 'from coalib.testing.BearTestHelper import *' used; unable to detect undefined names
tests/BearTestHelper.py:6: 'coalib.testing.BearTestHelper.*' imported but unused
tests/LocalBearTestHelper.py:6: 'from coalib.testing.LocalBearTestHelper import *' used; unable to detect undefined names
tests/LocalBearTestHelper.py:6: 'coalib.testing.LocalBearTestHelper.*' imported but unused
```

**Comment by mamakancha** [comment]
Hi. I would like to give this one a try.

**Comment by mamakancha** [comment]
@jayvdb  I can't seem to find the python files with names **BearTestHelper.py** and **LocalBearTestHelper.py** in tests/ 
Can you help me with this problem? May be I am missing out on something.

**Comment by mamakancha** [comment]
@jayvdb I opened these files, Could not find any star imports in any of them. What should I do?

**Comment by mamakancha** [comment]
@jayvdb How to know which explicit imports should be used?

**Comment by Makman2** [comment]
Delete those start imports, run tests or just try to import those files in python interpreter and see what's missing in the errors

**Comment by jayvdb** [comment]
Unassigning due to no pull request after 7 days.
@mamakancha , let us know if you're intending to finish this soon, and you can be re-assigned if nobody else has started it.

**Comment by vijeth-aradhya** [comment]
@jayvdb I'm new to `Coala` and I would like to be assigned to fix this issue

**Comment by vijeth-aradhya** [comment]
@jayvdb I have the dependencies :+1: I'm just waiting to be assigned :smiley:

**Comment by jayvdb** [comment]
This is a bit odd, but if @vijeth-aradhya  can do https://github.com/coala/coala-bears/issues/1195 , and @Techievena does https://github.com/coala/coala-bears/issues/1190 , this problem magically disappears.

**Comment by jayvdb** [comment]
Completed with those two PRs.  Nicely done.
