### ISSUE TITLE
README.rst: link is broken in 'Getting Involved' section

### ISSUE THREAD

**Issue by iamprakashom** [coala/coala-bears#1148]
Link for [`Getting In Touch`](http://coala.readthedocs.io/en/latest/Help/Getting_In_Touch.html) and [`newcomer guide`](http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html) is broken.

I think it should be updated with [this](http://docs.coala.io/en/latest/Help/Getting_In_Touch.html) and [this](http://coala.io/newcomer) respectively.

**Comment by ashwani99** [comment]
Is this issue still open? Can I try this?

**Comment by yash-nisar** [comment]
The links have been fixed and so this can be closed. :)

**Comment by Makman2** [comment]
yes this is fixed :+1:
