### ISSUE TITLE
Rename PycodestyleBear to PyCodestyleBear

### ISSUE THREAD

**Issue by andreiraduta1101** [coala/coala-bears#1152]

**Comment by sils** [comment]
use http://api.coala.io/en/latest/coalib.bearlib.html?highlight=deprecate#coalib.bearlib.deprecate_bear

**Comment by userzimmermann** [comment]
@sils I insist on `PyCodeStyleBear` :P

**Comment by sils** [comment]
Renaming is not possible as windows doesn't distinguish casing. This won't work and lead to loads of problems.
