### ISSUE TITLE
SpaceConsistencyBear: Remove Windows carriage return

### ISSUE THREAD

**Issue by abhsag24** [coala/coala-bears#1180]
it is an ugly `^M` that crops up if you use vim on windows and most of the other editors without configuration as well. if `allow_trailing_whitespaces = False` we should replace this character as well.
More on carriage return [here](http://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it)

**Comment by Makman2** [comment]
hm carriage return is default on windows. It's quite unusual to see a simple line feed in text files on windows^^
Actually vim is responsible not to print `^M`

Don't want to turn down this issue, I'm just not sure whether we should handle it like you want^^

**Comment by abhsag24** [comment]
@Makman2 hmm i get what you mean. Any suggestions though? those files look awfully ugly on linux.

**Comment by Makman2** [comment]
If you use git or other VCSes there should be configurations to change checkout and commit behaviour regarding newline conventions.
If you make cross-system work without something like a VCS and with tools that are (sadly :/ ) not smart enough to handle \r\n , it's bad luck imo, sorry :(

I would vote for a wontfix, this is something we should discuss at Microsoft :P :P

**Comment by jayvdb** [comment]
Agree with @Makman2 in general, that this should be dealt with using the VCS level.

(Another approach is a GitAttributesBear, which aggressively requires that .gitattributes is kept up to date.)

However, sometimes DOS eols are accidentally added on Linux. e.g. https://github.com/discourse/discourse_docker/pull/312

But DOS eols are appropriate on DOS, if the VCS will auto-fix them, so a bear can not blindly remove them.

I think this general problem is better as part of a new bear ( https://github.com/coala/coala-bears/issues/1000 ), which can grow separately with a special interest in cross-platform problems.

SpaceConsistencyBear has this horrible "use_spaces" setting which can only be True or False, which make it unusable on files with a bit of both (which in the real world, happens, and we dont deal with it).  (SpaceConsistencyBear also handles tabs extremely badly, but I have a 99% patch for that.)

**Comment by Makman2** [comment]
> I think this general problem is better as part of a new bear ( #1000 ), which can grow separately with a special interest in cross-platform problems.

Agree :+1:

**Comment by abhsag24** [comment]
@jayvdb @Makman2 do we need an issue for this new bear? :P

**Comment by Makman2** [comment]
@abhsag24 you can file one, but I think the issue should come with some design, as I have currently no idea how and where this should work :)

**Comment by jayvdb** [comment]
@abhsag24 , already exists see https://github.com/coala/coala-bears/issues/1000
