### ISSUE TITLE
MarkdownBear: Line length is not being enforced

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-bears#1181]
The linter used by MarkdownBear (remark) can be configured to enforce the line length. It should be enabled because it's part of the linter's feature.

**Comment by Mixih** [comment]
Yeah, we should add another param to the bear. At the very least, the default configuration should be enabled.

**Comment by namanyadav12** [comment]
Hi, Can i be assigned this isssue.

**Comment by jayvdb** [comment]
Note that this was implemented using remark-lint, which was bug https://github.com/coala/coala-bears/issues/926
