### ISSUE TITLE
JSONFormatBear cant handle a BOM

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1205]
needs to strip the BOM before loading, or other alternatives.
http://stackoverflow.com/questions/13156395/python-load-json-file-with-utf-8-bom-header

Found during [GCI CI2 task](https://travis-ci.org/GnarledHarpy06/Aurora/builds/186522902#L174) , processing [antonpup/Aurora](https://github.com/antonpup/Aurora/blob/b5afde5/Project-Aurora/kb_layouts/Corsair/layout.intl.json)
https://clbin.com/jJAxw

```
Project-Aurora/kb_layouts/Corsair/layout.intl.json
|    | [NORMAL] JSONFormatBear:
|    | This file does not contain parsable JSON. 'Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)'
```

**Comment by sils** [comment]
this should be solved in coala

**Comment by jayvdb** [comment]
This can also be handled by creating a BOMBear , like the [EOLBear](https://github.com/coala/coala-bears/issues/815), because 99% of the time they are added by Microsoft tools and they are unnecessary junk.

**Comment by sils** [comment]
created https://github.com/coala/coala-bears/issues/1207 for the BOMBear

**Comment by sils** [comment]
Related: https://gitlab.com/coala/coala-utils/merge_requests/28
