### ISSUE TITLE
In GitCommitBear.py change :param regex: to :param shortlog_regex:

### ISSUE THREAD

**Issue by dracarys09** [coala/coala-bears#1217]

**Comment by KirillZhingalov** [comment]
Here only need to change the line 96?
And that's all?

**Comment by dracarys09** [comment]
@KirillZhingalov yes that's all... would you like to work on this ?

**Comment by KirillZhingalov** [comment]
Yes, of course)

**Comment by dracarys09** [comment]
ask on gitter with a link to this issue... our maintainers will assign you...  :smile:

**Comment by dracarys09** [comment]
@KirillZhingalov you can refer http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html to update commit message in your PR...

**Comment by dracarys09** [comment]
@KirillZhingalov you still working on this issue ?

**Comment by sims1253** [comment]
unassigned due to inactivity
