### ISSUE TITLE
MatlabIndentationBear.py: Add asciinema

### ISSUE THREAD

**Issue by Elgayar** [coala/coala-bears#1221]
The coala bear MatlabIndentationBear.py does not have an asciinema.

**Comment by IpshitaC** [comment]
Hi! Is this assigned to someone? Can I take this up? @sils

**Comment by sils** [comment]
@Elgayar are you still working on this?

**Comment by sils** [comment]
@IpshitaC please evaluate the work of @Elgayar and see if you can reuse it in a meaningful way, it sucks to just throw away someones work. If you do give credit.

**Comment by Udayan12167** [comment]
@IpshitaC ping! This issue is assigned to you. Please show some activity?

**Comment by Udayan12167** [comment]
@IpshitaC Unassigning as you already did a newcomer issue.

**Comment by johnnyczhong** [comment]
I've tried to have cobot assign this issue to me with no success and it looks like it hasn't gone addressed for over a month. Can I ask that someone assign this newcomer task to me? Thanks!
