### ISSUE TITLE
CSSLintBear:  Error while adding ignore comment

### ISSUE THREAD

**Issue by hemangsk** [coala/coala-bears#1225]
Steps for reproduction:

1. Create file style.css
```
.low{
font-family:Roboto;
color:white;
}

```
2. Execute `coala --bears CSSLintBear --files style.css`
```
style.css
|   1| .low•{
|    | [NORMAL] CSSLintBear:
|    | Rule doesn't have all its properties in alphabetical order. (order-alphabetical)
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 2
|    | Please enter a value for the parameter 'language' (No description given.): css
[ERROR][14:26:06] Failed to execute the action IgnoreResultAction with error: 'comment_delimiter'.
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 2
|    | Please enter a value for the parameter 'language' (No description given.): css
[ERROR][14:26:13] Failed to execute the action IgnoreResultAction with error: 'comment_delimiter'.
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit): 2
|    | Please enter a value for the parameter 'language' (No description given.): scss
[ERROR][14:26:19] Failed to execute the action IgnoreResultAction with error: .
```
It is asking for the parameter 'language' from the user and then if there is no language found with name `css`, it returns 
```
Failed to execute the action IgnoreResultAction with error: 'comment_delimiter'.
```

I've been thinking about a few things we can improve here,

- Better message while asking language, 
Instead of
```
Please enter a value for the parameter 'language' (No description given.): 
```
Something like
```
Please enter description for the following parameters,
Language : 
```

- The Error message can also be formatted in the same way,
```
 Failed to execute the action IgnoreResultAction with error: 'comment_delimiter'.
```
to
```
Can't find the following attributes for this language,
comment_delimiters

Unable to execute the IgnoreResultAction.
```
What do you say team?

**Comment by sils** [comment]
Ah damn, coala doesn't know how to make single line comments in CSS, does that even exist?

**Comment by hemangsk** [comment]
Those CPP style `/* */` do work in CSS

**Comment by hemangsk** [comment]
Lets patch the bear  🚀  can I work on this ?

**Comment by sils** [comment]
it's actually not the bear but a coala builtin mechanism, ignoring results is totally independent of the bear, do a `git grep Ignore` and you'll find an IgnoreResultAction or something

**Comment by hemangsk** [comment]
Oh okay so I get the picture.. IgnoreResultAction uses (comment_delimiter) attribute, and in CSS.py [here](https://github.com/hemangsk/coala/blob/master/coalib/bearlib/languages/definitions/CSS.py) we have the `multiline_comment_delimiter` but not the comment_delimiter.
We can add option in IgnoreResultAction.py use `multiline comment delimiters` if `comment delimiter` attribute do not exist in the language

**Comment by hemangsk** [comment]
Moving the discussion to [coala/coala](https://github.com/coala/coala/issues/3441)
