### ISSUE TITLE
InvalidLinkBear: timeout setting not deprecated

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1244]
https://github.com/coala/coala-bears/pull/877 renamed `timeout` to `network_timeout` without deprecation.

**Comment by meetmangukiya** [comment]
Oh.. my bad, wanna wait until someone picks up, or I deprecate it and make a PR?

**Comment by Mixih** [comment]
pick it up.... It's important for release

**Comment by meetmangukiya** [comment]
This should be difficulty/newcomer, it is just one line :/
