### ISSUE TITLE
Backports for 0.9.2 

### ISSUE THREAD

**Issue by Mixih** [coala/coala-bears#1245]
The following pulls need backport documentation/backports for the bears 0.9.2 release:
- [x] aa76d08a1877669f5925805556f38320cc91838d 120bed08cc7562e5a2ab9f6bd645c3d4fca18439
~~(needed: the pyflakes pin)~~
- [x] 0c8c48e671ee2366a4002b79146b9896a0ace814  InvalidLinkBear.py: Increase default_timeout value 
~~- [ ] (when completed) https://github.com/coala/coala-bears/pull/1100~~ moved to 0.9.3 since there is an urgent isntall fix here

**Comment by Mixih** [comment]
wait, pyflakesbear is new this round and thus we dont need the pyflakes backport right(since the radon fix should have fixed the issue)?

**Comment by jayvdb** [comment]
The uncontrollable part of the pyflakes problem was between autoflake(pyflakes) and radon(flake8).
autoflake pinned their pyflakes, which temporarily solved out problem.

**Comment by Mixih** [comment]
completed two issues moved.
