### ISSUE TITLE
http://stylelint.io/

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#1255]

**Comment by sils** [comment]
related: https://github.com/CSSLint/csslint/issues/626#issuecomment-270292514

**Comment by nemaniarjun** [comment]
CSSComb already has an issue. https://github.com/coala/coala-bears/issues/28
So old :p

**Comment by sils** [comment]
Somebody needs to investigate the tool, check if it's useful for us, if it is, use [this tutorial](https://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html) to integrate it into coala

**Comment by dracarys09** [comment]
I would like to work on this issue...

**Comment by dracarys09** [comment]
This tool has some promising reviews, I'm also trying my hand at it... IMO I think we should write a bear using this tool... I'm going ahead with this task... 

https://code.facebook.com/posts/879890885467584/improving-css-quality-at-facebook-and-beyond
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/articles.md
https://css-tricks.com/stylelint/
