### ISSUE TITLE
provide a default value when a settings-question is left empty

### ISSUE THREAD

**Issue by abit2** [coala/coala-bears#1262]
http://pastebin.com/jkPW92mA

it should be something like this:
Please provide a value for `use_spaces` (True or False), when you don't enter something, the default is `True`:

To reproduce the problem just skip the use_space without giving any boolean value.

**Comment by jayvdb** [comment]
I suspect that this will need to be solved in [`coala`](https://github.com/coala/coala), rather than in the bear.

**Comment by CosminIcatoiu** [comment]
I would like to try this. From what i checked the changes have to be in ConsoleInteraction.py where some conditions have to be added. The only problem is that the message seems to be rather general so another one should be added if we want it displayed as @abit2 said. Should it be modified somewhere else, or changed in another way?

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala/issues/3558

**Comment by Makman2** [comment]
or shall we keep this issue open to implement this feature in all bears?
