### ISSUE TITLE
SpaceConsistencyBear: Add Newline to EOF

### ISSUE THREAD

**Issue by fneu** [coala/coala-bears#1263]
Do **not** just propose to delete the last freaking line :joy:

currently happening at https://github.com/coala/documentation/pull/380

![spectacle n32509](https://cloud.githubusercontent.com/assets/7591685/21696716/8616366e-d38f-11e6-94a5-3a59dbc700c2.png)

**Comment by aptrishu** [comment]
There is an issue related to it https://github.com/coala/coala/issues/2006 . Also a PR on gitlab.

**Comment by fneu** [comment]
Ah gotcha, so this is a problem with the diff presentation and not the SpaceConsistencyBear itself. I'm gonna go ahead and close this, then.
