### ISSUE TITLE
master build broken

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1270]
Empty commit on recent master:
https://github.com/coala/coala-bears/pull/1269
-->
https://travis-ci.org/coala/coala-bears/builds/189635508

**Comment by jayvdb** [comment]
Looks like an upstream problem in language check pacKage
```
Could not parse Java version from """java version "9-ea"
  Java(TM) SE Runtime Environment (build 9-ea+140)
  Java HotSpot(TM) 64-Bit Server VM (build 9-ea+140, mixed mode)
```

And something wrong with Infer also.

**Comment by Makman2** [comment]
Parsing bug for language-check filed upstream: https://github.com/myint/language-check/issues/31

**Comment by Makman2** [comment]
Looks like a java update, we get something similar for infer:
```
javac: option --boot-class-path not allowed with target 1.9
make[3]: *** [models/infer/report.json] Error 2
make[3]: Leaving directory `/home/travis/infer-linux64-v0.7.0/infer/models/java'
make[2]: *** [java] Error 2
make[2]: Leaving directory `/home/travis/infer-linux64-v0.7.0/infer/models'
make[1]: *** [java] Error 2
make[1]: Leaving directory `/home/travis/infer-linux64-v0.7.0/infer'
make: *** [java] Error 2
  compilation failure; you can try running
    make clean
    ./build-infer.sh java
```

**Comment by Makman2** [comment]
ah `-ea` means early-access... Not cool to use that

**Comment by sils** [comment]
@nemaniarjun wanted to look into this, please report your findings here. It's critical to document what you do since this is urgent so it can be picked up by someone whenever he finds time.

**Comment by nemaniarjun** [comment]
The error is here.
The java version on our ci is

java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+140)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+140, mixed mode)
We need to change the regex.

**Comment by nemaniarjun** [comment]
Started a PR at upstream.
Maybe look into why we are using the `-ea` version.
