### ISSUE TITLE
XMLBearDTDUrlTest test is failing

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-bears#1275]
coala version: `0.9.1`
coala-bears version: `0.10.0.dev999999`
`python 3.5.2  Ubuntu 16.04`
Installed test-dependencies from `coala-bears/test-requirements.txt`.

To reproduce:
Run `py.test -k XMLBearDTDUrlTest`

![screenshot from 2017-01-07 19-57-46](https://cloud.githubusercontent.com/assets/10217535/21742373/a3722a8a-d513-11e6-83df-2582b9edbbd4.png)

**Comment by Makman2** [comment]
This test works fine in our CI -> https://circleci.com/gh/coala/coala-bears/4777?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

We need a bit more background from you: Which coala version do you use? Did you try to update to latest `--dev` version? Did you update all dependencies? OS? Python version? Something else that could be important?

**Comment by satwikkansal** [comment]
@Makman2 Sorry, Just edited the description.

**Comment by Makman2** [comment]
Also `requirements.txt` installed?

**Comment by namanyadav12** [comment]
The test fails on my laptop if the internet connection is not working or it is slow and results in timeout.
I guess that might be the problem.

**Comment by satwikkansal** [comment]
@namanyadav12 Thanks, I found what was causing the issue. My university's Ethernet connection uses proxy to filter pages and they blocked the url labeling as `inactive sites`. Tried it on other network and it worked. I should have tried that earlier before creating this issue :disappointed:  Anyways, closing the issue.
