### ISSUE TITLE
InvalidLinkBear does not support percentage-encoded URLs

### ISSUE THREAD

**Issue by Naereen** [coala/coala-bears#1290]
Here is a simple demo:
![invalidlinkbear_does_not_support_percentage-encoded_urls](https://cloud.githubusercontent.com/assets/11994719/21856155/3e045cf2-d821-11e6-9d6a-89b1bd6947c2.png)

- The address in my example is `https://img.shields.io/badge/Maintained%3F-yes-green.svg` (which is valid: giving ![this badge](https://img.shields.io/badge/Maintained%3F-yes-green.svg)),
- But [`InvalidLinkBear`](https://github.com/coala/coala-bears/blob/master/bears/general/InvalidLinkBear.py) sees it as `https://img.shields.io/badge/Maintained` : that's wrong.

**Comment by Naereen** [comment]
It should be easy to fix.

**Comment by jayvdb** [comment]
Any solution needs to imclude tests that include `()` and `%`, and *must* only accept valid percent encoding values after the `%`.

**Comment by Makman2** [comment]
xref https://github.com/coala/coala-bears/pull/932 , which already tries to ignore links with common format placeholders like `%s` or `%f`.

**Comment by jayvdb** [comment]
Also need to test that it verified the correct URL.

**Comment by Naereen** [comment]
I am surprised that you don't use a parser specific to URL, instead of a hand-written regexp.
But maybe it's simpler (and quicker) that way.

**Comment by refeed** [comment]
@jiteshpabla are you still working on this?

**Comment by jiteshpabla** [comment]
@refeed Sadly, no. (Unless anyone else is willing to take over, i request to not be unassigned for the moment)

**Comment by refeed** [comment]
@jiteshpabla Sorry for late reply, btw I could take over this issue :smile:
