### ISSUE TITLE
InvalidLinkBear doesn't check multiple links in a single line

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-bears#1296]
For the content of the file as:
`http://www.some.linkthatdoesnotexist.com/  https://www.google.com `

The output is:
```
[MAJOR] InvalidLinkBear:
|    | Broken link - unable to connect to http://www.some.linkthatdoesnotexist.com/
````

But when switched the order
```
 https://www.google.com http://www.some.linkthatdoesnotexist.com/
```

Nothing is detected

Difficulty - low

**Comment by Makman2** [comment]
uuh that's bad :/
