### ISSUE TITLE
Write test for KeywordBear not offering all patches in results

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1306]
Write test for https://github.com/coala/coala-bears/issues/1274

So this problem never occurs again :)

**Comment by yash-nisar** [comment]
Can I do this ? This has been lying around for a while @Mixih @NiklasMM

**Comment by Techievena** [comment]
Its done. @yash-nisar Just needs a rebase and I think maintainers can cherry-pick or rebase this stuff.

**Comment by yash-nisar** [comment]
Oh I didn't go through the changes :P. Maybe someone should add a process/approved label then. :)

**Comment by khanchi97** [comment]
@namanyadav12 are you still working on this?I want to give it a try :)

**Comment by Makman2** [comment]
Reassigning due to inactivity.
