### ISSUE TITLE
.coafile/coala/TODOS section/KeywordBear: Not working

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1311]
On my branch I use plenty of `FIXME`s, but coala detects none:
```
 mak  ~  dev  coala   Makman2/NEXTGEN3  coala TODOS 
Executing section TODOS...
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] The setting `ci_keywords` is deprecated. Please use `keywords` instead.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
[WARNING][21:52:24] Bear KeywordBear failed to run. Take a look at debug messages (`-V`) for further information.
 mak  ~  dev  coala   Makman2/NEXTGEN3  coala TODOS 
Executing section TODOS...
 mak  ~  dev  coala   Makman2/NEXTGEN3  
```
Also it fails when I change the coafile and rerun. After a second run it executes the section without errors, but with no results either^^

**Comment by Techievena** [comment]
@Makman2 I want to pick up this issue. Can you please share both the coafiles?

**Comment by Makman2** [comment]
It's the coafile from our core repo: https://github.com/coala/coala/blob/master/.coafile

**Comment by Techievena** [comment]
@Makman2 getting this :worried: 
![image](https://cloud.githubusercontent.com/assets/17270966/22014738/265989f8-dcc5-11e6-91ed-0ed587a70d56.png)
and finally it is detecting it 
![image](https://cloud.githubusercontent.com/assets/17270966/22014799/53dafc2c-dcc5-11e6-9e66-4fd065a584b0.png)

**Comment by sils** [comment]
@Makman2 you should use `-V` to see the traceback, the second run is just cached because coala knows that there are no results so that's irrelevant.

**Comment by Techievena** [comment]
@sils How to fix what I'm getting?

**Comment by sils** [comment]
Try changing the language to `python 3` with a space or just python

**Comment by Techievena** [comment]
Thanks!!!

**Comment by Techievena** [comment]
![image](https://cloud.githubusercontent.com/assets/17270966/22015234/390221c6-dcc7-11e6-987b-9e16911b1de1.png)

**Comment by Makman2** [comment]
@sils there wasn't any traceback even with `-V`, I assume I've used a slightly older coala version not printing an error for an invalid language^^

**Comment by Makman2** [comment]
Gets solved by https://github.com/coala/coala/issues/3585
