### ISSUE TITLE
GitCommitBear/body_regex: Use re.fullmatch instead of re.search?

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1331]
I'm for using `re.fullmatch` to match the whole body of the commit. Currently you can work with anchors, but with the restriction that they work only on a single line, as `re.MULTILINE` is not activated for `body_regex`. Like for `shortlog_regex`, I would suggest to use `fullmatch` instead of `search`.

CC @nkprince007

**Comment by nkprince007** [comment]
I do agree to this.
