### ISSUE TITLE
InvalidLinkBear fails on URLs in Markdown link display text and target

### ISSUE THREAD

**Issue by dracarys09** [coala/coala-bears#1338]
```[http://harelba.github.io/q/](http://harelba.github.io/q/)```
Markdown files have links generally in this form...
InvalidLinkBear ```[http://harelba.github.io/q/](http://harelba.github.io/q/)``` takes this as a link to check
However it should only check ```http://harelba.github.io/q/```

**Comment by dracarys09** [comment]
The exact line in the markdown file was ```q's web site is [http://harelba.github.io/q/](http://harelba.github.io/q/). It contains everything you need to download and use q in no time.```

However coala output was

```q's•web•site•is•[http://harelba.github.io/q/](http://harelba.github.io/q/).•It•contains•everything•you•need•to•download•and•use•q•in•no•time.
|    | [NORMAL] InvalidLinkBear:
|    | Broken link - unable to connect to http://harelba.github.io/q/](http://harelba.github.io/q/) (HTTP Error: 404)
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Add ignore comment
|    | Enter number (Ctrl-D to exit):```

**Comment by sils** [comment]
what's the source line?

**Comment by jayvdb** [comment]
This was found as part of CI1 (See spreadsheet).
Which version of the docker image were you using?

https://github.com/harelba/q is the repo.

The line is https://github.com/harelba/q/blame/master/README.markdown#L6

The problem is the second url in `[http://harelba.github.io/q/](http://harelba.github.io/q/)`.

**Comment by jayvdb** [comment]
I think we need to start looking beyond managing a complex regex internally.
https://github.com/coala/coala-bears/issues/1342

**Comment by dracarys09** [comment]
@jayvdb I used 
```language: generic
services: docker
script: docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci```
in .travis.yml file. I used http://coala.readthedocs.io/en/latest/Users/Docker_Image.html#coala-on-travis-ci this link.
However I think the problem is the first url in ```[http://harelba.github.io/q/](http://harelba.github.io/q/)```
because generally in markdown files we use ```[description](actual_url)``` right ?
So ideally we should do a match with second url and not first right ?

**Comment by dracarys09** [comment]
for reference go to regex101.com and use this as regex
((git\+|bzr\+|svn\+|hg\+|)https?:\/\/[^.:%\s_\/?#[\]@\\]+\.((?:[^\s()%\'"`<>|\\\[\]]+)|\([^\s()%\'"`<>|\\]*\))*)(?<!\.)(?<!,)
then use this as test string
[http://harelba.github.io/q/200](http://harelba.github.io/q/200)

This may be helpful in understanding the changes I made in my PR
