### ISSUE TITLE
Compare npm dockerfile_lint and dockerfilelint

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1343]
We currently use [dockerfile_lint](https://github.com/projectatomic/dockerfile_lint)

The alternative, https://github.com/replicatedhq/dockerfilelint , looks interesting also.

Sort of c.f. https://github.com/coala/docker-coala-base/issues/89

**Comment by saurabhmarpadge** [comment]
@jayvdb What do I need to know about dockerfile to solve this issue?

**Comment by yash-nisar** [comment]
There is one more that I just found -> https://github.com/redcoolbeans/dockerlint

**Comment by jayvdb** [comment]
Unassigned due to inactivity.
Im working on this now

**Comment by jayvdb** [comment]
https://www.npmjs.com/package/dockerfilelint and https://www.npmjs.com/package/dockerlint both catch lowercase `run ...`.

dockerfilelint detects apt-get update and requires `rm -rf /var/lib/apt/lists/*` in the same layer. (dockerlint does not)

Neither require an EXPOSE or CMD , which dockerfile_lint does.

However dockerfile_lint is really hard to configure , as the default set of rules cant be disabled easily.  A new rules file copying the original one is needed, and excluding undesirable bits.  That approach means updates to dockerfile_lint to not automatically introduce new rules, as the static customised rules file wont magically include any new rules.

**Comment by jayvdb** [comment]
https://github.com/replicatedhq/dockerfilelint supports a .dockerfilelintrc , which has an easy format for turning off individual rules.

https://github.com/redcoolbeans/dockerlint doesnt appear to have an option to disable rules.

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/issues/2820 created
