### ISSUE TITLE
PyDocStyleBear has conflicting checks enabled by default

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#1345]
Both of these are checked by coala by default:

```
D203	1 blank line required before class docstring
D211	No blank lines allowed before class docstring
```

And both of these:

```
D212	Multi-line docstring summary should start at the first line
D213	Multi-line docstring summary should start at the second line
```

This, obviously, makes it impossible to pass checks with default settings.

See [pydocstyle's default checks docs](http://www.pydocstyle.org/en/latest/error_codes.html#default-checks) for what their configuration is.

**Comment by aptrishu** [comment]
So we should just disable one code ? D203 and D212?

**Comment by aptrishu** [comment]
I'm not able to reproduce it. is any of the two checks already disabled by default by pycodestyle?

**Comment by aptrishu** [comment]
By default we only check for D211..
```Cython
conventions = AttrDict({
    'pep257': set(ErrorRegistry.get_error_codes()) - set(['D203',
                                                          'D212',
                                                          'D213',
                                                          'D404'])
})
```

**Comment by underyx** [comment]
Oh I see, so the problem is that I added an ignore code myself (all public
whatevers must have a docstring) and that enabled the disabled-by-default
ones. Still should be fixed I think.

**Comment by aptrishu** [comment]
So, there are no conflicting checks enabled by default. so what needs to be fixed ?

**Comment by underyx** [comment]
Users should not need to copy the default ignore list if they want to
ignore their own errors.

**Comment by aptrishu** [comment]
Actually what happens is that as we add `--ignore` command, it overrides the default ignore list. we should use `--ad-ignore`..
