### ISSUE TITLE
GhcModBear should have a DistributionRequirement

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1357]
CabalRequirement and DistributionRequirement were created recently. Both should be used for GhcModBear.
(Edited to account for CabalRequirement already being present in GhcModBear)

**Comment by incorrectusername** [comment]
i have done changes [here](https://github.com/incorrectusername/coala-bears/commit/a6013a42218bf29ab5010dba5e367f9de39fbe05). Is there something more need to be done.
Just wanted to be sure that i'm going in right direction?

**Comment by jayvdb** [comment]
Correct direction. ;-)

**Comment by sils** [comment]
@jayvdb @incorrectusername sorry to pull this up too late, didn't see this earlier but: that'd mean that both of those requirements would have to be installed while we only want one, right?

**Comment by incorrectusername** [comment]
@sils @jayvdb There's already one. Which one do we need? Cabal or distribution?
