### ISSUE TITLE
cabal caching

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1380]
ea74d022e used a very basic & manual form of cabal cache checking.
There should be a way to avoid that.

cabal install should be able to check which dependencies are already installed.

Maybe there are more cabal install metadata dirs/files which needs to be preserved between builds.

cc: @vijeth-aradhya

**Comment by vijeth-aradhya** [comment]
I had noticed `cabal` being there, but `cabal-install` had _not_ been installed.
IMHO, at least the `cabal-install` version should be at least what is mentioned in the commit and should be cached ^^ ( at least in Circle, `cabal-install` is not there, in Travis [here](https://github.com/coala/coala-bears/blob/master/.travis.yml#L20), I don't think it's the right version?! _it's using apt package to install, instead so using cabal_ _<.<_ )
Then, we can go ahead and install any other Haskell dependencies.

**Comment by jayvdb** [comment]
We can install any version of cabal-install we need.
This issue is about working out why cabal-install wasnt checking its own cache first before fetching and building and installing packages that it already had.
It will be helpful to have all the `CabalRequirement` added to solve this issue, but not mandatory.

**Comment by vijeth-aradhya** [comment]
What about having `--avoid-reinstalls` flag so that it will not overwrite the installed version?

**Comment by jayvdb** [comment]
Try it?

**Comment by jayvdb** [comment]
Im not sure the caching has been fully fixed.

**Comment by jayvdb** [comment]
The next commit resulted in nicely cached 10s installations of Haskell dependencies.
See https://travis-ci.org/coala/coala-bears/builds/202066799 and https://circleci.com/gh/coala/coala-bears/5452 .
