### ISSUE TITLE
PycodestyleBear: Remove extra ' sign from Message

### ISSUE THREAD

**Issue by Techievena** [coala/coala-bears#1393]
The message displayed by PycodestyleBear contains an extra `'` sign at the end. Examples:
`E305 expected 2 blank lines after class or function definition, found 1'`
`E501 line too long (85 > 80 characters)'`. Fix the regex of PycodestyleBear.

**Comment by jayvdb** [comment]
In 2555651 @sahilarora535 removed the `'` from the cli arg.  I am quite positive that is not correct.
The issue says "Fix the regex of PycodestyleBear."  I assume that there is a regression in either the regex, or ... ?  If it is a regression, we may need to back port the fix to 0.10

**Comment by jayvdb** [comment]
It is also possible that those inner quotes are not necessary.
Test cases are needed, so we can see that the problem has been fixed (https://github.com/coala/coala/issues/3648).

**Comment by dracarys09** [comment]
@sahilarora535 as @jayvdb suggested... seems like those inner quotes are not necessary... so I tried something like...   ```arguments = [r'--format=%(row)d %(col)d %(code)s %(text)s']```
instead of ```arguments = [r"--format='%(row)d %(col)d %(code)s %(text)s'"]``` and it worked... but IMO this is probably just a hacky way to go about this.

**Comment by dracarys09** [comment]
@sahilarora535 for the discussion we had on your commit, I don't think that the ```text``` contains apostrophe of its own... It is also possible that the bug is not in PycodestyleBear but that is for you to find out...  :stuck_out_tongue:

**Comment by sahilarora535** [comment]
@dracarys09 Things are weird this side. I replaced the arguments with this:
`arguments = [r'--format="%(row)d %(col)d %(code)s %(text)s"']`

I also turned on verbose to check what's going on behind the scenes. I get this message:
```bash
[DEBUG][14:09:34] Running bear PycodestyleBear...
[DEBUG][14:09:34] Running 'pycodestyle --format="%(row)d %(col)d %(code)s %(text)s" --max-line-length=79 /home/sahil/workspace/coala-tutorial/src/test.py'
```
With `PycodestyleBear`, I get the following message: `E401 multiple imports on one line"`

I ran the same command mentioned in the debug message: `pycodestyle --format="%(row)d %(col)d %(code)s %(text)s" --max-line-length=79 /home/sahil/workspace/coala-tutorial/src/test.py`

I get this output:
```bash
E401 multiple imports on one line
```
I think the problem is somewhere else, and the arguments in the original code are correct.

**Comment by Makman2** [comment]
> but IMO this is probably just a hacky way to go about this because when we invoke pycodestyle from terminal... the format is pycodestyle <file_name> --format='%(row)d %(col)d %(code)s %(text)s' so I think those inner quotes should be there...

Invoking from shell or directly executing a program is a difference. The shell takes over interpretation of quotes, not the OS. In this case it removes those quotes, you can test it easily with a little script:
```
echo $1
```
And now invoke it with ` --format='%(row)d %(col)d %(code)s %(text)s'`. You'll see that the quotes are gone^^

**Comment by Makman2** [comment]
So yes, just remove those quotes, that should solve it :+1:

**Comment by dracarys09** [comment]
https://github.com/coala/coala-bears/issues/1393#issuecomment-277520844

@Makman2 I tried ```--format='%(row)d %(col)d %(code)s %(text)s This is sparta' and the output was like ```E231 missing whitespace after ','This is sparta'```. So basically whatever is after ```%(text)``` is also coming in the output. But if OS is interpreting this without both quotes then there shouldn't be one extra quote at the end right because both the quotes are removed while we are directly executing a program right ?

**Comment by Makman2** [comment]
no they aren't removed because you don't execute inside a shell ;) The shell removes them and passes the args to the OS :+1:

**Comment by dracarys09** [comment]
> no they aren't removed because you don't execute inside a shell ;) The shell removes them and passes the args to the OS :+1:

I think we need to reopen this then https://github.com/coala/coala-bears/pull/1401

CC @Makman2 @jayvdb @sahilarora535

**Comment by sahilarora535** [comment]
Thank you @Makman2 @dracarys09 . Finally. Learnt a lot here! :smile:

**Comment by jayvdb** [comment]
I've checked the blame on that line, and it is @NiklasMM 's original code.
So, this isnt a regression, so it doesnt *need* to be backport, but a backport to 0.10 would be a nice thing to do.

**Comment by jayvdb** [comment]
Very strange.  I cant reopen https://github.com/coala/coala-bears/pull/1401 .  The re-open button is disabled. @sils, can you?

I havent seen this before, except where the branch was deleted, but .. it exists https://github.com/sahilarora535/coala-bears/tree/fix-py-code-style-bear

**Comment by jayvdb** [comment]
Maybe it is because there has been a force-push after the PR was closed, so it cant be re-opened in the same state.

@sahilarora535 , could you re-force-push ed6651b to that branch ?

**Comment by sahilarora535** [comment]
@jayvdb I have done a re-force-push to the initial state to when the [PR](https://github.com/coala/coala-bears/pull/1401) was closed. Please check the [commit status](https://github.com/coala/coala-bears/pull/1401/commits)

**Comment by jayvdb** [comment]
Woot.  That solved it.  Re-opened.
Ok, now rebase and we can merge ;-)

**Comment by sahilarora535** [comment]
@jayvdb Yeah. I have rebased it, ready for merging. :smile:

**Comment by sils** [comment]
reopening a PR is not possible if there was a push on the branch after.
Though I guess you figured

**Comment by sahilarora535** [comment]
@sils Yeah. I checked  `git reflog`, deleted current branch, and make a branch from the original commit, the one before which the PR was closed, which solved the issue.
