### ISSUE TITLE
Require 100% coverage on Appveyor

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1415]
We had a windows regression in 0.10 because some bears stopped working, and started skipping.
Instead of skipping, the CI script should remove the bears&tests for known unsupported bears /uninstalled dependencies, similar to what the docker image does.

**Comment by nsurampu** [comment]
Can anyone tell me more about this issue? I may take this up

**Comment by Adrianzatreanu** [comment]
@jayvdb is this low or medium? Make up your.mind :D

**Comment by jayvdb** [comment]
There is a specific problem with x64 clang which doesnt occur on the `coala` repo, but does with most of the clang bears.  That is going to be a hard nut to crack.  It will require someone with a Windows machine, and a decent technical knowledge of windows.

**Comment by jack17529** [comment]
@Adrianzatreanu  can you help me:-
1. Test which bear uses clang - Need to check the clang version before installing clang. I think this have been reported already.
2. Test which bear don't work on windows.

Can someone tell me weather I am in the right direction or not.

**Comment by jayvdb** [comment]
Requested codecov support to help us reach this : https://github.com/codecov/support/issues/412

**Comment by jayvdb** [comment]
> Requested codecov support to help us reach this : https://github.com/codecov/support/issues/412

Disappeared.
