### ISSUE TITLE
Most YAML documents use document starts (---)

### ISSUE THREAD

**Issue by adrienverge** [coala/coala-bears#1417]
Hi,

I am the creator of yamllint, the linter coala uses for YAML.

Since #965 was merged three months ago, coala fails on many projects like Ansible, OpenStack and even yamllint itself, because coala doesn't accept document start markers (`---`) anymore.

Document start markers are commonly used, and required when declaring multiple documents in a single `.yaml` file (see [the spec](http://yaml.org/spec/1.2/spec.html#id2800132)).

The proposed fix in the original issue (#923) was to disable the rule, but the implemented fix (#965) made document starts forbidden.

My opinion is that coala should either require document starts, or disable the rule by default.

**Comment by Makman2** [comment]
Agree.

So task is to use `None` as default value [here](https://github.com/coala/coala-bears/blob/master/bears/yaml/YAMLLintBear.py#L27) and if it's used, leave the config value for the rule, if `True` or `False` are passed, configure the rule with `True`/`False`.

**Comment by Makman2** [comment]
Btw one can remove
```
https://github.com/coala/coala-bears/blob/master/bears/yaml/YAMLLintBear.py#L42
```
and directly feed the value of `document-start` into the configuration dictionary^^

**Comment by adhikasp** [comment]
For reference, this fix would be very similliar with https://github.com/coala/coala-bears/pull/1335.
