### ISSUE TITLE
PySafetyBear fails on Ubuntu precise

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1432]
See https://github.com/pyupio/safety/issues/35 .

When reading a `requirements.txt` file, the *ideal* exception to catch varies on the version of pkg_resources that is installed.  In all cases, `ValueError` is acceptable, however, as of setuptools 16 `RequirementParseError` was [introduced](https://github.com/pypa/setuptools/commit/cd79379c95051b94a7fa).

PySafetyBear is currenting using `RequirementParseError`, without specifying a minimum version of `setuptools`.

**Comment by sinwar** [comment]
@jayvdb I am not getting the issue completely.

I tried with ```ValueError``` which is showing that there is no attribute ValueError and ```RequirementParseError``` works well.

Should we add version of pkg_resources in requirements ?

**Comment by jayfk** [comment]
This should no longer be a problem. Safety now explicitly catches `ValueError`s: https://github.com/pyupio/safety/blob/master/safety/util.py#L84-L85

**Comment by jayvdb** [comment]
iirc, this was a problem with old setuptools.

The reported problem is fixed upstream.

Whether it works correctly on Ubuntu precise is likely a mystery for the centuries. Nobody cares any more.
