### ISSUE TITLE
gotype removed

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1472]
All builds failing with
```
$ go get -u golang.org/x/tools/cmd/gotype
package golang.org/x/tools/cmd/gotype: cannot find package "golang.org/x/tools/cmd/gotype" in any of:
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/golang.org/x/tools/cmd/gotype (from $GOROOT)
	/home/travis/gopath/src/golang.org/x/tools/cmd/gotype (from $GOPATH)
```

**Comment by jayvdb** [comment]
So this would be caused by https://github.com/golang/tools/commit/f5a6ee1ea9f7b3a91e3e70dc1b9706886d0e0ae3 
Review: https://go-review.googlesource.com/#/c/37657/

**Comment by jayvdb** [comment]
https://github.com/alecthomas/gometalinter/issues/91 is about the same problem, but they knew about it in advance.
cc @yukiisbored

**Comment by jayvdb** [comment]
Do we try to re-implement this using a different command?  I see quite a few alternatives mentioned in the various issues about this deprecation.

Or deprecate the bear?
If we deprecate it, either we remove it from test coverage, or we need to create our own repo with the old code in it, as the original is gone and go [doesnt do versioning](http://zduck.com/2014/go-and-package-versioning/).

Or do we effectively delete the bear, perhaps with a placeholder to ensure an appropriate warning message is emitted?

**Comment by yukiisbored** [comment]
I'm not quite sure with what's the best option here, `gometalinter` is experiencing the same problem as well.

**Comment by yukiisbored** [comment]
After browsing the repository, it looks like they moved it here: https://github.com/golang/go/blob/master/src/go/types/gotype.go

**Comment by yukiisbored** [comment]
Still have no idea how to use `go get` for that.

**Comment by yukiisbored** [comment]
The best decision that I can think of for now is to deprecate this bear, and use `go build -i`

**Comment by jayvdb** [comment]
If necessary, we can `git clone` the repo, and build the moved tool from the clone?

**Comment by yukiisbored** [comment]
@jayvdb Most likely that's the only option.

**Comment by jayvdb** [comment]
Can we create a copy of just the necessary files, and  put them in a repo, so it is quick to clone and go get also works?
