### ISSUE TITLE
Add min lines to LineCountBear

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1477]
It is especially useful to be able to reject files that have 0 lines by default, and explicitly exclude any files which are explicitly allowed to be 0 lines.

There are other scenarios where a higher minimum is a sensible default, and exceptions should be explicitly mentioned in the repository `.coafile`.

**Comment by damian1996** [comment]
Can you assign me to this issue? :) It seems that this issue is forgotten by the previous contributor :)

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Makman2** [comment]
@damian1996 try to reuse old code if possible, saves work for everyone ;)
