### ISSUE TITLE
Bear proposal: duplicate file detector

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1479]
A duplicate file detector will mostly be used to prevent problematic additions to a repo.

It probably needs to be a global bear.

coala might have all the info it needs for this, in its cache.  But the assumption that the entire repository is in memory is not a good idea.

Typically, the approach used is to compute a simple hash of each file, and then on collision do a more accurate comparison.

This can be done externally using an external tool.
On Linux there is [fdupes](https://en.wikipedia.org/wiki/Fdupes) and [fslint](http://www.pixelbeat.org/fslint/).
fdupes is very commonly used by debian and redhat based distros, often used as a package build dependency to help with the package build process.

fslint is a bit strange on Fedora, as the CLI tools are not installed into the usual `/usr/bin`.
Instead they are installed in the `share` area ([they](https://github.com/pixelb/fslint/tree/master/fslint) are mostly bash scripts with [some](https://github.com/pixelb/fslint/blob/master/fslint/supprt/md5sum_approx) [python](https://github.com/pixelb/fslint/blob/master/fslint/supprt/rmlint/merge_hardlinks)), and `findup` is the CLI tool for finding dups.
```
$ /usr/share/fslint/fslint/fslint --help
File system lint.
A collection of utilities to find lint on a filesystem.
To get more info on each utility run 'util --help'.

findup -- find DUPlicate files
findnl -- find Name Lint (problems with filenames)
findu8 -- find filenames with invalid utf8 encoding
findbl -- find Bad Links (various problems with symlinks)
findsn -- find Same Name (problems with clashing names)
finded -- find Empty Directories
findid -- find files with dead user IDs
findns -- find Non Stripped executables
findrs -- find Redundant Whitespace in files
findtf -- find Temporary Files
findul -- find possibly Unused Libraries
zipdir -- Reclaim wasted space in ext2 directory entries
$ /usr/share/fslint/fslint/findup --help
find dUPlicate files.
Usage: findup [[[-t [-m|-d]] | [--summary]] [-r] [-f] paths(s) ...]

If no path(s) specified then the current directory is assumed.

When -m is specified any found duplicates will be merged (using hardlinks).
When -d is specified any found duplicates will be deleted (leaving just 1).
When -t is specfied, only report what -m or -d would do.

When --summary is specified change output format to include file sizes.
You can also pipe this summary format to /usr/share/fslint/fslint/fstool/dupwaste
to get a total of the wastage due to duplicates.

Examples:

search for duplicates in current directory and below
    findup or findup .
search for duplicates in all linux source directories and merge using hardlinks
    findup -m /usr/src/linux*
same as above but don't look in subdirectories
    findup -r .
search for duplicates in /usr/bin
    findup /usr/bin
search in multiple directories but not their subdirectories
    findup -r /usr/bin /bin /usr/sbin /sbin
search for duplicates in $PATH
    findup $(/usr/share/fslint/fslint/supprt/getffp)
exclude zero length files from the search
    findup / -size +0c
search system for duplicate files over 100K in size
    findup / -size +100k
search only my files (that I own and are in my home dir)
    findup ~ -user $(id -u)
search system for duplicate files belonging to roger
    findup / -user $(id -u roger)
```

**Comment by Makman2** [comment]
> But the assumption that the entire repository is in memory is not a good idea.

This does happen currently anyway. `FileProxy` might solve this^^

**Comment by jayvdb** [comment]
> This does happen currently anyway.

Right, but a bear relying on that quirk would be very bad if coala is to be used in large projects (and get customers with serious money).

> FileProxy might solve this^^

The FileProxy spec, and code that I have seen, would encourage bears to rely on the anti-pattern that the entire codebase being analysed can be accessed randomly in memory, which is terrible unless the time has been put into designing appropriate mechanisms to do cache eviction.

**Comment by jayvdb** [comment]
re fdupes and findup, they are both available on Linux, but are they cross platform?
fdupes is C, so it should win on performance. But is fdupes portable to Windows? etc. etc.
findup is bash + python, so should be portable, but do they provide a Windows version?
If neither support Windows, is there a way to do the same on Windows?
