### ISSUE TITLE
inaccurate results on search

### ISSUE THREAD

**Issue by incorrectusername** [coala/coala-bears#1499]
when searched for `html` on http://coala.io/#!/languages we get search results for language tag for java , python , etc.
even there is no html language tag with them.

**Comment by nemaniarjun** [comment]
I think this should be opened on the Gitlab Repo for landing. https://gitlab.com/coala/landing

**Comment by incorrectusername** [comment]
there it said `If you find an issue with this documentation, you can report it at the coala-bears repository.`
do i move it?

**Comment by Makman2** [comment]
please move it :)
(and reference this issue so we don't miss something :+1:)

**Comment by incorrectusername** [comment]
Moved to https://gitlab.com/coala/landing/issues/34
