### ISSUE TITLE
ScalaLintBear.py PEP8 format errors

### ISSUE THREAD

**Issue by theaverageguy** [coala/coala-bears#150]
![m](https://cloud.githubusercontent.com/assets/9817962/13510722/e4dc41cc-e1b7-11e5-9969-ae0dcac1a008.png)

Difficulty/beginner

**Comment by AbdealiJK** [comment]
This seems like the exact same errors you've gotten for `setup.py` in https://github.com/coala-analyzer/coala-bears/issues/150 . Have you mixed up the screenshots ?
I can't see line 15 being an issue about module level imports

**Comment by Makman2** [comment]
@theaverageguy please supply a complete screenshot, so we can see the actual commands to reproduce this (though we have coala, but anyway :+1:)

**Comment by theaverageguy** [comment]
Sorry about the image, changed it. Please take a look.

**Comment by Makman2** [comment]
@theaverageguy are these all issues? before there were 2 :O

**Comment by jayvdb** [comment]
This has been fixed.
