### ISSUE TITLE
PythonPackageInitBear: Move class level doc string into `run` method so that coala gets correct metadata 

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-bears#1500]

**Comment by yash-nisar** [comment]
We already have an approved PR [here](https://github.com/coala/coala-bears/pull/1767) @harryjas :(

**Comment by harryjas** [comment]
@yash-nisar  My bad because i found it open.
But circleci is showing TextLintBearTest.test_bad_alex_no_dead_link error. 
Can you help me with this ?

**Comment by yash-nisar** [comment]
Sure, try rebuilding without cache and that should solve the problem :)
