### ISSUE TITLE
Try to provide class SomeBear(..., aspects=[...]) syntax via metaclass magic :)

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala-bears#1517]
As proposed by me in https://github.com/coala/coala-bears/pull/1391

@sils I wonder if this is possible ;)

**Comment by Techievena** [comment]
Won't DETECT_ASPECTS and FIX_ASPECTS metadata be sufficient to link with the kind of aspects for the bear? We can use some metaclass approach surely after detecting the aspect for the bear.

**Comment by Techievena** [comment]
Moreover I think this issue fits better in core repo rather

**Comment by userzimmermann** [comment]
It's just an idea... Or course we can talk about that later after the actual functionality is implemented and first use `DETECT_ASPECTS` and `FIX_ASPECTS` :)
