### ISSUE TITLE
Add shellcheck tests for OSX

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#153]
We added shell check in https://github.com/coala-analyzer/coala-bears/pull/139 But the testing is only for Linux.

Apparently shellcheck is available in homebrew.
So, this should be pretty simple, where we just need to add the appropriate command in `.ci/deps.osx.sh`

A newcomer with a OSX computer should be able to do this easily

**Comment by manojpandey** [comment]
Adding `brew install shellcheck` should do the job !

**Comment by sepihere** [comment]
I have tried a script to fix the issue.
https://github.com/sepihere/coala-bears/commit/c0e7fea60fafe255838f34782aff10d8c3d07308
I know should run tests. I have tried it on my own Mac which works but I don't know how to run "coala" command with my Fork for extra tests.

**Comment by sils1297** [comment]
Ahm wait a minute - we don't have Mac tests anymore because they were hard to maintain and didn't find us any issues

**Comment by sils1297** [comment]
@sepihere did you see my comment above? I don't think this issue needs fixing. @AbdealiJK can you confirm?

**Comment by sepihere** [comment]
@sils1297
oh sirry.  I thought you meant that I don't need to run additional tests and should do a pull request.

**Comment by sils1297** [comment]
@sepihere sorry we hate it when this happens (people wasting time on wrongly defined issues) but I think we want to close this. If I'm getting something wrong here please reopen with reasoning.
