### ISSUE TITLE
Scaffold a New Bear

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#154]
This is a feature proposal. Currently to make a new linter bear, the user has to manually create files in `bears/`, `tests/` directory and add external modules in `package.json` / `requirements.txt` etc.
A scaffolding tool which would automate the boring task would be nice to have. A basic framework I thought would be : 

```
$ coala-bear new-bear --name xyzLintBear -r 'extern_module'

Welcome! xyzLintBear added.
Bear Name: xyzLintBear
Bear Path: bears/xyzLintBear/
Tests file: tests/xyzLintBear/     
requirements.txt: extern_module
```

Note :  `-r` can be for `requirements.txt` ; `-p` for `package.json` etc...
`bears/xyzLintBear/` and `tests/xyzLintBear/` would have the files needed and we could have a simple template which is common in all linters.

We can integrate https://github.com/audreyr/cookiecutter in this 

I'd like to hear more on this from the mentors and interested to work on this.

**Comment by Makman2** [comment]
very cool idea. We could extend this issue to a general-purpose-assistance tool for such tasks.

Proposal for the message: Supplying local/weblinks to our tutorials for bear-writing.

**Comment by AbdealiJK** [comment]
Nice :)

I think this should come under `coala` repo and part of the bear binary though.

**Comment by sils1297** [comment]
I'd rather make it interactive than ask the use4r to put stuff via parameters in there
i.e. coala-start-bear
and it greets you and asks you things
and generates the class from that

**Comment by Makman2** [comment]
one could do it like `git --interactive / -i` :)

**Comment by Makman2** [comment]
(so supplying an argument meaning you want interactive mode)

**Comment by mr-karan** [comment]
Some progress : 
https://gist.github.com/mr-karan/51d3009d4ef0ccccecbc

![screencast from 03-05-2016 09-06-09 pm](https://cloud.githubusercontent.com/assets/5689132/13548520/418cc818-e318-11e5-8e69-02601cd3fc50.gif)

**Comment by mr-karan** [comment]
Work done :+1:  Please check it out by installing
`pip install coala-bears-create`

https://asciinema.org/a/47916

**Comment by sils1297** [comment]
Hey, I like it. I feel like the texts should be shortened a lot, users won't read this amount of text. Also the commit messages on your PR aren't that good yet.

Looks like a solid start on first sight but will need some heavy code review :)

**Comment by AbdealiJK** [comment]
It does look good ! Where is the repo for the project btw ?
 
- In lines like - "Please enter the description of the bear " add a `:` or so in the end so that it doesnt get confusing to read the description. Also, possibly ask for the description in the next line.
 - In lines like - "Please select regex or correction" simply doing `(regex, correction)` should be enough.

**Comment by mr-karan** [comment]
https://gitlab.com/coala/coala-bear-management/tree/bearcreate - Awaiting to be merged to master. If you can share your gitlab handle I can right away add you to people who can accept and merge in master (Right now i have added only @sils1297)

Thanks for the correction, I'll make the changes soon. I've quickly added a new feature right now
![imgur](http://i.imgur.com/oPXLomB.png)

**Comment by mr-karan** [comment]
I'll cleanup the commits and make the texts short

**Comment by mr-karan** [comment]
Made the changes

https://gitlab.com/coala/coala-bear-management/merge_requests/2

**Comment by Makman2** [comment]
I like the statusbar :D

**Comment by mr-karan** [comment]
Already done https://gitlab.com/coala/coala-bear-management

**Comment by meetmangukiya** [comment]
Any reason why is this not promoted or even highlighted in the docs. Sounds pretty cool to have.

**Comment by SanketDG** [comment]
This needs to be rebooted and maintained. Opening this for further discussion.

**Comment by jayvdb** [comment]
It is mentioned in the `External_Bears.rst` in core api docs.
