### ISSUE TITLE
KeywordBear: lookaheads doesn't work

### ISSUE THREAD

**Issue by Strajk** [coala/coala-bears#1549]
Lookaheads in KeywordBear seems to not work

Repo to replicate https://github.com/Strajk/coala-regex-bug

There are [2 rules](https://github.com/Strajk/coala-regex-bug/blob/master/.coafile)
* First is using lookahead, and coala do not find anything (regex checked via [Regex101](https://regex101.com/r/oWUdiW/1/) )
* Second is simple regex, and coala correctly finds the problem (just for reference)

**Comment by jack17529** [comment]
So according to you regex in coala has bug?

**Comment by Makman2** [comment]
It seems you regex is not correctly formed, I tried it on your example without using a bear, and it doesn't match. But it works if you omit the ending `$` -> `content:?\s\"\\.+\"`
Bears do not use the `re.MULTILINE` flag which allows `$` matching at each end of a line (instead at end of complete string/file).

**Comment by Strajk** [comment]
@jack17529 seems so, or at least it's not working as expected (by me :) )

@Makman2 thanks for willing to help, but [even removing $ doesn't work for me...](https://github.com/Strajk/coala-regex-bug/commit/d8fad5ed6e2878216cdc97d5e1cfdd6896bd8749)

`docker run -ti -v $(pwd):/common --workdir=/common coala/base coala --ci` still finds just `forbid-pink-color-in-styles`

any ideas?

**Comment by Makman2** [comment]
Ah maybe you have to also double escape `\` (as you have to do in python for regexes), because we interpret them too:
```
content:?\\s\\"\\\\.+\\"
```

**Comment by Strajk** [comment]
@Makman2 Looks like ASCII art, but works!!!! 🎉  🎉  🎉

**Comment by Makman2** [comment]
Glad it worked :)
