### ISSUE TITLE
Remove Python 3.4.0 support

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1552]
https://pypi.python.org/pypi/yapf#python-versions says it supports only 3.4.1+.
coala currently supports 3.4.0, but will fail to install because of the dependency on yapf.

Should coala also reject 3.4.0?

**Comment by jayvdb** [comment]
I've confirmed that it works on Python 3.4.1, but [Travis doesnt have 3.4.0](https://travis-ci.org/jayvdb/yapf/jobs/249014379), so cant easily check what is causing that to fail.

**Comment by jayvdb** [comment]
The broken dependency is lib2to3 ; see https://github.com/google/yapf/commit/a7bfe7e093b41a9dd

**Comment by Makman2** [comment]
We shouldn't reject 3.4.0 carelessly. Though 3.4.1 would be fine imo, as it's still the same major version.

My first idea popped into my head was also version management for the python version used to run coala, but I don't like that, that is so super much work and only useful in rare cases.

**Comment by sangamcse** [comment]
I think we have moved on to `3.4.4`. So shouldn't it be closed?

**Comment by jayvdb** [comment]
This is about informing users that coala is not usable with 3.4.0.

**Comment by Makman2** [comment]
I believe I updated all occurrences in our docs mentioning 3.4.0 and replaced it with 3.4.4 or higher. I guess we can close this, if we want to twitter that, we should open a new issue inside our `coala/meta` repo.
