### ISSUE TITLE
Add option of adding whitelist file for vulture in VultureBear

### ISSUE THREAD

**Issue by RJ722** [coala/coala-bears#1564]
How VultureBear currently executes vulture:
`
vulture file1.py file2.py ...    
`   (All the files in that particular directory - Please have a look [here](https://github.com/coala/coala-bears/blob/3cb9b148adc0dda51ac890188b38fd968f6058fd/bears/python/VultureBear.py#L37) )

For whitelisting stuff (functions, classes, variables), we have an option to execute:
```vulture <file.py> <whitelist.py>```
where, <whitelist.py> is the file containing all the *stuff* and it would be easily ignored.

**Comment by RJ722** [comment]
IMHO, we have two options:
* change the way we call vulture individually for  
* whitelist file could be made available as a command line feature.

CC: @jendrikseipp

**Comment by jack17529** [comment]
@RJ722  but this is already solved , there is no need to open the same issue there in vulture repository, and also here and that too already solved in vulture.

According to me this seems useless , Please don't open issues already been solved in some other repositories as this is rude to maintainers .

Please close it.

**Comment by RJ722** [comment]
> @RJ722 but this is already solved , there is no need to open the same issue in vulture repository , and also here and that too already solved in vulture.
According to me this seems useless , Please don't open issues already been solved in some other repositories as this is rude to maintainers .
Please close it. 

@jack17529, I did check the existing issues, I didn't found any!

**Comment by jack17529** [comment]
@RJ722 , you basically don't know how vulture works and you are filing issues and also referencing them :|
I firstly though you are intelligent and you know what you are doing and have already red the code of vulture repo but now you sound very rude.
This issue too does not makes any sense first see how vulture evaluates vulture repository.
I have also pointed out here - https://github.com/jendrikseipp/vulture/issues/32

**Comment by jack17529** [comment]
Are you doing this under pressure of GSOC 2017 @RJ722  
Then please stop this.

**Comment by adtac** [comment]
@jack17529 could you please not be rude to other users? This is hardly the first time you're going out of your way to call others out (in an impolite manner).

**Comment by RJ722** [comment]
> but now you sound very rude.

I'm sorry! Didn't meant so
I just meant to point out that I couldn't find any issue already submitted.

>Are you doing this under pressure of GSOC 2017 @RJ722
Then please stop this.

What is your point?

**Comment by Adrianzatreanu** [comment]
@RJ722 please ignore jack's rude comments. They are not constructive, they are meaning to intimidate you and we do not accept this behaviour.

@jack17529 i would like to ask you to stop harassing other contributors as you are right now, because you have crossed the line.

**Comment by jack17529** [comment]
Sorry but I also once tried this before but it was not constructive so jaydb closed both my issues , because he knew those don't make any sense.

**Comment by jack17529** [comment]
Although , I am sorry to everyone here , but what I told was truth .
If this issue is reported legit , I will make a patch on it and apologies by PM.

**Comment by jack17529** [comment]
This proves that I am right he is opening issues carelessly see this - https://github.com/jendrikseipp/vulture/issues/32

**Comment by sims1253** [comment]
This is not going anywhere nice so I locked the discussion.
@RJ722 This is not directed at you and I am sorry for this to happen. Opening issues, even if they are duplicates or based on a misunderstanding, is never a bad thing. Worst case, someone will point you do the other issue or documentation. Don't feel demotivated by this. Drop by [in our chat](coala.io/chat) if you have any questions or concerns.

Sincerely,
Max

**Comment by jayvdb** [comment]
So, to get back on topic, this is because VultureBear is a GlobalBear.

That is intentional, as vulture needs all filenames otherwise vulture doesnt work properly.

So, we need a better way of informing vulture of the whitelist. e.g. `--whitelist foo.py`. So this is an upstream problem at the moment. It is still a valid issue in this repo, as we need to track the upstream problems.

**Comment by jayvdb** [comment]
Given the undesirable discussion that occurred on this issue, I am closing it.  Create a new issue (and mention this one) if there is still a bug to be solved.
