### ISSUE TITLE
QuotesBear : Change CAN_DETECT to CAN_FIX

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-bears#1571]
`CAN_DETECT = {'Formatting'}` to `CAN_FIX = {'Formatting'}` as the bear "Checks and corrects the quotation style."

difficulty/newcomer

**Comment by Jakod96** [comment]
Can i please get assigned?

**Comment by satwikkansal** [comment]
@Jakod96 I don't have the rights please ask on our gitter channel, someone will definitely assign you :)

**Comment by palash25** [comment]
I think this PR has been abandoned. I would like to be assigned. I can probably send a PR today.

**Comment by jayvdb** [comment]
This is a newcomer issue @palash25 , as the change required is already given .  Find more challenging tasks.

**Comment by shashank-b** [comment]
I want to work on this issue.
