### ISSUE TITLE
deps.cabal.sh: Circle CI build failing 

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-bears#1572]
See  https://circleci.com/gh/satwikkansal/coala-bears/26?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

PR for which the build is failing : https://github.com/coala/coala-bears/pull/1297

Failure report
```
Failing command: bash .ci/deps.cabal.sh
Exit code: 1
Output:

cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
Downloading the latest package list from hackage.haskell.org
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: coala-bears-0.10 (user goal)
next goal: hlint (dependency of coala-bears-0.10)
rejecting: hlint-1.9.27/installed-3qm... (conflict: hlint =>
cmdargs==0.10.16/installed-K4I..., coala-bears => cmdargs==0.10.14)
rejecting: hlint-1.9.41, hlint-1.9.40, hlint-1.9.39, hlint-1.9.38,
hlint-1.9.37, hlint-1.9.36, hlint-1.9.35, hlint-1.9.34, hlint-1.9.33,
hlint-1.9.32, hlint-1.9.31, hlint-1.9.30, hlint-1.9.29, hlint-1.9.28
(conflict: coala-bears => hlint==1.9.27)
rejecting: hlint-1.9.27 (avoiding to reinstall a package with same version but
new dependencies)
rejecting: hlint-1.9.26, hlint-1.9.25, hlint-1.9.24, hlint-1.9.23,
hlint-1.9.22, hlint-1.9.21, hlint-1.9.20, hlint-1.9.19, hlint-1.9.18,
hlint-1.9.17, hlint-1.9.16, hlint-1.9.15, hlint-1.9.14, hlint-1.9.13,
hlint-1.9.12, hlint-1.9.11, hlint-1.9.10, hlint-1.9.9, hlint-1.9.8,
hlint-1.9.7, hlint-1.9.6, hlint-1.9.5, hlint-1.9.4, hlint-1.9.3, hlint-1.9.2,
hlint-1.9.1, hlint-1.9, hlint-1.8.61, hlint-1.8.60, hlint-1.8.59,
hlint-1.8.58, hlint-1.8.57, hlint-1.8.56, hlint-1.8.55, hlint-1.8.54,
hlint-1.8.53, hlint-1.8.52, hlint-1.8.51, hlint-1.8.50, hlint-1.8.49,
hlint-1.8.48, hlint-1.8.47, hlint-1.8.46, hlint-1.8.45, hlint-1.8.44,
hlint-1.8.43, hlint-1.8.42, hlint-1.8.41, hlint-1.8.40, hlint-1.8.39,
hlint-1.8.37, hlint-1.8.36, hlint-1.8.35, hlint-1.8.34, hlint-1.8.33,
hlint-1.8.32, hlint-1.8.31, hlint-1.8.30, hlint-1.8.29, hlint-1.8.28,
hlint-1.8.27, hlint-1.8.26, hlint-1.8.25, hlint-1.8.24, hlint-1.8.23,
hlint-1.8.22, hlint-1.8.21, hlint-1.8.20, hlint-1.8.19, hlint-1.8.18,
hlint-1.8.17, hlint-1.8.16, hlint-1.8.15, hlint-1.8.14, hlint-1.8.13,
hlint-1.8.12, hlint-1.8.11, hlint-1.8.10, hlint-1.8.9, hlint-1.8.8,
hlint-1.8.7, hlint-1.8.6, hlint-1.8.5, hlint-1.8.4, hlint-1.8.3, hlint-1.8.2,
hlint-1.8.1, hlint-1.8, hlint-1.7.3, hlint-1.7.2, hlint-1.7.1, hlint-1.7,
hlint-1.6.21, hlint-1.6.20, hlint-1.6.19, hlint-1.6.18, hlint-1.6.17,
hlint-1.6.16, hlint-1.6.15, hlint-1.6.14, hlint-1.6.13, hlint-1.6.12,
hlint-1.6.11, hlint-1.6.10, hlint-1.6.9, hlint-1.6.8, hlint-1.6.7,
hlint-1.6.6, hlint-1.6.5, hlint-1.6.4, hlint-1.6.3, hlint-1.6.2, hlint-1.6.1,
hlint-1.6, hlint-1.4, hlint-1.2, hlint-1.0.0.1, hlint-1.0.0.0 (conflict:
coala-bears => hlint==1.9.27)
Dependency tree exhaustively searched.

bash .ci/deps.cabal.sh returned exit code 1

Action failed: bash .ci/deps.cabal.sh
```

**Comment by jayvdb** [comment]
If I understand correctly, the main repo CI [passed on Circle CI](https://circleci.com/gh/coala/coala-bears/5948), and passes on Travis CI, so either it is

- a caching problem, which the main repo will also encounter when its cache is lost, or
- because you have your containers set to be 14.04 (trusty), whereas the main repo circle CI uses 12.04 (precise).  That isnt to say this bug isnt a real problem.  I have tried to keep the Circle CI trusty image working also, but without it running in our standard CI builds, we dont notice when it fails.
- something else... ;-)

I set up a build using 12.04, and [the error](https://circleci.com/gh/jayvdb/coala-bears/655) I got was
```
cabal: Error: some packages failed to install:
ShellCheck-0.4.1 failed during the building phase. The exception was:
ExitFailure 9
This may be due to an out-of-memory condition.
```

Restarting that Circle CI build - maybe that was a one-off problem.

**Comment by jayvdb** [comment]
The [next build](https://circleci.com/gh/jayvdb/coala-bears/656) failed with a timeout.  Trying again..

**Comment by satwikkansal** [comment]
Setting the container image to 12.04 (precise) worked for my PR.
 https://circleci.com/gh/satwikkansal/coala-bears/29

**Comment by jayvdb** [comment]
Ok, my next 12.04 build passed.  And Travis passes, so I think we can assume that this is a 14.04 problem.  I'm doing a 14.04 build of master [now](https://circleci.com/gh/jayvdb/coala-bears/658), which should fail with the same problem you encountered.

**Comment by jayvdb** [comment]
Interesting, my 14.04 Circle build also passes.

**Comment by satwikkansal** [comment]
I re-triggered the build [now](https://circleci.com/gh/satwikkansal/coala-bears/32) on 14.04 without cache. Let's see what happens

**Comment by satwikkansal** [comment]
Phew.. It's successful. Wonder why it wasn't successful the previous time I tried to rebuild without cache. I think this issue is resolved now :) Thanks for the help.  
Maybe it's better to document this in the guides somewhere so that others can benefit from it when similar problem occurs.

**Comment by yash-nisar** [comment]
So, can this be closed now @satwikkansal ?

**Comment by satwikkansal** [comment]
@yash-nisar Okay. My build is now successful, and no issues occur with any of the 12.04 or 14.04 image, so closing this issue. Thanks @jayvdb for helping.
