### ISSUE TITLE
Circle CI failure for sphinx 1.4.9

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1575]
```
Warning, treated as error:
/home/ubuntu/coala-bears/docs/API/bears.c_languages.rst:57: WARNING: error while formatting arguments for bears.c_languages.ClangBear.ClangBear.run: Optional[t] requires a single type. Got <function typed_list.<locals>.<lambda> at 0x2b3af041c1e0>.

make: *** [html] Error 1
make: Leaving directory `/home/ubuntu/coala-bears/docs'

python setup.py docs returned exit code 2
```

See https://circleci.com/gh/yash-nisar/coala-bears/19 for more info.
type/bug

**Comment by jayvdb** [comment]
> Optional[t] requires a single type 

That looks a little strange!  why `t`?

If it isnt happening on Travis, my guess is that the cause is there are different versions of `coala` installed, and the recently added `@wraps` for https://github.com/coala/coala/issues/3946 is the cause.

**Comment by jayvdb** [comment]
In [this Travis build](https://travis-ci.org/coala/coala-bears/jobs/218470349), `coala-0.11.0.dev20170404120542` is installed, which is of course after https://github.com/coala/coala/commit/017bcfc2195f was merged with `@wraps.

**Comment by yash-nisar** [comment]
I've tested for the same version `coala-0.11.0.dev20170404120542` for [this circleci build](https://circleci.com/gh/yash-nisar/coala-bears/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but still no success. @jayvdb

**Comment by jayvdb** [comment]
Note using Circle trusty by default is https://github.com/coala/coala-bears/issues/869

**Comment by yash-nisar** [comment]
Didn't get you @jayvdb ?

**Comment by yash-nisar** [comment]
Closing, since this seems to be resolved in https://github.com/coala/coala-bears/pull/1819/commits/c9be1bfc84542b92c640b57050f98a2270199ed8
