### ISSUE TITLE
Bear proposal: TextlintBear

### ISSUE THREAD

**Issue by satwikkansal** [coala/coala-bears#1576]
[textlint](https://github.com/textlint/textlint) is a linting tool for text and markdown. 

Also, see this nice discussion for “Interactive fix” functionality in textlint which might be related to https://github.com/coala/coala/issues/1021.

**Comment by jayvdb** [comment]
This linter has extra language support with plugins

* HTML: textlint-plugin-html
* reStructuredText: textlint-plugin-rst
* AsciiDoc/Asciidoctor: textlint-plugin-asciidoc-loose
* Re:VIEW: textlint-plugin-review

That would make this very cool, especially the reStructuredText and AsciiDoc(tor) support!
