### ISSUE TITLE
PyUnusedCodeBear: Implement remove_unused_variables

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#1584]
The remove_unused_variables is implicitly passed on:
https://github.com/coala/coala-bears/blob/master/bears/python/PyUnusedCodeBear.py#L33

should be implemented as a setting in `run()`

**Comment by shreab373** [comment]
Hello! i'm a newbie, could help me out a little in solving this? :)

**Comment by adhikasp** [comment]
Hi @shreab373 
Basically you should modify PyUnusedCodeBear to take additional setting named `remove_unused_variables` from coafile. If you need an example, the variable `remove_all_unused_imports` value is already taken from setting (hint, see the `run()` arguments).

**Comment by shreab373** [comment]
@adhikasp thanks for helping!

could you also explain this syntax https://github.com/coala/coala-bears/blob/master/bears/python/PyUnusedCodeBear.py#L18  ??

**Comment by SanketDG** [comment]
@shreab373 Its just a parameter to a function that's annotated as boolean and default value is set to `False`

you have to create another parameter of the given name with the same annotations and default values :)
