### ISSUE TITLE
`Ctrl+Z` command to terminate the program not working in Windows

### ISSUE THREAD

**Issue by Techievena** [coala/coala-bears#1612]
![image](https://cloud.githubusercontent.com/assets/17270966/25078818/50f8f164-2354-11e7-8abc-245bb6cafbeb.png)

coala must terminate after pressing `Ctrl+Z` keys as shown in the CLI.

**Comment by meetmangukiya** [comment]
Ctrl+C doesn't work?

**Comment by Techievena** [comment]
Yup it works. But the way `Ctrl+D` can be used to terminate the analysis in Ubuntu, it is mentioned in `Windows` to press `Ctrl+Z` to exit, but it doesn't works. 😃

**Comment by jayvdb** [comment]
issue in wrong repo?
I think I've seen this raised in the coala repo.

**Comment by satwikkansal** [comment]
Maybe reopen https://github.com/coala/coala/issues/3410 ?

**Comment by Makman2** [comment]
You need to press enter after CTRL+Z. Though because of this enter-pressing some programs do not handle that correctly.

**Comment by Techievena** [comment]
@Makman2 but this isn't mentioned anywhere. Can we show a warning message if coala doesn't terminate after Ctrl+Z?

**Comment by Makman2** [comment]
phew... I'm not sure we will be able to catch that easily. Maybe we should say "CTRL+Z + Enter" instead of "CTRL+Z" only^^

@Techievena have you tested whether CTRL+Z + Enter works? If not Windows just doesn't support the same EOL-exiting like linux does then^^

**Comment by Techievena** [comment]
Yup @Makman2 I have tested `Ctrl+Z+Enter` works fine

**Comment by Makman2** [comment]
so we have to change `CTRL-Z` to `CTRL-Z + ENTER` or `CTRL-Z and ENTER` ;)

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala/issues/5254
