### ISSUE TITLE
JuliaLintBear: Use JuliaRequirement

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1613]
`REQUIREMENTS` should be a `JuliaRequirement` instead of a `DistributionRequirement`.

**Comment by prakashdanish** [comment]
[this](https://github.com/coala/coala-bears/blob/master/bears/julia/JuliaLintBear.py#L28) needs to be changed, right?

**Comment by jayvdb** [comment]
@prakashdanish , correct.

**Comment by jayvdb** [comment]
It should add a requirement on the Julia package called 'Lint'
