### ISSUE TITLE
JSHintBear: Remove jshint_config from generate_config

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1615]
Remove `jshint_config` from `generate_config` and remove redundant if condition
area/lintbears

**Comment by Makman2** [comment]
Why do you want to remove that? It's an override to allow users to provide their already existing config file^^

**Comment by yash-nisar** [comment]
IIUC, users can still provide their already existing config file via `coala -b JSHintBear -S jshint_config=config_file -f xyz.js`. because it is present in `create_arguments()`. I feel we should remove it from `def generate_config(...jshint_config: str='')` because it will always be an empty string inside the function and similarly `if not jshint_config:` will always be true. Is it okay ?

**Comment by yash-nisar** [comment]
Is it okay if I ping you here or should I do it on gitter ?

**Comment by Makman2** [comment]
> Is it okay if I ping you here or should I do it on gitter ?

That's okay, I'm already involved into discussion ;)

If you remove the if-condition, coala will always generate a file. This is really a performance impact, as we create quite a large dict, convert it to json and save it back. And that for every file analyzed. If a user doesn't pass a `jshint_config`, we don't need to create the config file.

**Comment by yash-nisar** [comment]
You're absolutely correct @Makman2 . I misunderstood a few things. On testing it manually and diving deeper, I found out that the settings that we provide via the command line arguments override the `generate_config(...) settings` and the corresponding `config_file` is generated. So `generate_config` knows that we've provided the jshint_config file in the settings. I went through all the bears with the `generate_config(...)` function and saw mostly none of them have the ^^above configuration for performance enhancement and some of them don't have support for user defined config files. So this is definitely an area where we can improve our bears. Thanks a lot again. :smile:

**Comment by yash-nisar** [comment]
I think I should open a new issue for https://github.com/coala/coala-bears/blob/master/bears/ruby/RuboCopBear.py, by defining a similar `if` condition that checks for the `config_file` if present.

**Comment by jayvdb** [comment]
Re RuboCop, I recently created https://github.com/coala/coala/issues/4072 about the `_config` settings, and moving them into core, and adding features to them.

**Comment by yash-nisar** [comment]
Till https://github.com/coala/coala/issues/4072 is done, can we do https://github.com/coala/coala-bears/issues/1615#issuecomment-294663153 ? @jayvdb

**Comment by Makman2** [comment]
Actually I've searched for this in documentation for linter and in the guides, and nowhere is mentioned that returning `None` inside `generate_config` omits the config file. We should mention this performance possibility^^

Filed https://github.com/coala/coala/issues/4119 for that.
