### ISSUE TITLE
GitCommitBear: Download ntlk data automatically

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1617]
GitCommitBear does not check that the nltk data has been fetched.
It has an exception, and a helpful error message (without coverage - see https://github.com/coala/coala-bears/issues/1618), but that would mean any chance to the data required is a breaking change.

**Comment by RohanVB** [comment]
@jayvdb that means after merge, [this](https://circleci.com/gh/coala/coala-atom/109?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) will pass and I won't have to add the script to download NLTK data in .yml in that repo?

**Comment by jayvdb** [comment]
Yes!
