### ISSUE TITLE
Allow max_line_length value for unlimited line length

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1620]
Many bears set a default for `max_line_length`, and it is difficult to unset it (https://github.com/coala/coala/issues/4116).  It is common for a value of `0` to mean unlimited, where `0` has no logical meaning, such as this setting.

The bears that support `max_line_length` are:

* c_languages/CPPLintBear.py
* c_languages/GNUIndentBear.py
* coffee_script/CoffeeLintBear.py
* general/LineLengthBear.py
* markdown/MarkdownBear.py
* php/PHPCodeSnifferBear.py
* python/PEP8Bear.py
* python/PEP8NotebookBear.py
* python/PyImportSortBear.py
* python/PycodestyleBear.py
* python/YapfBear.py
* ruby/RuboCopBear.py
* swift/TailorBear.py

Current tests that mention `max_line_length`:

* c_languages/CPPLintBearTest.py
* c_languages/GNUIndentBearTest.py
* general/LineLengthBearTest.py
* markdown/MarkdownBearTest.py
* python/PEP8BearTest.py
* python/PycodestyleBearTest.py

This change should affect all of those bears, and have a common/similar test for each of them.

**Comment by yash-nisar** [comment]
So when we specify 0 as a default for `max_line_length`, the bear shouldn't complain and should allow unlimited length of a line @jayvdb ?

**Comment by jayvdb** [comment]
Changing the defaults would be a breaking change.  However when the user specifies `0`, it should give unlimited line length.  This is important for bears other than `LineLengthBear` which have lots of other good features and the user may not line length checking.

**Comment by Asnelchristian** [comment]
how about  we set `max_line_length` to.... maybe `999` when the user enters `0` (given that the tool used by the bear itself has a default value for it(it always checks on the line length))

**Comment by jayvdb** [comment]
oh, I have seen lines with much longer than 999 chars on them.  But I guess that concept could work using a much higher value.

**Comment by newbazz** [comment]
I would like to give a try on this issue.

**Comment by Makman2** [comment]
Unassigned due to inactivity.
