### ISSUE TITLE
LanguageToolBear.py: Use triple double quoted docstrings

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1627]
https://github.com/coala/coala-bears/blob/master/bears/natural_language/LanguageToolBear.py#L42
difficulty/newcomer

**Comment by jayvdb** [comment]
Note that @nikskushwah is doing this issue in https://github.com/coala/coala-bears/pull/1631

**Comment by ASVS-Kartheek** [comment]
I want to be assigned to this, Please guide me

**Comment by sanketnavin** [comment]
This issues seems stale. Can I get assigned to this issue?

**Comment by Makman2** [comment]
Reassigned due to inactivity.

**Comment by Makman2** [comment]
Due to documentation reasons, unassigning, but this issue is still not available.

**Comment by ksangam68** [comment]
Please assign me the issue 😄

**Comment by ksangam68** [comment]
Please assign me this issue 😄

**Comment by Makman2** [comment]
☝️ https://github.com/coala/coala-bears/issues/1627#issuecomment-366244396

> Due to documentation reasons, unassigning, but this issue is still not available.
