### ISSUE TITLE
Add ComposerRequirement

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1657]
PHPCodeSnifferBear and PHPMessDetectorBear should use ComposerRequirement

**Comment by jayvdb** [comment]
Also, you may as well also do https://github.com/coala/coala-bears/issues/1659 for these two bears.

**Comment by jayvdb** [comment]
And if this includes CI to actually test composer, then https://github.com/coala/coala-bears/issues/293 is also fixed.

**Comment by yash-nisar** [comment]
@damngamerz The release is within a few hours so can you initiate a PR asap ?

**Comment by jayvdb** [comment]
Note that openSUSE (zypper) has a package for PHPCodeSnifferBear: [php-pear-php_codesniffer](https://software.opensuse.org/package/php-pear-php_codesniffer)

**Comment by damngamerz** [comment]
Im guessing i have to use AnyOneOfRequirements. Making a PR 
CC @jayvdb @yash-nisar

**Comment by yash-nisar** [comment]
Yes, IIUC add `ComposerRequirement` and then wrap both of them in `AnyOne..`
