### ISSUE TITLE
DartLintBear: Add DistributionRequirement for brew package

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1664]
brew package manager has 'dart', in repo 'dart-lang/dart'.
I cant see any other package managers that provide dart.

The commit needs to be similar to https://github.com/coala/coala-bears/commit/c2b338bbe3862cbcd8e0ddcc793d33f9ae308a9b , but using `brew=dart`

**Comment by vrishank97** [comment]
@SacredWKnight If you aren't working on this, can I pick up this issue?

**Comment by Makman2** [comment]
Reassigned due to inactivity.
