### ISSUE TITLE
TailorBear: Add DistributionRequirement for brew package

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1666]
brew package manager has ['tailor'](https://github.com/sleekbyte/tailor#homebrew-linuxbrew)

The commit needs to be similar to https://github.com/coala/coala-bears/commit/c2b338bbe3862cbcd8e0ddcc793d33f9ae308a9b , but using `brew=tailor`

**Comment by yash-nisar** [comment]
@SacredWKnight The release is within a few hours so can you initiate a PR asap ?

**Comment by jayvdb** [comment]
The two commits above are correct, but need to be submitted as a single commit.
