### ISSUE TITLE
Make check_validity() test method more robust and correct the tests

### ISSUE THREAD

**Issue by Techievena** [coala/coala-bears#1694]
- [ ] PyLintBearTest.py
- [ ] PHPLintBearTest.py
- [ ] CheckstyleBearTest.py
- [ ] StyleLintBearTest.py
- [ ] DennisBearTest.py

have the wrong usage of `check_validity()` and are performing tests on empty files. Do correction in these tests and make `check_validity()` more robust not to allow any empty files further in the future.

**Comment by Makman2** [comment]
Why closed?

**Comment by Techievena** [comment]
@Makman2 Actually the issue is with `verify_local_bear()` and the docstring made me think the issue is with `check_validity()`. To be more exact, this is mentioned in the docstring of `check_validity()`:
```
:param filename:         The filename, if it matters.
```
whereas it should be more like `The file to be checked`.
and also in case of `verify_local_bear()` it should be `invalid_filename` and `valid_filename` instead of passing a single filename for `valid_file` and `invalid_file` case.

**Comment by Techievena** [comment]
In these cases the `param lines` but they are performing checks on the `param filename`

**Comment by Makman2** [comment]
So does the issue still exist with `verify_local_bear()`?

**Comment by Techievena** [comment]
Yes

**Comment by Makman2** [comment]
Wanna reopen this issue and change the title?

**Comment by jayvdb** [comment]
The filename is irrelevant.  It is optional.

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/coala-bears/pull/1438#pullrequestreview-36020495
