### ISSUE TITLE
Use with to load the file

### ISSUE THREAD

**Issue by shreyans800755** [coala/coala-bears#1704]
In https://github.com/coala/coala-bears/blob/master/tests/general/LicenseCheckBearTest.py#L18,
file is opened without using `with` statement. It doesn't ensure the closing of file.

**Comment by shreyans800755** [comment]
CC @jayvdb @sils 
Difficulty/newcomer should be enough.

**Comment by ragvri** [comment]
Can I take this please.

**Comment by Makman2** [comment]
@ragvri please checkout http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by Makman2** [comment]
Just a technical perspective on this:
CPython supports finalization hooks that are triggered when the reference count drops to zero. For many built-in classes this frees resources appropriately, and in this case too (as soon as `readline()` finishes, the file object is not used any longer and destroyed). But this is not an official Python feature, so it's definitely better to use a `with` stmt :+1:

**Comment by captaincrunch21** [comment]
Hi @Makman2 I want to take grab this

**Comment by Makman2** [comment]
☝️  https://github.com/coala/coala-bears/issues/1704#issuecomment-299288063

**Comment by captaincrunch21** [comment]
I submitted a pull request could you please verify it

**Comment by shreyans800755** [comment]
@captaincrunch21 Can you please assign this issue for reference to yourself ?
Use `cobot assign https://github.com/coala/coala-bears/issues/1704` in gitter.

**Comment by jayvdb** [comment]
@ragvri , @captaincrunch21 , you have both submitted pull requests without following the http://coala.io/newcomer process.  You need to follow the newcomer process to be assigned to this issue.
