### ISSUE TITLE
RSTcheckBear: Allow ignoring roles and directives

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1723]
rstcheck has [cmdline args](https://github.com/myint/rstcheck#options) for ignoring directives and ignoring roles.

These need to be exposed via bear settings.  This is blocking a proper fix for https://github.com/coala/coala/pull/4211#issuecomment-301042935

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/coala-bears/pull/1718 for a similar enhancement

**Comment by mridubhatnagar** [comment]
Instead of adding RSTcheckBear here. I can fix this issues in #4211 itself.

**Comment by jayvdb** [comment]
> Instead of adding RSTcheckBear here. I can fix this issues in #4211 itself.

No.  This is an enhancement for RSTcheckBear.

**Comment by mridubhatnagar** [comment]
Ohk so nothing has to be done with .coafile. I will have to go through RSTcheckBear.

**Comment by mridubhatnagar** [comment]
I understood what needs to be done. But for checking if everything works fine. I will have to add rstcheckBear to the .coafile of coala-bears repository.
rstcheckBear is not present in .coafile of coala-bears.

**Comment by jayvdb** [comment]
To test your changes, you need to add tests to `tests/rest/RSTcheckBearTest.py`, and not modify `.coafile`.

**Comment by mridubhatnagar** [comment]
Missing coverage 9-15.

**Comment by mridubhatnagar** [comment]
Can someone please help me with this. I am unable to get 100% code coverage. And not sure if changes are right or not.

**Comment by Makman2** [comment]
@mridubhatnagar it seems you are not working on the issue any more, and @umeshksingla said he has an urgent need for this feature. If you don't mind he would take this issue over :)

@umeshksingla please accept the invitation, then I'll assign the issue to you :)
PS: Hop onto our gitter channel, so you get various help: https://gitter.im/coala/coala
