### ISSUE TITLE
Use check_invalidity

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1729]
https://github.com/coala/coala/issues/2197 introduced check_invalidity in https://github.com/coala/coala/pull/4167 .

All use of `check_validity(.., valid=False)` should be replaced with `check_invalidity(..)`.

The most obvious are

```
$ git grep -l check_validity.*valid=False
tests/c_languages/CSharpLintBearTest.py
tests/css/StyleLintBearTest.py
tests/general/FilenameBearTest.py
tests/general/SpaceConsistencyBearTest.py
tests/gettext/DennisBearTest.py
tests/go/GoVetBearTest.py
tests/java/CheckstyleBearTest.py
tests/python/MypyBearTest.py
tests/python/PEP8BearTest.py
tests/python/PyCommentedCodeBearTest.py
tests/python/PyLintBearTest.py
tests/python/requirements/PySafetyBearTest.py
```

But that grep doesnt catch them all.

**Comment by AlexGascon** [comment]
Hi! If no one is working on it, I'd like to give it a try

**Comment by Makman2** [comment]
Hey :) Please read the newcomer guide on how to get invited and assign yourself to an issue -->
http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by prachi1210** [comment]
Hi, I'd like to work on this issue

**Comment by yash-nisar** [comment]
Hey @prachi1210, what is it that you would like to know ?

**Comment by yash-nisar** [comment]
We need this to be done a high priority basis because it is holding https://github.com/coala/coala/issues/2197

**Comment by prachi1210** [comment]
Hey can you please review my PR?https://github.com/coala/coala-bears/pull/1833

**Comment by yash-nisar** [comment]
I've requested changes, see https://github.com/coala/coala-bears/pull/1833#pullrequestreview-44754158

**Comment by prachi1210** [comment]
@yash-nisar done

**Comment by yash-nisar** [comment]
Perfect :+1:

**Comment by yash-nisar** [comment]
@jayvdb had mentioned that : 
> But that grep doesnt catch them all.

Seems that you have missed some of the files where I can still see the usage of `check_validity(..,valid=False)`. To make things easier for you, here is a list of bear tests that need changes : 

- tests/apertium/ApertiumLintBearTest.py
- tests/c_languages/CSharpLintBearTest.py
- tests/css/StyleLintBearTest.py
- tests/general/FilenameBearTest.py
- tests/general/SpaceConsistencyBearTest.py
- tests/gettext/DennisBearTest.py
- tests/go/GoVetBearTest.py
- tests/haskell/GhcModBearTest.py
- tests/haskell/HaskellLintBearTest.py
- tests/java/CheckstyleBearTest.py
- tests/php/PHPLintBearTest.py
- tests/python/MypyBearTest.py
- tests/python/PEP8BearTest.py
- tests/python/PyCommentedCodeBearTest.py
- tests/python/PyLintBearTest.py
- tests/python/YapfBearTest.py
- tests/python/requirements/PySafetyBearTest.py

CC @prachi1210

**Comment by prachi1210** [comment]
Updated the PR to reflect these
