### ISSUE TITLE
tests: Remove check_validity(..., valid=True)

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1730]
In calls to `LocalBearTestHelper.check_validity`,  `valid` defaults to `True`, so it is unnecessary to include it, and should be removed per https://github.com/coala/coala/issues/2197.

The following lists all modules that use `valid=True`

```
$ git grep -l 'valid=True'
tests/haskell/GhcModBearTest.py
tests/haskell/HaskellLintBearTest.py
tests/python/MypyBearTest.py
tests/python/YapfBearTest.py
```

c.f. https://github.com/coala/coala-bears/issues/1729

**Comment by yash-nisar** [comment]
Still on it @shravandoda ? This is a high priority issue so we need this to be done asap.

**Comment by yash-nisar** [comment]
This can be closed since everything has been fixed in https://github.com/coala/coala-bears/pull/1833.

CC @jayvdb

**Comment by yash-nisar** [comment]
I'm taking this up because this issue is not being worked upon and it is holding my GSoC project :smile:

**Comment by meetmangukiya** [comment]
Assigned @yash-nisar :+1:

**Comment by gurpreetsingh00885** [comment]
Do I need to make separate commits for each one of the 4 files I need to make changes in?

**Comment by Makman2** [comment]
@gurpreetsingh00885 you can, but you don't have to. In this case both is fine imo :)
As you've already split up into several commits, you can keep it :)
