### ISSUE TITLE
Use Test in test class module names

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1733]
The following use `verify_local_bear` to create a test class, but then do not use the word Test in the stored class name, which is confusing by itself as the name should describe what it does.

- TailorBearTest.py
  - `TailorBearWithoutConfig = verify_local_bear(TailorBear, ...)`
  - `TailorBearWithConfig = verify_local_bear(TailorBear, ...)`
  - `TailorBearWithSetting = verify_local_bear(TailorBear, ...)`
- TSLintBearTest.py
  - `TSLintBearWithoutConfig = verify_local_bear(TSLintBear, ...)`
  - `TSLintBearOtherOptions = verify_local_bear(TSLintBear, ...)`

Add `Test` to those variable name, like is done in most other test modules that use `verify_local_bear`.

**Comment by jayvdb** [comment]
Note https://github.com/coala/coala-bears/issues/1732 is a similar problem, but it is a far worse syntax and more critical problem.

**Comment by akohli96** [comment]
@jayvdb can I be assigned this?

**Comment by jayvdb** [comment]
Sure.  You'll need to join the coala org first, then I can assign it to you.

**Comment by akohli96** [comment]
I have joined the gitter chat and requested it to be assigned to me.

**Comment by akohli96** [comment]
Does ````python
Test
````

also have to be added to [TSLintBearTest](https://github.com/coala/coala-bears/blob/f451712286a700914a2fee45fcd5cfd048abd099/tests/typescript/TSLintBearTest.py)
````python

TSLintBearOtherOptions = verify_local_bear(TSLintBear,
                                           valid_files=(good_file,),
                                           invalid_files=(bad_file,),
                                           settings={'rules_dir': '/'},
                                           tempfile_kwargs={'suffix': '.ts'})

````

**Comment by akohli96** [comment]
Within ```` TSLintBearTest.py````

there is ```` TSLintBearTestWithConfig````.

Should I rename it to ````TSLintBearWithConfigTest````

**Comment by mridubhatnagar** [comment]
@akohli96 hey, if you are done with the changes. Then you must raise a PR. For your changes to get reviewed by the community.

**Comment by e-aakash** [comment]
I want to work on this issue.
Please assign this to me.
