### ISSUE TITLE
Error if use_spaces = True for HappinessLintBear 

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1754]
https://github.com/JedWatson/happiness/ requires tabs for indentation.
Thus it is configuration error if `use_spaces` is enabled **in the same section**.  If there are other bears **in the same section** using `use_spaces = True`, then they will conflict with HappinessLintBear, and it will be hard to understand why unless someone looks at the documentation of Happiness.

If `use_spaces` is inherited, it is also a bit confusing, but the default for other sections may be `use_spaces`, for other files, and the `HappinessLintBear` section is blissfully ignoring that.  It would be a regression to error in this circumstance, but it would be wise to emit a info message recommending that `use_spaces = False` is added to the section, so it is explicit that the default is being ignored.

**Comment by jayvdb** [comment]
See https://github.com/coala/coala-bears/issues/897 and https://github.com/coala/coala-bears/issues/897 for similar issues that have been fixed.

**Comment by naman1901** [comment]
So, you want that if `HappinessLintBear` is running, a message is printed to the terminal, advising the user to set `use_spaces = false`. Is that correct?

**Comment by jayvdb** [comment]
Only if `use_spaces` is set to true, there should be an error.
See #897 and #897 for similar issues that have been fixed.  They have merged pull requests which do almost exactly what is required.

**Comment by naman1901** [comment]
Been trying to run HappinessLintBearTest. Any idea why it fails even in the version I pulled from git, without making any changes
I had it passing from one directory in windows
fails from another directory and in Ubuntu
I made copies in different directories

`E           AssertionError: 0 == 0 : The local bear 'HappinessLintBear' yields no result although it should. 
E           Running bear HappinessLintBear...
E           Running 'happiness /tmp/tmpeh4ox853'`

^ Part of log

**Comment by naman1901** [comment]
The new test I added works fine. Just one of the old ones that fails. Should I create a PR?

**Comment by naman1901** [comment]
Identified the source of trouble as the `invalid_files` referred to in
`HappinessLintBearTest = verify_local_bear(HappinessLintBear,
                                          valid_files=(good_file,),
                                          invalid_files=(bad_file,))`
I guess that is supposed to happen, as the invalid file would cause an error, right?

**Comment by sils** [comment]
I hereby disagree that we should care about the setting being inherited or not.

If we do this distinction we're breaking our own rules by basically ignoring settings and giving them a weaker meaning if they're inherited. There's no such thing as a setting with a weaker meaning and introducing this concept would be harmful IMO, take this example:

```
[all]
use_spaces = True
[all.happy]
bears = SpaceConsistencyBear, HappinessLintBear
```

The natural expectation is indeed that both bears have the same behaviour for use_spaces. One of them now requiring tabs is very confusing.

**Comment by newbazz** [comment]
I would like to work on this issue if no ones working.

**Comment by Makman2** [comment]
Unassigning due to inactivity.
