### ISSUE TITLE
Objective C linter

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala-bears#176]
i found this linter: http://oclint.org/
seems it works, ive tested it on my machine: i suggest downloading the archive
and exporting the /bin/ manually; the `make` takes too long

**Comment by Adrianzatreanu** [comment]
seems this is how you run a c++ file for example `` $ oclint sample.cpp -- -c``

**Comment by Nosferatul** [comment]
I wanna try!

**Comment by Adrianzatreanu** [comment]
@Nosferatul you still working on this?

**Comment by Nosferatul** [comment]
Still working, I have some problems with dependencies.

**Comment by Adrianzatreanu** [comment]
hey, need some help? it's been some time, message us on gitter if you need help, we're happy to help you

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity.

**Comment by khanchi97** [comment]
Hey, I think this issue is same as this one https://github.com/coala/coala-bears/issues/1953

**Comment by Makman2** [comment]
Closing this one as the duplicate is more active and worked upon.
