### ISSUE TITLE
GitCommitBear downloads nltk_data even if not required

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala-bears#1760]
Since 0.11 we have incorporated downloading of nltk data into GitCommitBear.

We do check if the imperative check is needed:

```Python
    def setup_dependencies(self):
        if not self._nltk_data_downloaded and bool(
                self.section.get('shortlog_check_imperative', True)):
            print(self.section)
            nltk.download([
                'punkt',
                'maxent_treebank_pos_tagger',
                'averaged_perceptron_tagger',
            ])
            type(self)._nltk_data_downloaded = True
```
But `shortlog_check_imperative` is not the name of the settings. It's `shortlog_imperative_check`

To add insult to injury: I was the one who reviewed this.

**Comment by meetmangukiya** [comment]
Bump: This actually breaks `coala --json`, try running `coala --json` and see this popping. No problem with it occuring, but it actually prints to stdout. So reading the json doesn't work, since the parser throws an error then!

**Comment by meetmangukiya** [comment]
Nevermind, I think I was using it wrong way, one can use `
coala --json --log-json` to get the logs in json as well

**Comment by Makman2** [comment]
Dynamic dependency handling might be improved by https://github.com/coala/coala/issues/4436
