### ISSUE TITLE
InvalidLinkBear: False results on working links

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-bears#1780]
Various comments on https://github.com/coala/projects/pull/289

/cc @jayvdb

**Comment by meetmangukiya** [comment]
fwiw CI running coala doesn't report those error, but gitmate runs coala as well, not sure what's wrong there

**Comment by meetmangukiya** [comment]
Maybe gitmate is using old coala? @sils do you recall what version of coala does gitmate1 use?

**Comment by sils** [comment]
@meetmangukiya working theory is that we have connectivity issues with the server. I'm not sure wether it uses coala 0.9 or 0.10 but I think it's 0.10

**Comment by meetmangukiya** [comment]
this is confusing: https://github.com/coala/projects/blob/master/.coafile doesn't have InvalidLinkBear enabled, I wonder what gitmate's been complaining then :confused: 

Definitely not a bug in InvalidLinkBear.
(Closing.)

**Comment by jayvdb** [comment]
I suspect this is due to https://github.com/coala/coala-bears/issues/1782
