### ISSUE TITLE
Use vulture as a library rather than as a command line tool in VultureBear

### ISSUE THREAD

**Issue by RJ722** [coala/coala-bears#1805]
Currently, VultureBear executes vulture as follows:
```python
stdout_output, _ = run_shell_command(
        (self.EXECUTABLE,) +
        tuple(filename for filename in self.file_dict.keys()),
        cwd=self.get_config_dir())
``` 

vulture's utility can also be harnessed directly through `vulture.scavenge` - This would be optimal as it would save time of memory copying.

Reference:
- [VultureBear](https://github.com/coala/coala-bears/blob/master/bears/python/VultureBear.py)
- [vulture](https://github.com/jendrikseipp/vulture)

**Comment by jayvdb** [comment]
Probably a good idea to add Appveyor CI testing on vulture, to avoid any regressions from switching from Win32 command execution to python package loading.

**Comment by jendrikseipp** [comment]
@jayvdb I guess you mean using appveyor for testing VultureBear, right?

**Comment by RJ722** [comment]
> @jayvdb I guess you mean using appveyor for testing VultureBear, right?

Nope, I confirmed!

**Comment by jendrikseipp** [comment]
Can you clarify, please? What exactly should be tested with appveyor?

**Comment by Makman2** [comment]
I think he meant we should encourage the guys from vulture to run tests also on AppVeyor for Windows^^ Misunderstood myself^^

**Comment by Makman2** [comment]
Could be made into a new issue though (encouraging vulture to introduce AppVeyor tests)^^

**Comment by Makman2** [comment]
@RJ722 please assign yourself if you are working on the issue :+1:

**Comment by Makman2** [comment]
@jendrikseipp I haven't seen that you are actually the owner of `vulture` 😅
