### ISSUE TITLE
Add `Stylus` to readme 

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1807]
Add `Stylus` to readme under the Languages supported section.
difficulty/newcomer

**Comment by Anirudh257** [comment]
Hey, I would love to work on this

**Comment by jayvdb** [comment]
@Anirudh257 this issue is assigned to @sgreene570 .  You'll need to find another [newcomer](http://coala.io/new) issue ;-)

**Comment by Anirudh257** [comment]
Sorry

**Comment by appi147** [comment]
Can I do this?

**Comment by yash-nisar** [comment]
Sure, use `corobo` and assign yourself by typing in `corobo assign https://github.com/coala/coala-bears/issues/1807` on https://coala.io/chat
