### ISSUE TITLE
Update required version of vulture in VultureBear

### ISSUE THREAD

**Issue by RJ722** [coala/coala-bears#1809]
`VultureBear` currently requires vulture 0.10.0 to be installed:
```python
class VultureBear(GlobalBear):
    LANGUAGES = {'Python', 'Python 3'}
    REQUIREMENTS = {PipRequirement('vulture', '0.10.0')}
```
vulture 0.14.0 has been released. This should be updated.

**Comment by RJ722** [comment]
Since `Vulture.unused_imports` was introduced in vulture 0.12.0, it is necessary for VultureBear to be able to make use of the vulture API.

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/pull/1814 is merged, and completed this task.
