### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1811]
Seems like we have problems with `Jinja2Bear`.

See e.g. PR https://github.com/coala/coala-bears/pull/1808
Builds:
https://ci.appveyor.com/project/coala/coala-bears/build/1.0.6618/job/hh5qt31a9vq8be4x
https://travis-ci.org/coala/coala-bears/jobs/239619674

**Comment by sgreene570** [comment]
https://github.com/coala/coala-bears/pull/1810

**Comment by meetmangukiya** [comment]
dup of https://github.com/coala/coala-bears/issues/1812
