### ISSUE TITLE
Feature request: FilenameBear: Prefix suffix rules

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-bears#1817]
A friend of mine wants a linter to check if the files are prefixed with a word. It'll be a nice feature to implement in FilenameBear.

**Comment by AMR-KELEG** [comment]
I would  like to work on the issue.
Do you think it would be better if i added a param check_prefix to the FilenameBear or add a new separate bear?

**Comment by yukiisbored** [comment]
@AMR-KELEG You can just have settings like `prefix` and `suffix` and will check for those if exists.

**Comment by AMR-KELEG** [comment]
![coala](https://user-images.githubusercontent.com/8365743/27038477-70cbae60-4f8b-11e7-8e4f-ee8317dd7a94.png)
I used the yield Result -as in the FilenameBear- to generate this dialog.
Is the shown dialog appropriate?

**Comment by yukiisbored** [comment]
@AMR-KELEG It looks okay, but I think "The filename doesn't use the '<prefix goes here>' prefix" would be better because it doesn't makes the user confused.
Also, euhm I think "is not" is a grammar issue
