### ISSUE TITLE
Change default remove_all_unused_import to True or don't propose a patch 

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-bears#1824]
(consider a breaking change if the default was changed. (for release notes autors))

**Comment by mridubhatnagar** [comment]
What else is required to be done in this one? .  Should the patch option be removed as well ?

**Comment by meetmangukiya** [comment]
> What else is required to be done in this one? . Should the patch option be removed as well ?

nope, just change the default, one issue at a time :wink:

**Comment by mridubhatnagar** [comment]
@userzimmermann in the review you suggested to make changes in the docstring. But when I changed the default remove_all_unused_imports = True now also only uneeded builtin imports are getting removed.

I added 2 unused imports in PyUnusedCodeBear.py.
import time
from rstcheck import check

And ran coala.
So, it suggested the patch for only "time" as it is builtin .
So the explaination in docstring seems right to me.

**Comment by userzimmermann** [comment]
@mridubhatnagar But then the whole change would make no sense ;) And when I checkout your branch from https://github.com/coala/coala-bears/issues/1829 and add those imports to **PyUnusedCodeBear.py** and run

```
> coala -I --bears PyUnusedCodeBear --files bears/python/PyUnusedCodeBear.py
Executing section cli...
```

I get

```
|    | [NORMAL] PyUnusedCodeBear:
|    | This file contains unused source code.
|----|    | c:\users\zimmermann\projects\coala\bears\bears\python\pyunusedcodebear.py
|    |++++| c:\users\zimmermann\projects\coala\bears\bears\python\pyunusedcodebear.py
|   1|    |-import time
|   2|   1|
|   3|    |-from rstcheck import check
|   4|   2|
|   5|   3| import autoflake
|   6|   4|
```

How did you run `coala`?

Are you sure that the `PyUnusedCodeBear` is taken from your repo? Have you installed the `coala-bears` package from PyPI in your Python environment or have you only installed your local `coala-bears` repo in development mode with `pip install -e /path/to/your/repo`?

cc @meetmangukiya

**Comment by userzimmermann** [comment]
@mridubhatnagar BTW: Good that you mentioned the docstring again :) So I realized that it also doesn't reflect the default `remove_unused_variables=True`. I created https://github.com/coala/coala-bears/issues/1832 for that and assigned it to you

**Comment by mridubhatnagar** [comment]
No. I guess I had done none of the things you mentioned above. 
I had just cloned the coala-bears repo and run coala in it.

**Comment by mridubhatnagar** [comment]
When I run coala using the command you mentioned. The output remains the same.
```
(venv) C:\Users\hp\Desktop\Coala\coala-bears>coala -I --bears PyUnusedCodeBear --files bears/python/PyUnusedCodeBear.py
Executing section Default...

bears\python\pyunusedcodebear.py
|   2| import┬╖time
|    | [NORMAL] PyUnusedCodeBear:
|    | This file contains unused source code.
|----|    | c:\users\hp\desktop\coala\coala-bears\bears\python\pyunusedcodebear.py
|    |++++| c:\users\hp\desktop\coala\coala-bears\bears\python\pyunusedcodebear.py
|   1|   1| import autoflake
|   2|    |-import time
|   3|   2| from rstcheck import check
|   4|   3|
|   5|   4| from coalib.bears.LocalBear import LocalBear
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Apply patch
|    |  3: Add ignore comment
|    | Enter number (Ctrl-Z to exit): 0
```

**Comment by userzimmermann** [comment]
Please leave the `coala-bears` directory and paste me the output of the following command run from your command line:

`echo %cd% && python -c "print(__import__('bears').__file__)"`

**Comment by mridubhatnagar** [comment]
```
(venv) C:\Users\hp\Desktop\Coala>echo %cd% && python -c "print(__import__('bears'))"
C:\Users\hp\Desktop\Coala
<module 'bears' from 'C:\\Users\\hp\\Desktop\\Coala\\venv\\lib\\site-packages\\bears\\__init__.py'>
```

**Comment by userzimmermann** [comment]
@mridubhatnagar And there you see the problem: `coala-bears` is installed in your `site-packages`. So you can change as much as you want in your repo... The bears will always be taken from `site-packages`

So `pip uninstall coala-bears` and `pip install -e .` in your repo directory

**Comment by sils** [comment]
there's a development setup page at least

Write your blog post...

**Comment by mridubhatnagar** [comment]
@userzimmermann Thanks. Changes work as expected now. :)

**Comment by mridubhatnagar** [comment]
Yes, the development setup page mentions this step http://api.coala.io/en/latest/Developers/Development_Setup.html. 
Sorry, I had just forked and cloned the repo and started working.

**Comment by Makman2** [comment]
I think installing the repo as a dev-installation is not always best. I usually prefer installing it manually as I work mostly on components, and only tests are important for me. Then I use sometimes coala normally as a tool. I already wondered sometimes why coala crashed, and forgot that I installed it ages ago as a dev-version which has picked up my recent not-yet-ready changes ;)

**Comment by Makman2** [comment]
Anyway, please open a different issue for this if you want it dev-install instructions to be mandatory :)
