### ISSUE TITLE
PyUnusedCodeBear.run() docstring must be changed according to default remove_unused_variables=True

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala-bears#1832]
Current docstring:

```python
        """
        Detects unused code. By default this functionality is limited to:

        - Unneeded pass statements.
        - Unneeded builtin imports.

        :param remove_all_unused_imports:
            True removes all unused imports - might have side effects
        :param remove_unused_variables:
            True removes unused variables - might have side effects
        """
```

The `... is limited to:` list must be extended and `:param remove_unused_variables:` must focus on the `False` alternative

This is related to https://github.com/coala/coala-bears/issues/1824 and https://github.com/coala/coala-bears/pull/1829 , which are about setting also default `remove_all_unused_imports=True`

cc @meetmangukiya

**Comment by mridubhatnagar** [comment]
Just for the sake of checking behavior. I tried changing the default of remove_all_unused_variable to False. And ran coala. This way also it removed the unused import. And when I again set the value back to True it then also removed the unused import. What's the difference?

**Comment by userzimmermann** [comment]
Like the name implies, `remove_unused_variables` is about unneeded variables, not unneeded imports ;)

Let's take a sample **fancy_seven.py** :)

```python
def seven():
    five = 5
    return 7
```

When we run `coala -I --bears PyUnusedCodeBear --files fancy_seven.py` we get:

```diff
|    | [NORMAL] PyUnusedCodeBear:
|    | This file contains unused source code.
|----|    | c:\users\zimmermann\projects\coala\bears\unusedvar.py
|    |++++| c:\users\zimmermann\projects\coala\bears\unusedvar.py
|   1|   1| def seven():
|   2|    |-    five = 5
|   3|   2|     return 7
```

With `remove_unused_variables=False` there is no patch at all

cc @meetmangukiya

**Comment by meetmangukiya** [comment]
@userzimnermann isn't that the expected behavior?

**Comment by userzimmermann** [comment]
@meetmangukiya It is! Exactly :) But @mridubhatnagar mixed it up a bit with imports, so I wanted show what it's actually about ;)

**Comment by mridubhatnagar** [comment]
@userzimmermann Even on doing remove_unused_variables= False. The variable is getting removed. I am on windows.
```
(venv) C:\Users\hp\Desktop\Coala\coala-bears>coala -I --bears PyUnusedCodeBear --files bears/python/PyUnusedCodeBear.py
Executing section Default...

bears\python\pyunusedcodebear.py
|  32| ┬╖┬╖┬╖┬╖┬╖┬╖┬╖┬╖seven┬╖=┬╖7
|    | [NORMAL] PyUnusedCodeBear:
|    | This file contains unused source code.
|----|    | c:\users\hp\desktop\coala\coala-bears\bears\python\pyunusedcodebear.py
|    |++++| c:\users\hp\desktop\coala\coala-bears\bears\python\pyunusedcodebear.py
|  29|  29|         :param remove_unused_variables:
|  30|  30|             False removes unused variables - might have side effects
|  31|  31|         """
|  32|    |-        seven = 7
|  33|  32|
|  34|  33|         corrected = autoflake.fix_code(
|  35|  34|                        ''.join(file),
|    | *0: Do nothing
|    |  1: Open file(s)
|    |  2: Apply patch
|    |  3: Add ignore comment
|    | Enter number (Ctrl-Z to exit): ^Z
Found EOF. Exiting gracefully.
```

**Comment by mridubhatnagar** [comment]
Yeah, sorry understood the mistake in my very first comment. I meant variables only. Above snippet shows. Even on setting remove_unused_variables = False. There is a patch being proposed.

**Comment by userzimmermann** [comment]
@mridubhatnagar See https://github.com/coala/coala-bears/issues/1824#issuecomment-310077069 :)
