### ISSUE TITLE
Performance improvement for RubocopBear

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1839]
We should only generate the `config_file` if `rubocop_config` is not given as an argument. In this case, the `config_file` is generated everytime.

See [this](https://github.com/coala/coala-bears/blob/master/bears/js/JSHintBear.py#L319-L391) for reference.

difficulty/low
area/lintbears
size/S

**Comment by jayvdb** [comment]
Copying parts of https://github.com/coala/coala-bears/pull/1841#pullrequestreview-44208692 that are more relevant for further discussion even after that PR is merged.

It looks like you might be solving #1077

More broadly, is this a performance problem affecting all bears that use a config file?
Is it documented that bears should do this when they have a config file?
Is this the only bear which doesnt do it?  Is there bugs about fixing the others?

See coala/coala#4072 for my initial attempt at trying to find a way to make config files a native part of the Linter class.

**Comment by jayvdb** [comment]
some answers at https://github.com/coala/coala-bears/pull/1841#issuecomment-308641115

@yash-nisar , which other bears have this problem?  Can you create 'low' bugs for them, and use your PR as an example for them to follow.
