### ISSUE TITLE
Bear Proposal: RousseauBear

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1843]
https://github.com/GitbookIO/rousseau

difficulty/low
area/lintbears

**Comment by Makman2** [comment]
Aren't you going to cover support for Rousseau with your coming `TextLintBear`?

**Comment by yash-nisar** [comment]
Yes, we are going to cover support for Rousseau, so should we drop the idea of a dedicated `RousseauBear`?

I thought of having this since we have dedicated `AlexBear`, `WriteGoodLintBear`, etc. You can close the issue this is redundant :wink: 

CC @Makman2

**Comment by Makman2** [comment]
Yeah I think if we don't have a good reason for now, let's close. Saves effort :)
