### ISSUE TITLE
WriteGoodLintBear: Change setting docstring

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1850]
Change 
Allows ``weasel words`` for example ``often``, ``probably``
to
Allows "weasel words", for example "often" or "probably".
We should use regular double quotes as those are words referring to standard prose and not specific technical/informatics term.

difficulty/newcomer

**Comment by Vamshi99** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/1851
