### ISSUE TITLE
WriteGoodLintBear: Change backticks to double quotes

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1851]
We should use regular double quotes as those are words referring to standard prose and not specific technical/informatics term below: 
```
        :param allow_passive_voice:     Allows passive voice.
        :param allow_so_beginning:      Allows ``So`` at the beginning of
                                        the sentence.
        :param allow_adverbs:           Allows adverbs that can weaken the
                                        meaning, such as: ``really``,
                                        ``very``, ``extremely``, etc.
        :param allow_repeated_words:    Allows lexical illusions – cases
                                        where a word is repeated.
        :param allow_there_is:          Allows ``There is`` or ``There are``
                                        at the beginning of the sentence.
        :param allow_ambiguous_words:   Allows ``weasel words`` for example
                                        ``often``, ``probably``
        :param allow_extra_words:       Allows wordy phrases and unnecessary
                                        words.
        :param allow_cliche_phrases:    Allows common cliche phrases in the
                                        sentence.
```
difficulty/newcomer

**Comment by S2606** [comment]
I would love to contribute to this.Pls assign it to me

**Comment by yash-nisar** [comment]
You've already worked on a newcomer issue right ?

**Comment by rahuldecoded** [comment]
@yash-nisar Can I work in this?

**Comment by yash-nisar** [comment]
@rahuldecoded You've also done a newcomer issue right ?

**Comment by rahuldecoded** [comment]
@yash-nisar Yup! Just 10 mins back. I've been reading about Coala. Can you share come important resources to get started with Coala.

**Comment by yash-nisar** [comment]
Sorry, we do not allow more people to do more than 1 newcomer issue because it is a lot of work to search and file them. Newcomer issues are basically meant to get you accustomed to the workflow at coala. You could do a `difficulty/low` issue instead.

Here are the docs to get you started : 
* http://api.coala.io/en/latest/
* http://coala.readthedocs.io/en/latest/Users/Tutorial.html

Also, you can ping us on https://coala.io/chat if you need any help. :wink:

**Comment by rahuldecoded** [comment]
Thank you.  :+1:
