### ISSUE TITLE
master build is red

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#1880]
The master builds are failing, and now I get on one PR the same error:
https://circleci.com/gh/coala/coala-bears/6674?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

(For PR https://github.com/coala/coala-bears/pull/1836#issuecomment-312147321)

**Comment by jayvdb** [comment]
Probably fixed by https://github.com/coala/coala-bears/pull/1872

**Comment by jayvdb** [comment]
Seems fixed.
