### ISSUE TITLE
SCSSLintBear: Rename parameter check_ulrs_format to check_url_format

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1912]
Spelling mistake in 3627f33c9.

The setting name needs to be deprecated using decorator `@deprecate_settings`

**Comment by sidharthskumar** [comment]
hey @jayvdb i have made the required changes in the file. But what is to be done with the second line of your statement?

> The setting name needs to be deprecated using decorator @deprecate_settings

**Comment by jayvdb** [comment]
Is deprecating settings not mentioned in the developer docs? Ask on gitter, or search bears repo for 'deprecate'.

**Comment by sidharthskumar** [comment]
OK, I googled about it and researched a lot and finally come to know about
what actually it is . But forgot to check in Dev docs . Thanks John . I LL
refer to that now

**Comment by palash25** [comment]
@jayvdb I would like to be assigned to this issue
