### ISSUE TITLE
PyImportSortBear drops/moves comments

### ISSUE THREAD

**Issue by Alexander-N** [coala/coala-bears#1929]
PyImportBear drops the comment from the following example
```python
import distutils
# this comment is important and should not be removed 
from sys import api_version as api_version
```
Without the alias ``as api_version`` the comment is moved to the top of the file, separating it from its context.

**Comment by NiklasMM** [comment]
This problem also occurs when running `isort` directly, so I've reported the issue upstream.

**Comment by Alexander-N** [comment]
This has been fixed in isort.
