### ISSUE TITLE
Docstring format wrong in DocumentationStyleBear

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#1941]
https://github.com/coala/coala-bears/blob/master/bears/documentation/DocumentationStyleBear.py#L105

It should be either in the table format or the new line format (preferred more)

**Comment by Raman1121** [comment]
I want to work on this issue. Can you please explain a bit more what exactly I will have to do in this?

**Comment by SanketDG** [comment]
If you take a look at https://github.com/coala/coala-bears/blob/master/bears/documentation/DocumentationStyleBear.py#L114, you will see it is very different from the preferred [style](https://github.com/coala/coala-bears/blob/master/bears/documentation/DocumentationStyleBear.py#L31)

Your task is to write the `param` and `return`'s in tje preferred style, taht's all :)

**Comment by Raman1121** [comment]
Got it!
I am gonna start working on this now.

**Comment by vedantc98** [comment]
Is this issue still open? I'm confused as to which function's docstring need to be altered.
@SanketDG Could you assign me and let me know where exactly the docstring needs to be changed?
Thanks!

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by SanketDG** [comment]
@vedantc98 You are assigned, Function in question https://github.com/coala/coala-bears/blob/master/bears/documentation/DocumentationStyleBear.py#L127, the preferred [style](https://github.com/coala/coala-bears/blob/master/bears/documentation/DocumentationStyleBear.py#L31)
