### ISSUE TITLE
Add script to circle to kill developer builds

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#1946]
Circle shouldnt be enabled by developers unless they are debugging a Circle specific problem.  It should only be used on PRs, and master and release builds on coala/* repos.
The script should check for 'Circle' in the commit message to allow a developer build to occur on Circle.
difficulty/low
Opened by @jayvdb at [gitter/coala/coala-bears](https://gitter.im/coala/coala-bears?at=59760eae42d2f6102587fad8)

**Comment by Makman2** [comment]
Like the idea with the `Circle` keyword allowing to build anyway. Maybe we want to extend it a bit, to some command-like sentence `!Build on Circle` (or so), then it's 1. easier to understand 2. it's not so ambiguous :)

**Comment by jayvdb** [comment]
Well i normally start the shortlog with 'Circle: ...' for circle fixes.

Also we should use yaml as well https://stackoverflow.com/questions/37115473/how-do-i-make-circleci-ignore-a-particular-branch

So we need to also name branches 'circle' to bypass that.

**Comment by jayvdb** [comment]
We already have a check in the `.ci/` scripts to check whether the build is occurring on CI.
```
git grep CIRCLE .ci circle.yml
.ci/deps.apt.sh:case $CIRCLE_BUILD_IMAGE in
.ci/deps.apt.sh:if [[ "$CIRCLE_BUILD_IMAGE" == "ubuntu-14.04" ]]; then
.ci/deps.pip.sh:case $CIRCLE_NODE_INDEX in
circle.yml:          if [ $CIRCLE_NODE_INDEX == 1 ] ; then
circle.yml:          if [ $CIRCLE_NODE_INDEX == 1 ] ; then
```

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/issues/2006 is an example of why - it fails regularly on forks, and wastes the shared 'coala' build cycles.
Documentation was just amended to discourage circle builds.

**Comment by aashraybhandar1** [comment]
Can someone guide how to proceed with this issue?

**Comment by kriti21** [comment]
Please review my PR [#2233](https://github.com/coala/coala-bears/pull/2233) @Makman2 @jayvdb

**Comment by Makman2** [comment]
I guess the CircleCI option I've turned is what we want, we don't have to modify our CI scripts:

![screenshot from 2018-02-07 23-10-04](https://user-images.githubusercontent.com/6023916/36164262-25880174-10ec-11e8-8ad3-f07359978820.png)

**Comment by Makman2** [comment]
@jayvdb reopen in case this is not what you've had in mind^^
