### ISSUE TITLE
JSStandardBear: Document rules

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1951]
Since we're aiming for high quality bears, inclusion of settings becomes trivial.
They can be found [here](https://standardjs.com/rules.html). Refer to the `StylintBear` for reference.

difficulty/low
area/documentation

**Comment by palash25** [comment]
Could you direct me to the document file that needs to be changed?

**Comment by yash-nisar** [comment]
https://github.com/coala/coala-bears/blob/master/bears/js/JSStandardBear.py

**Comment by palash25** [comment]
I'm interested in this issue could you please elaborate what needs to be done.

**Comment by Raman1121** [comment]
I am interested in this issue.
What exactly has to be done in this? @yash-nisar

**Comment by yash-nisar** [comment]
We need settings that our users can use to configure bears via the command line or .coafile. For example: See https://github.com/coala/coala-bears/blob/master/bears/stylus/StylintBear.py#L46-L76

**Comment by menukaNaya** [comment]
In this document (https://github.com/coala/coala-bears/blob/master/bears/js/JSStandardBear.py)
there is a function named as "create_arguments". Do i need to change this into camelcase.
Becuase in https://standardjs.com/rules.html it says to do like that.
But then it will affect for the other documents also where this function is used.

Thank you!

**Comment by Makman2** [comment]
No no you should document the available "rules" that standardjs exposes in the bear, but not apply them to our repo.

**Comment by mohitkyadav** [comment]
@menukaNaya Are you working on this?

**Comment by palash25** [comment]
@yash-nisar I would like to be assigned

**Comment by Makman2** [comment]
Reassigned due to inactivity.

**Comment by palash25** [comment]
Do we also need to generate a config file by applying the rules or do we just have to document them as docstrings in the bear?

**Comment by anctartica** [comment]
please assign this issue to me @Makman2

**Comment by Makman2** [comment]
Reassigning due to inactivity.
