### ISSUE TITLE
RST bears should support Sphinx prolog and epilog

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#1954]
http://www.sphinx-doc.org/en/stable/config.html#confval-rst_epilog 
restructuredtext_lint 1.1.0 has added support for this; see https://github.com/twolfson/restructuredtext-lint/issues/39.
difficulty/low
Opened by @jayvdb at [gitter/coala/coala-bears](https://gitter.im/coala/coala-bears?at=597973b342d2f61025881e36)

**Comment by khanchi97** [comment]
@jayvdb if i use updated version of restructuredtext_lint and add rst_prolog configuration in [conf.py](https://github.com/coala/coala-bears/blob/master/docs/conf.py),then it will gonna work or not?
means i've some confusion about now what i should do. :disappointed:

**Comment by Makman2** [comment]
The bears shall get new settings to support the `restructuredtext_lint` prolog/epilog features from the newer version. It's not about using that in our `conf.py` :)

**Comment by kriti21** [comment]
Please provide some more explanation about what needs to be done here @khanchi97 @Makman2

**Comment by shashank-b** [comment]
I would like to work on this. Could someone please assign this to me?

**Comment by khanchi97** [comment]
@kriti21 https://github.com/coala/coala-bears/issues/1954#issuecomment-322454204

**Comment by khanchi97** [comment]
@shashank-b if you want to get assigned in less time then you can request on gitter channel to get assigned 😉

**Comment by shashank-b** [comment]
Thank you @khanchi97  :)

**Comment by jayvdb** [comment]
We should upgrade to 1.2.x, and ensure new features are activated, e.g. with new settings where applicable

**Comment by Anmolbansal1** [comment]
@jayvdb can I work on it?
