### ISSUE TITLE
KeywordBear should not require setting the language

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#1956]
I want to use KeywordBear to do a simple text search, but it's not really cooperating. It needs the language to be set, which is bad for two reasons

- If my language is not understood by coala, I can't use the KeywordBear
- I can't search for the text `FIXME` across all my files, I'd need to have separate sections for Python, JS, HTML, CSS, Markdown, and so on.

**Comment by Makman2** [comment]
Yeah this is definitely bad :+1:

**Comment by jayvdb** [comment]
We have a bunch of bugs about this already, and PRs which were blocked but can probably be rescued.

**Comment by underyx** [comment]
Does anyone remember which coala version introduced this issue? I guess we have to downgrade to be able to use keyword checks at all.

**Comment by Makman2** [comment]
No sorry, I guess you have to `git blame` through the `KeywordBear`.

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/1012

Last good version was 0.8
