### ISSUE TITLE
ApertiumLintBear: Fix typo in `defLabel_closed`

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1964]
`defLabel_closed` -> `def_label_closed` as mentioned in `create_arguments(...)`

difficulty/newcomer
area/documentation

**Comment by csdeshpande19** [comment]
I would like to work on this issue.

**Comment by Makman2** [comment]
You were already assigned to a newcomer issue ;)

**Comment by csdeshpande19** [comment]
I completed that issue.

**Comment by Makman2** [comment]
@csdeshpande19 usually newcomers should do only a single `difficult/newcomer` issue, so other newcomers can get acquainted with our merge process :) You can pick a `difficulty/low` issue which is a bit more challenging ;)

**Comment by amrx101** [comment]
@Makman2 , Can I take this up?
