### ISSUE TITLE
ApertiumLintBear: Incomplete and incorrect line break

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1965]
```
:param repeated_attributes_pardef:
            This issue is responsible for checking any repeated entries in
            the attributes associated with an entry in the parameter
            definition section
            n monodix files.
```
should be corrected to : 
```
:param repeated_attributes_pardef:
            This issue is responsible for checking any repeated entries in
            the attributes associated with an entry in the parameter
            definition in monodix files.
```

difficulty/newcomer
area/documentation

**Comment by csdeshpande19** [comment]
Hey, can I get solve this. Thanks!

**Comment by yash-nisar** [comment]
Sure, use `corobo` and assign yourself. See http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-2-picking-up-an-issue for more information.

**Comment by csdeshpande19** [comment]
I'm a newbie so can you please guide me.

**Comment by Makman2** [comment]
See title: ApertiumLintBear(.py) :)

**Comment by prashantksharma** [comment]
@csdeshpande19 , Hey are you still working on it?

**Comment by prashantksharma** [comment]
@yash-nisar  The last activity of the previous assignee was on 6 Aug, which is a month old.If you can asssign me this issue. I have already corrected this issue and raised a PR https://github.com/coala/coala-bears/pull/2039.

**Comment by Makman2** [comment]
Looks indeed like the old PR went stale. Reassigning and closing old one 👍

**Comment by jayvdb** [comment]
Unassigning due to inactivity.

**Comment by jayvdb** [comment]
(closing PR, not issue .. )

**Comment by kunalvaswani123** [comment]
corobo assign https://github.com/coala/coala-bears/issues/1965

**Comment by apb7** [comment]
@jayvdb: Can you please assign this issue to me? Thanks!

**Comment by apb7** [comment]
Hi @Makman2 and @jayvdb, can you please assign this issue to me? Thanks!
