### ISSUE TITLE
ApertiumLintBear: Fix spelling errors

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1966]
`consits` -> `consists`
`Inconsitency` -> `Inconsistency`

difficulty/newcomer
area/documentation

**Comment by AkshGautam** [comment]
Hey, can I be assigned this job? I wanna do this.Thanks

**Comment by yash-nisar** [comment]
Sure, use `corobo` and assign yourself. See http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-2-picking-up-an-issue for more information.

**Comment by AkshGautam** [comment]
Which documentation file contains the error?  I am new to open source so any help would be appreciated. Cheers!

**Comment by SanketDG** [comment]
You would first want to search for the file `ApertiumLintBear.py` and `run()` inside it should contain the documentation you are looking for

**Comment by AkshGautam** [comment]
Thanks,I am on it!

**Comment by AkshGautam** [comment]
@SanketDG  Sorry, i was away for a while, is this [https://github.com/coala/coala-bears/blob/master/bears/apertium/ApertiumLintBear.py](file) you are talking about?

**Comment by AkshGautam** [comment]
[https://github.com/coala/coala-bears/blob/master/bears/apertium/ApertiumLintBear.py](url)

**Comment by AkshGautam** [comment]
[https://github.com/coala/coala-bears/blob/master/bears/apertium/ApertiumLintBear.py](url)

**Comment by AkshGautam** [comment]
[file](https://github.com/coala/coala-bears/blob/master/bears/apertium/ApertiumLintBear.py)

**Comment by SanketDG** [comment]
@AkshGautam yup!

**Comment by prashantksharma** [comment]
Hey,
I have made the necessary changes:
https://github.com/prashantksharma/coala-bears/commit/8ce44129fa477edec346ca6f90677a92b5e724d3
But, since I am not assigned the issue tell me how I can be assigned this issue.

**Comment by prashantksharma** [comment]
I have made the necessary changes with reference to this issue and created a pull request https://github.com/coala/coala-bears/pull/2035 .Please review. Thank You!

**Comment by SanketDG** [comment]
@prashantksharma You may want to get assigned first to avoid any conflicts, but since in this case, the issue has been staying stale for a long period of time, I'll assign you,

**Comment by prashantksharma** [comment]
@SanketDG  Thank you! 
Yes, I do understand that I need to get assigned first.I did ask for re-assignment in the main channel on gitter.I did not know which maintainer to ask for re-assignment.But, as you said the issue has been staying stale for a long period of time(22 days).This is very-minor issue.Thats why I resolved it and raised a PR.Will follow the protocol from now onwards.
Now, that I have been assigned, do I need to raise a PR again ?

**Comment by prashantksharma** [comment]
@SanketDG  @yash-nisar Could you please review this PR https://github.com/coala/coala-bears/pull/2035. Thanks!

**Comment by SanketDG** [comment]
> Now, that I have been assigned, do I need to raise a PR again ?

Nope, no need. Just wait for someone to review your PR.

**Comment by Makman2** [comment]
Unassigning due to inactivity.
