### ISSUE TITLE
Move `severity_map` inside the `linter` decorator

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#1971]
difficulty/newcomer
Opened by @yash-nisar at [gitter/coala/coala-bears](https://gitter.im/coala/coala-bears?at=5981f152a7b406262d51b23f)

**Comment by yash-nisar** [comment]
Associated bear: `RuboCopBear`

**Comment by Makman2** [comment]
No that's actually wrong for the `RuboCopBear`, because it overrides `process_output` itself. Providing it inside linter makes the map inaccessible (and makes no sense as the output-format is not `regex`).

**Comment by yash-nisar** [comment]
Ah alright, we need to access it inside `process_output`, so should be defined inside the class explicitly.

**Comment by yash-nisar** [comment]
Damnit, my bad.
