### ISSUE TITLE
PylintBear breaks on Python 3.5.0

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1973]
https://circleci.com/gh/jayvdb/coala-bears/814

**Comment by sangamcse** [comment]
Is it still open? Can I work on this?

**Comment by nvzard** [comment]
Is this a duplicate issue? coz I already have a PR https://github.com/coala/coala-bears/pull/2184

**Comment by Makman2** [comment]
Seems the solutions are same. In this case, please coordinate. @nvzard check that your PR solves this issue too to be sure :+1:
