### ISSUE TITLE
Upgrade restructuredtext-lint to 1.1

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#1991]
Opened by @khanchi97 at [gitter/coala/coala](https://gitter.im/coala/coala?at=598d3c031c8697534aa95011)

**Comment by Makman2** [comment]
Does the old one not work? :)

**Comment by khanchi97** [comment]
@Makman2 I think we don't have any issue related to working of old one,but in latest version it has support for sphinx rst_prolog and as we have an issue related to this https://github.com/coala/coala-bears/issues/1954 :)

**Comment by Makman2** [comment]
I would close this issue to make #1954 the main one, as the reason to upgrade are these prolog/epilog features mentioned in that issue (which automatically involves the upgrading of `restructuredtext-lint`).
