### ISSUE TITLE
ClangFunctionDifferenceBear: Replace triple single-quoted strings with triple double-quoted strings

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#1999]
Triple double quoted strings (`"""`) should be used for docstrings instead of (`'''`).

difficulty/newcomer
area/documentation

**Comment by akspr7** [comment]
Hey, can you tell me where i need to replace?

**Comment by menukaNaya** [comment]
@akspr7 
Are you still working on this issue...

**Comment by acashmkj** [comment]
@akspr7 are you still working on this issue ?

**Comment by menukaNaya** [comment]
Yes.
