### ISSUE TITLE
Jinja2Bear : add support for Whitespace control

### ISSUE THREAD

**Issue by aladjadj** [coala/coala-bears#2002]
Linter doesn't support whitespace control :
http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control

for sample : {% condition -%}
for the moment the linter return many messages: 
 - Control blocks should be spaced with `1` spaces on each side.
 - End tag label does not match expected label
-  Control start tag has no corresponding end

**Comment by kriti21** [comment]
Please assign this issue to me @Makman2
