### ISSUE TITLE
FilenameBear: Check filename length

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2003]
Windows has an API limitation of 260 characters per filename, causing fetches to fail.
As a result, it is helpful to catch this before files with long names are committed to the repository.
There is a workaround `git config core.longpaths true`, however Windows users are typically also using a GUI which doesnt let them run `git config` or have a settings panel for git config.
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
This might be incorporated into the existing FilenameBear.
Opened by @jayvdb at [gitter/coala/coala](https://gitter.im/coala/coala?at=5994720e51915d962af7ef01)

**Comment by jayvdb** [comment]
Note that `git` also has a different limit, 4096 characters (or bytes?), which could also be used as a default, as this will still catch such errors before `git commit`.

**Comment by Makman2** [comment]
Yeah would also say we incorporate this feature into `FilenameBear` :+1:
