### ISSUE TITLE
HTMLLintBear: Upgrade `html-linter` to 0.4.0

### ISSUE THREAD

**Issue by yash-nisar** [coala/coala-bears#2004]
difficulty/newcomer

**Comment by Makman2** [comment]
@yash-nisar any specific reason?

**Comment by yash-nisar** [comment]
I thought it would be great if our linters are up to date :wink:

**Comment by Raman1121** [comment]
Can you direct me to the file which is addressed here? @yash-nisar

**Comment by Raman1121** [comment]
I am interested in this issue. Can I work on it?

**Comment by Raman1121** [comment]
I am interested in this issue and want to work on it.

**Comment by prashantksharma** [comment]
@Raman1121 Are you still working on it?

**Comment by sangamcse** [comment]
@Raman1121 What is the status of the issue??

**Comment by Makman2** [comment]
Unassigning due to inactivity.
