### ISSUE TITLE
uncached circle build sometimes fails on `deps.opam.sh`

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2006]
For reference
https://circleci.com/gh/damngamerz/coala-bears/193
possible fix
>We need to create/use packages for ubuntu, etc

difficulty/medium
Opened by @damngamerz at [gitter/coala/coala-bears](https://gitter.im/coala/coala-bears?at=5995471376a757f808b2a050)

**Comment by harshhx17** [comment]
@jayvdb Please assign this issue to me :smile:
