### ISSUE TITLE
TravisLintBearTest: Close opened test files properly

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2042]
py.test gives warnings on https://circleci.com/gh/coala/coala-bears/7126 like
```
tests/yaml/TravisLintBearTest.py::TravisLintBearTest::test_good_file
  /home/ubuntu/coala-bears/tests/yaml/TravisLintBearTest.py:23: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ubuntu/coala-bears/tests/yaml/travislint_test_files/.good_travis.yml' mode='r' encoding='UTF-8'>
    return open(get_testfile_path(name)).readlines()
```
To not rely on ref-counting for object destruction (which isn't anyway an official feature in Python to allow custom destructors), we should close the file manually by using a with-context:
```
with open(get_testfile_path(name)) as fl:
    return fl.readlines()
```

**Comment by sanketnavin** [comment]
Can you assign me to this issue?

**Comment by anuyog1004** [comment]
Please assign this issue to me.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by anuyog1004** [comment]
Can I work on it now?
