### ISSUE TITLE
XMLBearTest fails on AppVeyor

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2043]
See https://ci.appveyor.com/project/coala/coala-bears/build/1.0.7662/job/2pf6yc8u9gq0c0mo

**Comment by Makman2** [comment]
The error happens due to a conversion fail with the settings that use `path_or_url`. It fallbacks to `path` which then raises an error because `setting.origin == ''` (empty string):
```
ValueError: Cannot determine path without origin.
```
And inside the testing machinery this gets swallowed and reported as no results are returned, but bear operated normally (which is just wrong in this case).

What's interesting that this happens only on Windows.

Continuing investigation...

**Comment by Makman2** [comment]
Found out why it works on Linux systems:
This condition is `True` there inside `setting.__path__()`:
```python
strrep = str(self).strip()
if os.path.isabs(strrep):
    return strrep
```

**Comment by Makman2** [comment]
It seems that filenames passed as settings inside `verify_local_bear` go through the settings-machinery in coala and single escape characters get removed. Once a Windows path with backslashes reaches the above snippet, it has no backslash characters any more and that doesn't look like a path any more for sure, failing the check, and trying to retrieve `origin`, which fails as it's not getting set inside `verify_local_bear` (that doesn't make any sense anyway, settings are passed virtually, thus having no real origin).

To keep backslashes that appear in Windows paths, those have to be escaped when used in settings.

**Comment by Makman2** [comment]
It appears that libxml2 had a recent update affecting xmllint. There's another error appearing that might occur because of changed error messages. Because errors seem to be made for human eyes, the bear is currently not in the state to catch that properly. Thus deactivating the affected test-case is in my opinion right now the best option. https://github.com/coala/coala-bears/issues/2045 and https://github.com/coala/coala-bears/issues/2046 shall take care of that in future.

**Comment by jayvdb** [comment]
The title of this issue says AppVeyor (Windows), but the first message of this issues says circleci (Ubuntu).

Is this problem only on AppVeyor?  Or is it cross platform?
This is critically important as libxml2 isnt a well maintained part of the Windows/AppVeyor ecosystem, so the problem might be due to issues that can be solved there.

**Comment by Makman2** [comment]
> The title of this issue says AppVeyor (Windows), but the first message of this issues says circleci (Ubuntu).

Oh sorry I've put the wrong link into the issue description. Corrected :+1:

**Comment by Makman2** [comment]
Those were all errors currently that lead to a fail on AppVeyor, I've split up those into separate issues:
- https://github.com/coala/coala-bears/issues/2052
- https://github.com/coala/coala-bears/issues/2053
