### ISSUE TITLE
DuplicateFileBearTest: Use `assertEqual` instead of `assertEquals`

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2050]
Appears e.g. in https://circleci.com/gh/coala/coala-bears/7124?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link:

```
tests/general/DuplicatefileBearTest.py::DuplicateFileBearTest::test_results_no_duplicates
  /home/ubuntu/coala-bears/tests/general/DuplicatefileBearTest.py:53: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(messages, [])
```

**Comment by sthkindacrazy** [comment]
can I work on this deprecation issue?

**Comment by shahidikram0701** [comment]
I want to work on this issue.

**Comment by Makman2** [comment]
@Dumidu921 are you working on this issue?

**Comment by supriyanta** [comment]
I would like to work on it.assign me in i....

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by RaiVaibhav** [comment]
@supriyanta  assign yourself first

**Comment by RaiVaibhav** [comment]
Just to the log of `$ bash .ci/tests.sh (0)` you will get the `warning` there.

**Comment by Passionatecricketer** [comment]
@supriyanta You still working on this issue?

**Comment by supriyanta** [comment]
Yes

**Comment by mridubhatnagar** [comment]
Hey @supriyanta. 
Congrats on raising your PR in the community.
In my opinion we can amend the commit message a bit. 

> It changes the code

We can replace this and have something like

> Use assertEqual as assertEquals has been
deprecated.

**Comment by duskybomb** [comment]
@Makman2 assign this to me

**Comment by Makman2** [comment]
@duskybomb You already have a newcomer issue assigned.

**Comment by Makman2** [comment]
However, unassigning due to inactvitiy.

**Comment by joaomcarvalho** [comment]
Anyone working on this issue? I would like to help @Makman2

**Comment by joaomcarvalho** [comment]
@Makman2 done :)

**Comment by EverWinter23** [comment]
I would like to help.

**Comment by joaomcarvalho** [comment]
@Makman2 Sorry to bother you again, but can you assign me?
