### ISSUE TITLE
Addition of DS_Store to .gitignore

### ISSUE THREAD

**Issue by stellargo** [coala/coala-bears#2067]
DS_Store should be ignored in coala-bears just like it is already being ignored in coala.

**Comment by Makman2** [comment]
Unassigned due to inactivity.

@cristianossd please assign to an issue before working on it :+1:

**Comment by RaiVaibhav** [comment]
@cristianossd first use corobo bot on gitter to assign yourself.

**Comment by nvzard** [comment]
Can I assign myself this issue ?

**Comment by prnvdixit** [comment]
@Makman2 There are already 3 PRs https://github.com/coala/coala-bears/pull/2068, https://github.com/coala/coala-bears/pull/2072, https://github.com/coala/coala-bears/pull/2076 for this issue 😛 - Can we merge any patch to this issue please?....  Just close this issue 😃 - Though the contributor to the last approved PR https://github.com/coala/coala-bears/pull/2072 hasn't ```yet``` assigned himself 😟 - Please see what needs to be done...

**Comment by RaiVaibhav** [comment]
First PR was mine 😜   Seriously its becoming a mess

**Comment by stellargo** [comment]
@prnvdixit Seems starightforward, 2068 is closed so leave that. 2076 is the one that should be reviewed since it is assigned to the author :)

**Comment by prnvdixit** [comment]
@stellargo But 2072 is the reviewed and approved one and 2076 still needs changes 😛

**Comment by Makman2** [comment]
If approved, the approved one gets merged, doesn't make sense otherwise.

**Comment by nvzard** [comment]
I made @cristianossd  the author of this commit.
