### ISSUE TITLE
Make CppCheckBear a GlobalBear

### ISSUE THREAD

**Issue by Psirus** [coala/coala-bears#2078]
Let's say I have a function `f`, defined in `f.cpp` and used in `g.cpp`. If I run `cppcheck` just on `f.cpp`, it will tell me `[f.cpp:1]: (style) The function 'f' is never used.`. If I run cppcheck on the whole directory, that message disappears, because it sees that the function is being used after-all. However, in coala, these messages also appear, because, presumably, coala runs cppcheck on each individual file. Can I tell it to run on the whole directory?

**Comment by Makman2** [comment]
`CppCheckBear` is currently configured as a `LocalBear`, meaning it works like you said. We can change it to be a `GlobalBear` and adapt it a bit to pass all files at once.

**Comment by Psirus** [comment]
If that doesn't break the usecase of someone else, great!

**Comment by urohit011** [comment]
I would like to work on this.

**Comment by Makman2** [comment]
Then, get yourself assigned ;)

**Comment by khanchi97** [comment]
@urohit011 are you still working on it?

**Comment by Makman2** [comment]
Unassigning due to inactivity.
