### ISSUE TITLE
CSS: Identify missing whitespace between class name and brace

### ISSUE THREAD

**Issue by adtac** [coala/coala-bears#2083]
I was just reviewing and found that SpaceConsistencyBear did not detect the whitespace inconsistency in:

```css
.classname{
  properties
}
```

(Hint: it should be `classname {`, not `classname{`)

Not sure if SpaceConsistencyBear is the right bear for this (maybe create a new bear just for this :P), but I think this is worth detecting.

**Comment by aashraybhandar1** [comment]
Should a new bear be written ?

**Comment by adtac** [comment]
@aashraybhandar1 That's up to you. Feel free to discuss it with others.

My opinion: yes, a new bear for this would be nice (unless there's already a CSS bear that can perform this; check for this before you start writing a new bear, if you go down that route). SpaceConsistencyBear is kinda generic, and this is CSS-specific.

**Comment by Makman2** [comment]
`SpaceConsistencyBear` is as far as I know not aware of languages and syntax, it's meant for simple spacing stuff.

**Comment by blazeu** [comment]
CSSComb is [able to do this ](https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md#space-before-opening-brace) but the option is not available in our [CSSCombBear](https://github.com/coala/coala-bears/blob/1ea886ab9dac649179ab8d6bea490dcc9ad1dd1f/bears/css/CSSCombBear.py)

**Comment by Makman2** [comment]
Then let's implement it there :)

**Comment by RaiVaibhav** [comment]
Can I give it a try?

**Comment by blazeu** [comment]
Sure, also you can probably add all other missing settings in our `CSSCombBear` if there's any ;)

**Comment by RaiVaibhav** [comment]
@blazeu I think the settings included in CSScombBear is best in its own the,creator have taken care of all , some missed but I think only 1-2, also some `config` not incuded are not included and IMO it not needed for ex- `element-case`, `sort order`, `template`
I need your suggestion whether to consider [tab-size](https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md#tab-size) or not , I am confused here

**Comment by RaiVaibhav** [comment]
Till then I am fixing current issue.

**Comment by blazeu** [comment]
Yeah, fix this issue first, that can go in another PR.

Now I think about it there's something off with putting all the settings inside the bear. [ESLintBear](https://github.com/coala/coala-bears/blob/master/bears/js/ESLintBear.py#L49-L52) uses external files or the default .eslintrc to [configure it](https://eslint.org/docs/user-guide/configuring).

csscomb also [behaves like that](https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md#where-to-put-config)

**Comment by RaiVaibhav** [comment]
ohk

**Comment by blazeu** [comment]
@Makman2 What do you think? Should we remove/deprecate the config from CSSCombBear?

**Comment by Makman2** [comment]
> What do you think? Should we remove/deprecate the config from CSSCombBear?

Why? :O

**Comment by blazeu** [comment]
Looking at [ESLintBear](https://github.com/coala/coala-bears/blob/master/bears/js/ESLintBear.py#L49-L52) it has no bear config other than `eslint_config` which is the file containing the actual eslint config.

IMO it's better that way so we can stop adding new config to our bear everytime the upstream linter has a new config.

**Comment by Makman2** [comment]
> IMO it's better that way so we can stop adding new config to our bear everytime the upstream linter has a new config.

But then we shouldn't deprecate the option, right?

However we want to convert people using coala's settings system so it's easier to use multiple bears at once without diving into special configuration syntaxes of other tools. We only have those options to have simple full compatibility with those tools + people can easily migrate to coala with existing config files.

**Comment by blazeu** [comment]
Ah, that's where you guys are going, I see.

**Comment by Makman2** [comment]
> I just realized, if it uses coala's settings then we can also overlap settings between bears leading to simpler settings file.

Exactly. For example `use_spaces` is a very common option that is used by many bears at once.
