### ISSUE TITLE
PySafetyBear fails with an exception due to changes in upstream data format

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#2085]
The format of https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json has been changed, which triggers this exception:

```
      Traceback (most recent call last):
        File "/coala/coalib/bears/Bear.py", line 282, in execute
          return [] if result is None else list(result)
        File "/coala-bears/bears/python/requirements/PySafetyBear.py", line 80, in run
          additional_info=vulnerability.description,
        File "/usr/lib/python3.6/site-packages/safety/safety.py", line 31, in description
          return self.data["description"] if self.is_cve else self.data["changelog"]
      KeyError: 'description'
```

**Comment by RaiVaibhav** [comment]
I would like to give it a try

**Comment by RaiVaibhav** [comment]
@underyx Need information how did you gets the error log??, I run the PySafetyBear on my `requirement.txt` file its running fine

**Comment by underyx** [comment]
@raivaibhav you need to add a vulnerable package version to your requirements as the error is triggered while creating a result. I think bottle==0.10.0 should work.

**Comment by RaiVaibhav** [comment]
I think there are two ways to solve the problem either by change in their `development` of `setup.py` file or either solve in our Bear File 
```
Both will works but I think The first method is far better as we it will catch the keyError intially so we  don't create a problem later i.e for example in Bear file   
```

**Comment by jayvdb** [comment]
These database files were updated 29 days ago https://github.com/pyupio/safety-db/tree/master/data

And safety 1.6.1 was released 11 days ago.
