### ISSUE TITLE
issue with installing coala-bears

### ISSUE THREAD

**Issue by sagar-cenation** [coala/coala-bears#2112]
Collecting coala-bears
  Downloading coala-bears-0.11.1.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 21kB/s 
Collecting coala~=0.11.0 (from coala-bears)
  Downloading coala-0.11.0.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 8.4kB/s 
    Complete output from command python setup.py egg_info:
    coala supports only python 3.4 or later.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 4 in /tmp/pip-build-QzkO6C/coala/

**Comment by Makman2** [comment]
> coala supports only python 3.4 or later.
