### ISSUE TITLE
KeywordBear.check_keywords: Indent parameters correctly

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2120]
4 spaces relative to parameter reference `:param name_of_param:`.

If you don't know what that means, just follow the documentation style of other functions in the same file ;)

**Comment by gureks** [comment]
Can you please elaborate a bit?

**Comment by Makman2** [comment]
> If you don't know what that means, just follow the documentation style of other functions in the same file ;)

**Comment by LifetimeAlone** [comment]
Seems like the issue has already been solved:
https://github.com/coala/coala-bears/commit/06d1636f601a4d727fc0481edd7feef87b155d89

**Comment by RJ722** [comment]
Yes, seems like it, the doc string indentation was fixed along with https://github.com/coala/coala-bears/issues/1797

Some maintainer would soon close this issue. @LifetimeAlone, you may can find other newcomer issues here: https://coala.io/new

**Comment by Makman2** [comment]
Yeah a rushed cherry-pick without looking at the original PR which unacked that commit actually. Too late, it's done.
