### ISSUE TITLE
MarkdownBear: Not outputting the correct output

### ISSUE THREAD

**Issue by blazeu** [coala/coala-bears#2131]
remark is now version 8.
We are still stuck in version 3 and there's a bug ~> https://circleci.com/gh/coala/coala-atom/150

Related: https://github.com/coala/coala-bears/issues/1492

**Comment by jayvdb** [comment]
Upgrading is #1492 .

Is this issue about fixing the current bear with the currently supported remark?
What is the bug in the current bear with the currently supported remark?

**Comment by blazeu** [comment]
Unfortunately the bug does not happen on my local machine but see [Gitter](https://gitter.im/coala/coala?at=5a0e407b51915d962afc18d7).

**Comment by blazeu** [comment]
Built successfully using `remark-cli@~4` `remark-lint@~6` ~> [CircleCI](https://github.com/blazeu/coala-atom/commit/5136b247097bc1cae4eb2c48155b8936351ccf25)

My fork: https://github.com/blazeu/coala-atom/commit/5136b247097bc1cae4eb2c48155b8936351ccf25

And yes I've tried installing `remark@~^3.2.3` and the bug did not happen. I've gone as far as removing all my global npm packages and reinstalling `remark` alone.

**Comment by Grox-Ni** [comment]
remark: 8.0.0, remark-cli: 4.0.0
installed with `yarn global install remark-cli`

Having same complainant "The text does not comply to the set style." and `coala` suggests to delete all my code in README.md on my local machine

**Comment by EverWinter23** [comment]
Would like to work on it.

**Comment by blazeu** [comment]
Given the following markdown:

```md
List:
1. Lorem ipsum
2. Dolor sit
```

MarkdownBear will output:
```
❯ coala --no-orig --flush-cache      
Executing section markdown...

test.md
|   2| 1.·Lorem·ipsum
|   3| 2.·Dolor·sit
|    | [NORMAL] MarkdownBear:
|    | The text does not comply to the set style.
|----|    | /home/surya/Projects/coala/cEPs/test.md
|    |++++| /home/surya/Projects/coala/cEPs/test.md
|   1|   1| List:
|   2|    |-1. Lorem ipsum
|   3|    |-2. Dolor sit
|    |   2|+1\. Lorem ipsum
|    |   3|+2\. Dolor sit
```

It wants to add `\` before `.`

Applying patch will change the md to:
```md
List:
1\. Lorem ipsum
2\. Dolor sit
```

When running MarkdownBear again, it wants to remove the patch that has been applied before (removing `/`):
```
❯ coala --no-orig --flush-cache
Executing section markdown...

test.md
|   2| 1\.·Lorem·ipsum
|   3| 2\.·Dolor·sit
|    | [NORMAL] MarkdownBear:
|    | The text does not comply to the set style.
|----|    | /home/surya/Projects/coala/cEPs/test.md
|    |++++| /home/surya/Projects/coala/cEPs/test.md
|   1|   1| List:
|   2|    |-1\. Lorem ipsum
|   3|    |-2\. Dolor sit
|    |   2|+1. Lorem ipsum
|    |   3|+2. Dolor sit
```

Turns out the problem is missing blank line between paragraph and list.
```md
List:

1. Lorem ipsum
2. Dolor sit
```

**Comment by blazeu** [comment]
Same result with `remark-lint@5` (from coala package.json) and `remark-lint@6`

**Comment by blazeu** [comment]
Got the same result running `remark` directly (with default MarkdownBear config). Suggesting that this bug came from remark itself.

Originally, this issue was opened because https://github.com/coala/coala-atom/issues/81 , Closing because apparently this is duplicate of https://github.com/coala/coala-bears/issues/1235
