### ISSUE TITLE
Rename `DuplicatefileBearTest.py` to DuplicateFileBearTest.py`

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2132]
The casing is wrong.

**Comment by shreyateeza** [comment]
If @gokberksahin is not working on this issue then please assign it to me.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Makman2** [comment]
Ah you already have a newcomer issue in queue @shreyateeza , please pick a `difficulty/low` issue ;)

**Comment by ujjaldas1997** [comment]
@Makman2  please assign this issue to me.

**Comment by Makman2** [comment]
Seems there was recent activity.
