### ISSUE TITLE
Set setup.py url = http://coala.io/

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2135]
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=5a1181aff257ad9109b396a0)

**Comment by yashraj-Dhanuka** [comment]
corobo assign #2135

**Comment by Makman2** [comment]
@yashraj-Dhanuka this only works in gitter ;) Also this issue is currently assigned and quite new, so I would advise to rather pick a different issue ;)

**Comment by yashraj-Dhanuka** [comment]
@Makman2 
Thankyou for your advice sir , but sir assigned user is inactive on this iss,ue for a long time.
Hope you can reassign this issue to me

**Comment by Makman2** [comment]
9 days and he has a PR that's approved. Please pick a different issue ;)

**Comment by mridubhatnagar** [comment]
@yashraj-Dhanuka instead of quickly hopping on to new issues. You can do the requested changes on the Pull Requests that you have raised. In order to get those pull requests merged :)
