### ISSUE TITLE
Don't require a `--files` flag if we're running only global bears

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2144]
Opened by @adtac at [Gitter](https://gitter.im/coala/coala-bears?at=5a1d50cd540c78242d5a517c)

**Comment by Makman2** [comment]
@adtac shouldn't this issue go to `coala/coala`?

**Comment by adtac** [comment]
Oh yes, my mistake.

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala/issues/4928
