### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md: Change cobot to corobo

### ISSUE THREAD

**Issue by co-robo** [coala/coala-bears#2145]
Opened by @Vamshi99 at [Gitter](https://gitter.im/coala/corobo?at=5a1e4f5771ad3f87364249ca)

**Comment by mridubhatnagar** [comment]
Good @yashraj-Dhanuka. As you have claimed this issue first and then have raised a PR. :+1:

**Comment by mridubhatnagar** [comment]
@yashraj-Dhanuka are you a Google Code In participant?

**Comment by yashraj-Dhanuka** [comment]
@mridubhatnagar no, i am not a google code-in participant , but i have my eyes on getting selected in GSOC and work for this community

**Comment by mridubhatnagar** [comment]
See the tasks having gci tags explicitly are meant *ONLY* for the gci participants. 
So, you can work on any other issue that does not have a GCI tag.

On gitter do corobo unassign link to this issue. And you'll be unassigned.

**Comment by jackthepirate6** [comment]
I will work on this issue please assign me
