### ISSUE TITLE
Add pylamaBear

### ISSUE THREAD

**Issue by khanchi97** [coala/coala-bears#2150]
https://github.com/klen/pylama

**Comment by damian1996** [comment]
Can I work on this issue? :)

**Comment by yashraj-Dhanuka** [comment]
@khanchi97 Please Elaborate me this issue and guide me on solving it.

**Comment by khanchi97** [comment]
Take a look at http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html how to write linter bears and try to wrap this linter https://github.com/klen/pylama

**Comment by paavininanda** [comment]
@yashraj-Dhanuka Can i take this up ?

**Comment by Makman2** [comment]
It seems pylama is a wrapper for many other linters, so it does what coala tries to achieve, but on a more specialized and primitive level:

> Code audit tool for Python and JavaScript. Pylama wraps these tools:
>
>    pycodestyle (formerly pep8) © 2012-2013, Florent Xicluna;
    pydocstyle (formerly pep257 by Vladimir Keleshev) © 2014, Amir Rachum;
    PyFlakes © 2005-2013, Kevin Watters;
    Mccabe © Ned Batchelder;
    Pylint © 2013, Logilab (should be installed 'pylama_pylint' module);
    Radon © Michele Lacchia
    gjslint © The Closure Linter Authors (should be installed 'pylama_gjslint' module);

We should rather implement those instead of pylama. Many of them are already implemented.

Feel free to file issues for missing ones.
