### ISSUE TITLE
README.rst : Supported languages should be dynamic

### ISSUE THREAD

**Issue by IpshitaC** [coala/coala-bears#2169]
Add HAML to the list of supported languages.
Relevant file can be found [here](https://github.com/coala/coala-bears/blob/master/README.rst#languages-supported)
Relevant commit can be found [here](https://github.com/coala/coala-bears/commit/c86a6d0f4c88521d5701c7d2fc7c1e9d989bb08a)

difficulty/newcomer area/documentation

**Comment by IpshitaC** [comment]
@jayvdb could this be used as a GCI task?

**Comment by Makman2** [comment]
Let's keep it standalone :+1: @IpshitaC

**Comment by RaiVaibhav** [comment]
```
coalaBear
DuplicateFileBear
FilenameBear
InvalidLinkBear
KeywordBear
LicenseCheckBear
LineCountBear
LineLengthBear
MementoBear
SpaceConsistencyBear
URLBear
```
@IpshitaC  Just tried `coala --show-bears --filter-by-language HAML`
But `HAMLLintBear` is not up there.(don't know much about it's working)
Also https://coala.io/#/languages is also needs to be updated as per `HAML`.

**Comment by Makman2** [comment]
We recently merged `HAMLBear`, so it will appear once you upgrade to the newest coala-bears ;) @RaiVaibhav

**Comment by sanshay** [comment]
@ishanSrt @Makman2 can anyone of you please assign this issue to me.

**Comment by jayvdb** [comment]
Hi @sanshay , sorry to unassign you.

This issue keeps occurring whenever we add new bears, and just adding HAML isnt enough.  We have quite a few other languages also supported since it was last updated.

The README should be generated with `moban` so that the list is always up to date.

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/1609
