### ISSUE TITLE
Circle CI and AppVeyor Build Failing with same error logs on all PRs

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala-bears#2175]
# **error log link of Circle CI:**
https://circleci.com/gh/coala/coala-bears/7640?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
**NOTE**: error logs on different PRs are different but its failing with the same conditions
# error log of AppVeyor:
```
___________________________ PyLintBearTest.test_run ___________________________
self = <tests.python.PyLintBearTest.PyLintBearTest testMethod=test_run>
    def test_run(self):
        self.section.append(Setting('pylint_disable', ''))
        self.check_invalidity(
            self.uut,
            [],  # Doesn't matter, pylint will parse the file
>           self.test_file)
tests\python\PyLintBearTest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Python34\lib\site-packages\coalib\testing\LocalBearTestHelper.py:175: in check_invalidity
    self.assertNotEqual(len(bear_output), 0, msg=msg)
E   AssertionError: 0 == 0 : The local bear 'PyLintBear' yields no result although it should.
============================== warnings summary ===============================
tests/natural_language/LanguageToolBearTest.py::SkipTest
  cannot collect test class 'SkipTest' because it has a __init__ constructor
tests/python/PyromaBearTest.py::PyromaBearTest::test_minimal
  C:\Python34\lib\site-packages\setuptools\dist.py:358: UserWarning: The version specified ('0.0foo') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % self.metadata.version
-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================= 27 tests deselected =============================
 1 failed, 391 passed, 367 skipped, 27 deselected, 2 warnings in 196.69 seconds 
Command exited with code 1
codecov
File not found - '*.gcno'
```
link: https://ci.appveyor.com/project/coala/coala-bears/build/1.0.8216

importance/high

**Comment by RaiVaibhav** [comment]
@ishanSrt  take a look at a `CI` logs both are different on different `CI` but failing on every PR with same conditions
And instead of providing whole log of `CI` here provide a link of log of `CI` of  `last commit of repo` (on your `fork master` )

**Comment by Makman2** [comment]
Hm the build link contains an error for `SCSSLintBear`, not `PyLintBear` @ishanSrt

**Comment by ishanSrt** [comment]
@Makman2 they are 2 err logs of Circle CI and AppVeyor. Both of them are failing.

**Comment by Makman2** [comment]
Could you post both links? Because the relevant bears are different^^

**Comment by Makman2** [comment]
Isolated two issues that cause this umbrella bug:
- https://github.com/coala/coala-bears/issues/2177
- https://github.com/coala/coala-bears/issues/2178

Those take over. Closing.
