### ISSUE TITLE
Update scss_lint for SCSSLintBear

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2179]
Newer versions of `scss_lint` (gem) cause the existing tests to fail, so tests have to be adapted.

**Comment by shreyateeza** [comment]
@Makman2 Please this to me.

**Comment by sangamcse** [comment]
I would like to solve this issue. Please assign it to me.

**Comment by vddesai1998** [comment]
Please assign this issue to me! 
Yeah, @sangamcse commented first but I talked to him, he has no issues if you assign me this issue! :)
