### ISSUE TITLE
Update pylint for PyLintBear

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2180]
Newer versions of `pylint` (pip) cause the existing tests to fail, so tests have to be adapted.

**Comment by shreyateeza** [comment]
@Makman2 Please explain this to me more in detail.

**Comment by Makman2** [comment]
It's about to update `pylint` inside `PyLintBear` to the newest version ;)

**Comment by nvzard** [comment]
@Makman2 I tested this locally with `pylint 1.8.1` but the tests are not failing.

**Comment by nvzard** [comment]
The newer version of `pylint`(1.8.1) is causing the appveyor build to fail not the travis-ci?

**Comment by li-boxuan** [comment]
I opened https://github.com/coala/coala-bears/issues/2826 a month ago and sorry I didn't notice this existing issue. Since someone is working on that issue, I'll close this old one to prevent duplicate work.
