### ISSUE TITLE
Move to composer for php dependencies

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#2187]
For php linting tools, we are better off using a composer setup than using distro packages https://github.com/coala/coala-bears/blob/master/.ci/deps.apt.sh#L28 or manual setup https://github.com/coala/coala-bears/blob/master/.ci/deps.sh#L52

**Comment by SanketDG** [comment]
Related to https://github.com/coala/coala-bears/issues/293 which deals with adding composer, but this is for adding the existing tools that are supported by composer

**Comment by jayvdb** [comment]
> we are better off using a composer setup than using distro packages /.ci/deps.apt.sh@master#L28 

why?  apt is faster.

> or manual setup /.ci/deps.sh@master#L52

again, why?

**Comment by jayvdb** [comment]
The first step is adding ComposerRequirements to the relevant bears.

**Comment by SanketDG** [comment]
> > we are better off using a composer setup than using distro packages /.ci/deps.apt.sh@master#L28
> why? apt is faster.

one good reason would be the sync time of a version release, not to mention 14.04's apt is a little old now :)


> or manual setup /.ci/deps.sh@master#L52
> again, why?

manually setting up dependencies when a package manager is readily available, that's odd right?

we use other major package managers, why not use one for php?

**Comment by sangamcse** [comment]
@jayvdb, Is there other issue open to add `ComposerRequirements` to it's respective bears or it will be added from this issue only? 
> The first step is adding ComposerRequirements to the relevant bears.

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/293
