### ISSUE TITLE
TextLintBear broken

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2191]
On an uncached build, we are getting build errors

https://travis-ci.org/coala/coala-bears/jobs/319742819

cc @yash-nisar

**Comment by Makman2** [comment]
I think I found the reason: I experimented in our `coala/base` docker environment, and during that I've seen that the bear has thousands of npm dependencies, and like thought, those weren't installed. Installing all of them makes the tests pass :+1:

**Comment by Makman2** [comment]
Hmm... I actually missed those packages before, it seems they get installed in the CI...

**Comment by Makman2** [comment]
However the errors in the CI are the same like without the plugins.

**Comment by jayvdb** [comment]
JS plugins are hell.  They are what caused our `MarkdownBear` problems during the last GCI.

**Comment by newbazz** [comment]
@Makman2 can you plz explain the issue a bit.

**Comment by Makman2** [comment]
I tested each npm package individually and found the culprit: `textlint-rule-ginger`
Version `2.1.2` is failing, `2.1.0` and `2.1.1` are not.

**Comment by anctartica** [comment]
do you know why certain versions are causing builds to fail? @Makman2

**Comment by Makman2** [comment]
Seems the newer versions have a different linting behaviour, and those maintainers weren't careful enough.
