### ISSUE TITLE
Ignore comments for more than one bear don't work properly

### ISSUE THREAD

**Issue by pareksha** [coala/coala-bears#2209]
Even though the ignore statement has been added, the same bear is prompting.
```
[   1] print(·'Hey'·)··//·Ignore·CPDBear··//·Ignore·PycodestyleBear·(E201)

Downloads/new.py
[   2] print('Hey')
**** CPDBear [Section: cli | Severity: NORMAL] ****
!    ! Duplicate code found.
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. Print (M)ore info
[    ]  3. Add (I)gnore comment
[    ] Enter number (Ctrl-D to exit): 3
!    ! Please enter a value for the parameter 'language' (No description given.): CPP
[    ] An ignore comment was added to your source code.
```
And look what it did to the file
```
print( 'Hey' )  // Ignore CPDBear  // Ignore PycodestyleBear (E201)  // Ignore CPDBear
print('Hey')
```
Two statements ignoring the same bear have been added.
I think that coala is reading only the second ignore statement.

**Comment by Makman2** [comment]
Looks like an issue on coala itself.

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala/issues/5034

**Comment by ishanSrt** [comment]
can't get PMD to work correctly right now, can you duplicate this with any other bear? also what exactly was your file before. @pareksha
