### ISSUE TITLE
change `sudo: required` to `sudo: enabled` in .travis.yml file

### ISSUE THREAD

**Issue by newbazz** [coala/coala-bears#2212]
![image](https://user-images.githubusercontent.com/25884863/34572172-b3e27384-f196-11e7-8d0e-20e7fe77841e.png)

**Comment by surana-mudit** [comment]
@Makman2  @newbazz  I would like to work on this issue

**Comment by surana-mudit** [comment]
@newbazz  Can you assign this issue to me .
Also I have made changes in the PR, so can you review it again.

**Comment by ankurg22** [comment]
Please assign this to me. I would like to work.

**Comment by newbazz** [comment]
ping @Makman2

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by ankurg22** [comment]
@Makman2 I accepted the invitation. You can assign me this. :)

**Comment by jayvdb** [comment]
wtf.  this `sudo: enabled` is mentioned at https://docs.travis-ci.com/user/getting-started/#Selecting-infrastructure-(optional)

however the real reference is https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System , and it says `sudo: required`, and that is what it has always been.

**Comment by newbazz** [comment]
So should i close the issue @jayvdb

**Comment by jayvdb** [comment]
Eh?  This issue is already closed.

**Comment by newbazz** [comment]
ohh yeah my bad
