### ISSUE TITLE
Bear Proposal: bashate

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2226]
https://github.com/openstack-dev/bashate

**Comment by parimatrix** [comment]
@jayvdb I would like to try to work on this issue. Any specific / helpful thing that I should keep in mind ? Thanks !

**Comment by palash25** [comment]
@parimatrix refer to http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html that's all you need.

**Comment by anctartica** [comment]
please assign this to me @jayvdb

**Comment by Makman2** [comment]
@anctartica Sorry, @parimatrix was first.

**Comment by anctartica** [comment]
@parimatrix are you still working on this?

**Comment by parimatrix** [comment]
@anctartica No. I was working on something else. Sorry for the late reply. You can start working if you would want to.
