### ISSUE TITLE
Typo under Writing_Linter_Bears

### ISSUE THREAD

**Issue by sangamcse** [coala/coala-bears#2232]
There is one typo in `Running and Testing our Bear` section.  Follow this link --> [Writing_Linter_Bears.html](http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html#running-and-testing-our-bear)
```
$ coala --bear-dirs=. --bears=PythonTutorialBear \
> -S pylint_rcfile=my_rcfile --files=sample.py
```
Change `PythonTutorialBear` to `PylintTutorialBear`.

**Comment by AliabbasMerchant** [comment]
Please assign this to me!

**Comment by jackthepirate6** [comment]
Ask Someone to assign it to you on https://gitter.im/coala/coala

**Comment by newbazz** [comment]
@Makman2 assign this to @AliabbasMerchant ;P

**Comment by apoorvaagupta** [comment]
Hello, May I take this issue if no one is working on it?

**Comment by Pradhvan** [comment]
If @AliabbasMerchant  is not working on it. Can someone assign this issue to me?

**Comment by ishanSrt** [comment]
This is not a typo but a mistake.

**Comment by Pradhvan** [comment]
@sangamcse can you review this?

**Comment by Makman2** [comment]
Wrong repo, migrated to https://github.com/coala/coala/issues/5236
