### ISSUE TITLE
Correct the docstring indentation

### ISSUE THREAD

**Issue by newbazz** [coala/coala-bears#2243]
Correct the docstring indentation of CPPLintBear
![image](https://user-images.githubusercontent.com/25884863/35117714-7d8fee2c-fcb5-11e7-8a8a-0eb1aab1b93b.png)
difficulty/newcomer

**Comment by Utkarsh-Mishra-CIC** [comment]
i would like to work on this issue.

**Comment by duskybomb** [comment]
Assign this issue to me @Makman2

**Comment by ankan17** [comment]
Anybody is not yet assigned. Can I work on this issue?

**Comment by newbazz** [comment]
@Makman2

**Comment by Makman2** [comment]
@Utkarsh-Mishra-CIC was first, and meanwhile he has accepted the invite.

**Comment by Utkarsh-Mishra-CIC** [comment]
how you need those indentations to be changed? they are already at a tab shift

**Comment by newbazz** [comment]
@Utkarsh-Mishra-CIC look st some other bears ;P

**Comment by Utkarsh-Mishra-CIC** [comment]
Please review the PR [here](https://github.com/coala/coala-bears/pull/2254)
