### ISSUE TITLE
DockerfileLintBear: Improve docstring

### ISSUE THREAD

**Issue by manankalra** [coala/coala-bears#2259]
https://github.com/projectatomic/dockerfile_lint/blob/master/README.md#dockerfile-lint

**Comment by Makman2** [comment]
What do you want to exactly improve?

Note: Copying texts from other sources needs to be checked for license issues^^

**Comment by manankalra** [comment]
- Check -> Checks
- semantic -> semantics/semantic attributes
- it (after the first sentence) should have capitalized I.
- Mentioned link in the docstring can be added under the metadata attribute `SEE_MORE`.

Yeah, the link is just for reference. Btw, the content of the docstring is already copied from the same source. Also, it's MIT licensed. :)

**Comment by Makman2** [comment]
`SEE_MORE` usually contains the official link to the tool, and is not so precise like pointing to a documentation. I think we should follow that convention instead of adding this link to the readme.

**Comment by manankalra** [comment]
> Mentioned link in the docstring can be added under the metadata attribute `SEE_MORE`.

By this, I meant the link which is already specified in the docstring of the DockerfileLintBear should be added to `SEE_MORE`. Yes, it's the official link to the tool wrapped for this linter bear. :)

**Comment by Crphang** [comment]
Can I be assigned to work on this? Really hope to get started on contributing!

**Comment by newbazz** [comment]
@Makman2
