### ISSUE TITLE
Add query to prompt the user for docstyle used for documenting code in the DocumentationStyleBear

### ISSUE THREAD

**Issue by kriti21** [coala/coala-bears#2275]

**Comment by Makman2** [comment]
The user is prompted when the setting is missing.

I guess this goes into the direction of https://github.com/coala/coala-bears/issues/2273 ;)

**Comment by kriti21** [comment]
Should I close this one then? That one needs to be opened in the `coala/coala` repo while this still needs change in DocumentationStyleBear i think.

**Comment by kriti21** [comment]
Should I close this one in that case ? @Makman2

**Comment by Makman2** [comment]
No let's keep it open as a reminder. Let's decide once #2273 is settled :+1:

**Comment by Makman2** [comment]
Blocked by https://github.com/coala/coala-bears/issues/2273

**Comment by jayvdb** [comment]
I dont think it is ever appropriate for a bear to be prompting a user.

I've added some thoughts at https://github.com/coala/coala-bears/issues/2273#issuecomment-381879170
