### ISSUE TITLE
Add bear to support Mercurial version control system 

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2286]
> coala currently supports only git vcs. It would be good to include mercurial as well.

From https://github.com/coala/coala/issues/5185

**Comment by virresh** [comment]
Hello @Makman2 , I would like to get started with writing a bear with this.
I couldn't find an existing linter for Mercurial, so I suppose we need to write a native bear for this ?

**Comment by Makman2** [comment]
Yes
