### ISSUE TITLE
DockerfileLintBear: Add SEE_MORE attribute

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2287]
Separated from https://github.com/coala/coala-bears/issues/2259:

> Mentioned link in the docstring can be added under the metadata attribute SEE_MORE.

The mentioned link is https://github.com/projectatomic/dockerfile_lint#dockerfile-lint

**Comment by siddharthkv7** [comment]
Hello. I would like to work on this issue. It would be great if it could be assigned to me.

**Comment by harshhx17** [comment]
Hii, Can this issue be please assigned to me
