### ISSUE TITLE
Master Branch Broken: Travis-CI fails due to wrong artistic_style download

### ISSUE THREAD

**Issue by nvzard** [coala/coala-bears#2302]
currently, we download astyle_3.0.1.tar.gz from
```
https://downloads.sourceforge.net/project/astyle/astyle/astyle%203.0.1/astyle_3.0.1_linux.tar.gz?r=&ts=1499017588&use_mirror=excellmedia
```
which redirects to some other url which downloads a [text/html] file. 
That's why we get the below error 
```
+tar -xvzf /home/travis/astyle.tar.gz -C /home/travis/
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Ref: https://stackoverflow.com/a/46715748/7384392
https://travis-ci.org/coala/coala-bears/jobs/348557001
https://prnt.sc/im7w0w

importance/critical

**Comment by nvzard** [comment]
@Makman2 Sorry I've already made a PR, please assign this issue to me. 
Though both the builds are passing, CircleCI is failing due to `DockerfileLintBearDefaultRuleTest` which is not related to the changes I've made, can you please look into this ;)

**Comment by jayvdb** [comment]
This problem appears to have fixed itself.

**Comment by jayvdb** [comment]
it occurred again today https://travis-ci.org/coala/coala-bears/jobs/351269016

**Comment by jayvdb** [comment]
A much better approach is to use a packaged astyle .   http://build.openSUSE.org can build debian images . PPAs are another approach

**Comment by nvzard** [comment]
https://software.opensuse.org/package/astyle

I don't have much idea about this
>A much better approach is to use a packaged astyle . http://build.openSUSE.org can build debian images . PPAs are another approach

**Comment by jayvdb** [comment]
Another two broken builds today because of this.

@nvzard, either figure it out, or get unassigned so someone else can work on it

**Comment by jayvdb** [comment]
openSUSE Leap 42.3 is using 3.0.1.
tumbleweed is still on 2.05.1.
so we need to try to branch from the openSUSE Leap 42.3 rpm spec.

**Comment by jayvdb** [comment]
@giovanism , you might be interested in this .. ;-)

**Comment by nvzard** [comment]
@jayvdb you can unassign me, I won't be able to devote time to fix this at the moment.

**Comment by giovanism** [comment]
@jayvdb sure that obs can build deb package, but that means we have to maintain it ourselves. Is there a reason why we can't use PPA in the existing deps.apt.sh?

**Comment by jayvdb** [comment]
PPAs are one of the options (see https://github.com/coala/coala-bears/issues/2302#issuecomment-372083059), and quite possibly the easiest option for the Travis problem which uses Ubuntu.

OBS can build debs, and you are right it means maintaining it ourselves, but usually that will mean incrementing the version every year, a debugging a complex dependency problem every second year.

However we also need openSUSE rpms for our Docker, so that means we're already implicitly using OBS anyway, or explicitly if we want versions not yet in the latest openSUSE distros.
