### ISSUE TITLE
DockerfileLintBear: Tests broken with 0.3.0

### ISSUE THREAD

**Issue by manankalra** [coala/coala-bears#2309]
CircleCI builds are failing due to `DockerfileLintBearDefaultRuleTest`. 
It might be because of the recent changes made to https://github.com/projectatomic/dockerfile_lint.  
Update the test files according to the deprecations made. Also, update the linter version suitably. (i.e. to the version that makes use of the test files in the recently updated way)

**Comment by manankalra** [comment]
@Makman2 Assign it to me. ;)

**Comment by jayvdb** [comment]
Updating everything isnt the right solution.  First we need to pin our dependency versions to avoid the broken upstream version.

**Comment by jayvdb** [comment]
I've just run a [fresh build of master](https://travis-ci.org/coala/coala-bears/builds/351169635), and it is passing.
