### ISSUE TITLE
DockerfileLintBear: modify bear as per dockerfile_lint 0.3.0

### ISSUE THREAD

**Issue by nvzard** [coala/coala-bears#2313]
The output of dockerfile_lint v0.3.0 differs from the output of dockerfile_lint v0.2.7.

dockerfile_lint deprecated `MAINTAINER` instruction

v0.3.0 has an addition `Analyzing {file_name}` string added at the beginning of the JSON object.

Output( dockerfile_lint <= v0.2.7)
```
Check Passed!
```

Output( dockerfile_lint = v0.3.0)
```
Analyzing {file_name}

Check Passed!
```

**Comment by nvzard** [comment]
I'm already working on this issue. Please assign @Makman2

**Comment by nvzard** [comment]
'@linter` returns inconsistent output, opened an issue https://github.com/projectatomic/dockerfile_lint/issues/97

**Comment by nvzard** [comment]
They fixed the issue, the latest `dockerfile_lint` release is not 0.3.1, We just need to modify the tests handle the deprecated `MAINTAINER` instruction.

**Comment by jayvdb** [comment]
Dup of https://github.com/coala/coala-bears/issues/2309

**Comment by Makman2** [comment]
Is this really a dupe @jayvdb ? The purpose of this issue is to actually upgrade the bear dependency to the latest version.

**Comment by jayvdb** [comment]
Well it was a dup at the time, as we had many people trying to solve the same CI breakage on different issues and in different ways, and none of those solutions were particularly useful as the core of the problem was mostly fixed upstream.
