### ISSUE TITLE
CSSAutoPrefixBear: Tests break for  8.0.0

### ISSUE THREAD

**Issue by nvzard** [coala/coala-bears#2315]
Make CSSAutoPrefixBear support the latest version by adapting tests.

**Comment by jayvdb** [comment]
I believe the problems are fixed in 8.1.0 .

> Make CSSAutoPrefixBear support the latest version by adapting tests.

Issues should describe the problem, so you should include *details* of the test breakage.

Then do analysis.

Dont jump straight to the solution.
