### ISSUE TITLE
CSSAutoPrefixBear: Pin autoprefixer as 8.0.0 is breaking the tests

### ISSUE THREAD

**Issue by nvzard** [coala/coala-bears#2318]

**Comment by jayvdb** [comment]
I believe the problem is fixed in 8.1.0

**Comment by jayvdb** [comment]
Dup of https://github.com/coala/coala-bears/issues/2315

**Comment by nvzard** [comment]
I opened the issue in respect of my commit to just pin the autoprefixer to fix masterbranch, https://github.com/coala/coala-bears/issues/2315 is to adapt the tests as per the latest version.
No issues if this is not correct

**Comment by jayvdb** [comment]
#2315 is mostly about the breakage; analysis hasnt been done yet, so no need for lots of different issues about the same thing.
