### ISSUE TITLE
.ci npm install does not show the versions used

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2319]
When looking at a Travis log of bears, there is no summary of the versions used for the npm modules.

**Comment by jayvdb** [comment]
We only really want to see versions of the direct dependencies.

Dumping unnecessary junk into the logs is the subject of a different bug : https://github.com/coala/coala-bears/issues/1123

**Comment by nvzard** [comment]
I suggest after npm deps are installed we use `npm list [dep_name]` to print the installed version.

We need to parse the package.json file and for that we can use `jq` https://stedolan.github.io/jq/
and the pipe the results into `npm list` one by one for each package.

**Comment by jayvdb** [comment]
that will invoke Node many times, slowing down our CI unnecessarily.  needs to be done in a single command.

**Comment by nvzard** [comment]
@jayvdb lol sorry, we can just use `npm list -g --depth=0`
