### ISSUE TITLE
Add isort bear

### ISSUE THREAD

**Issue by palash25** [coala/coala-bears#2339]
isort is a nice tool to sort imports in python files. We should have this integrated with coala. If a linter bear integration is not possible then maybe we can write a native bear

https://github.com/timothycrosley/isort#readme

**Comment by palash25** [comment]
area/ci label should be removed.
Btw whats wrong with @gitmate-bot ?

**Comment by ajeetdsouza** [comment]
Could I work on this, please? :)

**Comment by palash25** [comment]
Sure go ahead @ajeetdsouza since you have already commented a maintainer will assign you as soon as possible. Meanwhile you can start working on this. If still not assigned for more than a day then ask on gitter for assignment.

**Comment by ajeetdsouza** [comment]
Doesn't [this](https://github.com/coala/coala-bears/blob/master/bears/python/PyImportSortBear.py) already do this, though?

**Comment by Makman2** [comment]
isort is a different tool, I guess we want to have it too :+1:

**Comment by ajeetdsouza** [comment]
I think this bear already uses the isort tool:
https://github.com/coala/coala-bears/blob/master/bears/python/PyImportSortBear.py
They're using the SortImports class from https://github.com/timothycrosley/isort/blob/develop/isort/isort.py

**Comment by Makman2** [comment]
Oh indeed, I always thought `PyImportSort` is an own tool :sweat_smile: Thanks for clarifying.
