### ISSUE TITLE
Travis Failing due to version conflicts raised by setup tools 

### ISSUE THREAD

**Issue by virresh** [coala/coala-bears#2361]
Ref:  https://travis-ci.org/coala/coala-bears/jobs/354914979#L1828

Setup tools is raising a version conflict on python 3.3
```pkg_resources.VersionConflict: (setuptools 18.0.1 (/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages), Requirement.parse('setuptools>=27.3'))```
Needs more investigation

Also could be related to the same:
https://travis-ci.org/coala/coala-bears/jobs/354914979#L1382
^PyYAML's installation failure

Complete log:
https://pastebin.com/UMZUfqvz

PyLint line -> 1828
PyYAML line -> 1382

**Comment by jayvdb** [comment]
pylint recently released a new version, but the setuptools dependency isnt in [there](https://github.com/PyCQA/pylint/blob/master/pylint/__pkginfo__.py#L29)

**Comment by jayvdb** [comment]
Problem is due to https://github.com/pytest-dev/pytest-runner/issues/40
