### ISSUE TITLE
PrettierLintBear regex is incorrect

### ISSUE THREAD

**Issue by anctartica** [coala/coala-bears#2365]
The output of the prettierLintBear to stderr stream on syntax error for the input `function b(){` is:
`[error] ../../../../var/folders/x6/p95tfncj57q1lzsbbm02599xmts4q9/T/tmphekpuu5k: SyntaxError: Unexpected token (2:1)\n[error]   1 | function b(){\n[error] > 2 | \n[error]     | ^\n`.

This does not match `r'L(?P<line>\d+)C(?P<column>\d+): (?P<message>.*)'` the regex that is included inside the bear for stderr

**Comment by MacBox7** [comment]
Could you provide the input to recreate the problem?

**Comment by anctartica** [comment]
Can you assign this to me @jayvdb

**Comment by newbazz** [comment]
@anctartica are you still on this?

**Comment by jayvdb** [comment]
cc @Nshul

**Comment by anctartica** [comment]
yes working will make a PR today

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/issues/2421 is semi-related

**Comment by anctartica** [comment]
When the PrettierBear was written not many tests were added. I later added the tests #2341 so, it is possible that this could have slipped. The format for the syntax error message produced by prettier is here: https://github.com/prettier/prettier/blob/master/src/common/parser-create-error.js which does not match the previous regex.

**Comment by Nshul** [comment]
Apologies for my late response.
When PrettierBear was written not much tests were added. I am really sorry that the regex is incorrect, I took the idea of regex by looking at the official tutorial by coala and the other linter bears, it seemed fine on the tests i conducted.
i think i did miss the link @anctartica has sent from the official prettier repo.

**Comment by jayvdb** [comment]
Thanks for letting us know.
