### ISSUE TITLE
PySafetyBear: Add asciinema 

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala-bears#2371]
Content of file on Bear will perform it's action also have to shown in asciinema.

difficulty/newcomer

**Comment by rlemasquerier** [comment]
Hello, could I get assigned please ?

**Comment by Ghaliger** [comment]
@RaiVaibhav and iam new to this and excited to work on the issue. could you please assign me? iam also requesting for further description to get me started.

**Comment by Ghaliger** [comment]
hello. tried to give this a go while waiting on an assignment, but in the process of trying to build my asciinemer, it reveals that asciicinema doesn't work out of the box on Windows. On my Win10 machine It fails with ImportError: No module named termios. iam going to install linux and try again. or is there another way?

**Comment by Makman2** [comment]
Seems like, `termios` is Unix-only. But should work also pretty well from a Linux VM.

**Comment by jayvdb** [comment]
Reassigned to @rlemasquerier , as the PR wasnt creating the asciinema for PySafetyBear at all.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [5109379524198400](https://codein.withgoogle.com/dashboard/tasks/5109379524198400).

**Comment by arnav-mandal1234** [comment]
Can I take this issue?@jayvdb  @Makman2 @RaiVaibhav
It would be great if I get some insight on how to fix this bug.
