### ISSUE TITLE
RuboCop cannot always find it's config file if it's specified

### ISSUE THREAD

**Issue by cbaines** [coala/coala-bears#2373]
If the rubocop config file is specified with a relative path, e.g. [1], then this means that coala must be run in a working directory such that the configuration file exists at this relative path. This breaks things like the Emacs Flycheck integration, which runs coala not always in the directory where the .coafile exists.

1:
```
rubocop_config = .rubocop.yml
```

I'm not sure if this is something that can be fixed, or how to do it. Is there someway to specifying a path in the `.coafile` as relative to the `.coafile` itself, or can the RuboCopBear determine the correct path at runtime, ... It would at least be good to have the RuboCopBear check the config file exists before trying to run rubocop.

**Comment by Makman2** [comment]
I think this is fixable. coala provides bears with a `path` settings-type. This type could actually expand the path intelligently (using the .coafile path) conforming your situation.

**Comment by Makman2** [comment]
I believe we should migrate this to `coala/coala` as this affects all bears :)

**Comment by Makman2** [comment]
Migrated to https://github.com/coala/coala/issues/5305
