### ISSUE TITLE
Fix invalid language setting

### ISSUE THREAD

**Issue by rohanrk** [coala/coala-bears#2376]
```
[WARNING][12:02:47] Section `todos` contain invalid language setting: 'Language `python3` 
is not a valid language name or not recognized by coala.'
```

Should change the .coafile to suppress this warning

difficulty/newcomer

**Comment by engrravijain** [comment]
i would like to work on this
can this be assigned to me

**Comment by jayvdb** [comment]
which `.coafile`?  The one in this repo?

Is this appearing in a build log?  If so, provide a link.

Why is this happening?

We cant assign to newcomers unless we know the cause of the problem, and know the solution is trivial.

**Comment by rohanrk** [comment]
I was referring to the .coafile in this repo. 

```language = python3``` 

in section [all.TODOS] is causing this error

**Comment by jayvdb** [comment]
Actually I suspect #1635 is a different problem.

**Comment by rohanrk** [comment]
Perhaps it's related to https://github.com/coala/coala/issues/4690?

**Comment by jayvdb** [comment]
Ya, that is probably closer to the problem.

**Comment by rohanrk** [comment]
coala recognizes python 3 as a valid language. This issue has been fixed.
