### ISSUE TITLE
InvalidLinkBear: Unable to detect valid link

### ISSUE THREAD

**Issue by rohanrk** [coala/coala-bears#2377]
https://msdn.microsoft.com/en-us/commandline/wsl/install-win10 is a valid link but InvalidLinkBear states that it is broken

ref: https://gitlab.com/rohanrk/documentation/-/jobs/59445738

**Comment by MacBox7** [comment]
Unable to recreate the issue. InvalidLinkBear works as expected. The link you mention has been permanently moved and if you set `follow_redirects=True`, it even provides with a correct redirect otherwise it quietly ignores the message.

**Comment by Makman2** [comment]
Sounds like it's invalid then.

@rohanrk feel free to reopen if you doubt :) Please try it also on most recent master in case you haven't done yet :+1:
