### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by sangamcse** [coala/coala-bears#2383]
package-lock.json is a lock file of JS dependencies.

difficulty/new comer

**Comment by mayokunthefirst** [comment]
@sangamcse can I be assigned to this please?

**Comment by sangamcse** [comment]
@mayokunthefirst, Since this issue is newcomer issue and you have completed one newcomer issue, you can not work on this. And from next time, don't open PR without getting assigned.

**Comment by MacBox7** [comment]
`.pytest_cache/` and `.vscode/` can also be added.

**Comment by Makman2** [comment]
@MacBox7 Please file new issues for them, so we can fill our backlog for newcomers :)

**Comment by binore** [comment]
@sangamcse Can I be assigned to this? I need to finish newcomer process

**Comment by Makman2** [comment]
It should be definitely committed, opened https://github.com/coala/coala-bears/issues/2508 to revert this commit again.
