### ISSUE TITLE
Refactor issue Regexes in GitCommitBear

### ISSUE THREAD

**Issue by virresh** [coala/coala-bears#2396]
The issue regex for matching hosts can be done away with a class variable which will support better modularity
(refer [here](https://github.com/coala/coala-bears/pull/2310#pullrequestreview-106719986))

I would prefer to work on this 

(difficulty/low)

**Comment by Makman2** [comment]
I'm not sure if it's that profitable, that would be rather a performance optimization, and I think it's really negligible.
You only save a variable assignment here, the way more expensive regex compilation is not affected.

**Comment by virresh** [comment]
I agree with the performance optimization not being profitable, although I just want to delegate the task of choosing the regex to another function and place that function in place of result info, so that the rest of the issue_reference function gets rid of dependency on host-specific hardcoded regexes, and it would be a bit easy to extend them to another VCS bear (specifically the HgCommitBear), something like [this](https://github.com/virresh/coala-bears/blob/a5af46834d62ede5c6d7622551bd6cffc188a39b/bears/vcs/git/GitCommitBear.py#L57)
and then the parent would simply call this function

**Comment by Makman2** [comment]
Alright, sounds like a plan then :)

**Comment by jayvdb** [comment]
It looks like this issue is going to overlap or lead towards https://github.com/coala/coala-bears/issues/1134
