### ISSUE TITLE
.coafile: Replace default section with all

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2397]
Since **Default** section is deprecated, it should be replaced with **all**.
Many people might take `.coafile` of coala as a reference for their project, so IMO it should be updated.

**Comment by MacBox7** [comment]
Yup. Go ahead.

**Comment by rammanoj** [comment]
Thanks @MacBox7 created a PR at https://github.com/coala/coala-bears/pull/2400 can you review it?

**Comment by rammanoj** [comment]
I am sorry to make a new patch instead of amending to the current patch. There are some issues locally with my git. In the current patch, I made the other sections inherit the current section. Can you review it now @MacBox7 ?

**Comment by rammanoj** [comment]
@MacBox7 present patch passed all the test cases, are there any other changes to be made?
