### ISSUE TITLE
Exclude pip 9.0.2 specifically from test-requirements

### ISSUE THREAD

**Issue by virresh** [coala/coala-bears#2404]
Due to a recent pip update to 9.0.3 that reverts the changes brought in pip 9.0.2, we should ideally just bar pip 9.0.2 and allow other versions [here](https://github.com/coala/coala-bears/blob/master/test-requirements.txt#L4)

Relevant links : 
https://github.com/coala/coala-bears/issues/2359
https://github.com/pypa/pip/issues/5081#issuecomment-375150007

**Comment by jayvdb** [comment]
And also prevent use of pip 10.0, but allow pip 10.1 , basically preparing for 10.0 being quite disruptive, but the problems will sort themselves out by 10.1

**Comment by aadilmehdis** [comment]
Hi, I'd like to work on this issue, but am not sure where to get started.

**Comment by virresh** [comment]
Hello @aadilmehdis 
You need to modify [this](https://github.com/coala/coala-bears/blob/38532090bc56979d2cafc8841f8050e35feb166a/test-requirements.txt#L4) line appropriately for the purpose of this issue.

If you would like an insight into what the actual problem is, consider reading the related links in the description

Also probably [requirements specifiers](https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers) might be useful for this issue

Head over to the [gitter channel](https://gitter.im/coala/coala-bears) if you feel stuck

**Comment by aadilmehdis** [comment]
What versions of pip are to be excluded @virresh.
From the comments, I understand that the version 9.0.2 and 10.0 are to be specifically excluded.

**Comment by virresh** [comment]
@aadilmehdis 
Yes, we need to specifically exclude version 9.0.2 and 10.0

**Comment by aadilmehdis** [comment]
@virresh 
Hey, so making this change in the line would be okay?
pip<=9.0.3 , != 9.0.2, != 10.0.*

**Comment by virresh** [comment]
Why would you use <= 9.0.3 ?
I think the two latter specifiers should suffice.

**Comment by aadilmehdis** [comment]
Okay. Now to push in the changes, I just commit the changes and push my development branch and create a pull request right?
