### ISSUE TITLE
PEP8Bear: Change the docstring indentation.

### ISSUE THREAD

**Issue by newbazz** [coala/coala-bears#2437]
difficulty/newcomer

**Comment by RachaelNantale** [comment]
Can I take up this issue?
Could someone please assign me this

**Comment by RachaelNantale** [comment]
@newbazz @palash25 in which file should i make the indentation changes?

**Comment by newbazz** [comment]
The file name is written in the issue heading `PEP8Bear.py`

**Comment by palash25** [comment]
@RachaelNantale make a PR and stop worrying about assignment

**Comment by vaibhav9619** [comment]
Assign me the issue

**Comment by jayvdb** [comment]
I've assigned you to this issue.  Please do it first.

**Comment by ANURADHAJHA99** [comment]
can you assign me this issue?

**Comment by anshulahuja98** [comment]
Can this issue be assigned to me, the previous assignee looks inactive...

**Comment by AkshJain99** [comment]
I find this issue interesting to solve,
Please assign this issue to me I would like to work in it

**Comment by AkshJain99** [comment]
Anyone please review this PR

**Comment by jayvdb** [comment]
This issue doesnt say what the indentation should be like.

Implied in this issue: the indentation should be the same indentation that is commonly used in docstrings in the coala and coala-bears repos.

So, ...

What is the style of the docstrings in the coala and coala-bears repos?

What is the *name* of that style?

We have learnt at https://github.com/coala/coala-bears/pull/2701 that this style is not PEP8, and it isnt PEP257.

What is it?

If you dont know the indentation style being requested, it isnt possible to know if the change is correct.

**Comment by AkshJain99** [comment]
Ohhh okay so that means I need to find what indentation style coala use??
Is it?

**Comment by jayvdb** [comment]
Yes.

**Comment by AkshJain99** [comment]
Okay👍

**Comment by AkshJain99** [comment]
@jayvdb as you said that i need to find the docstring stye coala repo use ,but as I have read there is only PEP257 which deals with docstring convention

**Comment by sks444** [comment]
>This issue doesnt say what the indentation should be like.

@jayvdb, a similar [issue](https://github.com/coala/coala-bears/issues/2243) created by @newbazz  was solved in https://github.com/coala/coala-bears/pull/2254. Maybe we could get some idea from there.

**Comment by jayvdb** [comment]
I dont need an idea about the docstring style.  I know the answer :P  This issue is not assigned to me.

We have lots and lots of information about these docstring styles in coala and coala-bears repos.

And there is lots of information about docstring styles on the internet.
