### ISSUE TITLE
PEP8NoteBear: Add infinite line length feature

### ISSUE THREAD

**Issue by newbazz** [coala/coala-bears#2443]
allow infinite line length when max_line_length is set to 0.
difficulty/low

**Comment by jayvdb** [comment]
This is needed for consistency with other bears.
@newbazz can you add a link to some PRs where this has been done, so the developer can easily see what is required.

**Comment by newbazz** [comment]
Some PRs for referal https://github.com/coala/coala-bears/pull/2255 , https://github.com/coala/coala-bears/pull/2440 .

**Comment by rishabhgarg25699** [comment]
@jayvdb Please assign this issue to me.

**Comment by rishabhgarg25699** [comment]
I am working on this issue , So please no one work on it

**Comment by bkhanale** [comment]
I can fix this, @jayvdb
