### ISSUE TITLE
Allow extra information in bear-requirements.yaml

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2444]
`.ci/generate_bear_requirements.py` currently overwrites `bear-requirements.yaml`, removing any information that was in it.

It should load the yaml, and have

- an `--update` mode which modifies only the information which needs to be modified. This can be achieved using https://pypi.org/project/ruamel.yaml/ 's RoundTrip functionality.

- a `--check` mode which reports any differences in a helpful way, tells the user to run in `--update` mode and commit and re-push, with a non-zero exit status when differences were found.

In travis, we would `--check` *and* `--update`, so that any yaml output differences will be caught by `git diff --exit-code` even if `--check` doesnt report dependency differences.

To test this, `overrides: coala-build.yaml` should be moved to the top of `bear-requirements.yaml`, and a comment added at the top of the file, and travis shouldnt report any differences.

**Comment by nemaniarjun** [comment]
I don't understand the `RoundTrip Functionality` and cant find any documentation/explanation of what it does exactly.

**Comment by nemaniarjun** [comment]
Nevermind, understood the first part of the description :)

**Comment by nemaniarjun** [comment]
I will be sending in the PR soon, testing it on my branch travis takes too long as the build takes 2 hours :(

**Comment by jayvdb** [comment]
ya, you need to test these things locally, and then hope for the best with the PR.
But use the travis cron triggers (in settings) to do a build of master (weekly) on your fork, as that will prime your forks cache so your branches can use the master cache.

**Comment by nemaniarjun** [comment]
The extra information will not be a part of the requirements right?

```
extra info:
  ...
npm_requirements:
  ...
gem_requirements:
  csvlint: true
  ...
``

I mean both the update and check need to be shallow or deep?
