### ISSUE TITLE
CIRCLE_NODE_INDEX hack for travis is not required anymore

### ISSUE THREAD

**Issue by harshhx17** [coala/coala-bears#2453]
`.travis.yml` sets `CIRCLE_NODE_INDEX=-1` to avoid being a circle worker
Remove code related to this hack as pip deps are no more called from travis

**Comment by harshhx17** [comment]
@jayvdb 
This can be solved before going to circle 2
Please assign me :wink:

**Comment by dhruv10** [comment]
I want to work on this issue. Also, I need elaboration as I'm a newbie.

**Comment by ayushagg31** [comment]
@jayvdb  assign this to me.

**Comment by harshhx17** [comment]
@phoenixking25 
Yess

**Comment by phoenixking25** [comment]
Please assign me this issue @harshhx17

**Comment by harshhx17** [comment]
@jayvdb ^
