### ISSUE TITLE
URLBear: Redundent settings

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2456]
Currently, URLBear uses link_ignore_list and link_ignore_regex to enumerate for the links to be ignored. IMO it could be replaced with one parameter that could primarily be a `list of regex` so that it performs both the functions provided by link_ignore_list and link_ignore_regex.
Needs discussion
CC @Makman2  @jayvdb 
Refer: https://github.com/coala/coala-bears/issues/2128

**Comment by jayvdb** [comment]
regex are not user friendly.
See other issues about these params to see existing plans.
