### ISSUE TITLE
GitCommitBear: Fix regex for issue id

### ISSUE THREAD

**Issue by ksdme** [coala/coala-bears#2469]
1) The regex for issue id supports referencing such as ```some/sample#12``` but does not use proper validation pattern for username and repo name instead uses a ```\w```. This should be fixed to use host specific patterns.

2) The reference number should be an integer for both the hosts, thus ```#(\S+)``` should not be used.

**Comment by ksdme** [comment]
Refer https://github.com/coala/coala-bears/issues/2468

**Comment by jayvdb** [comment]
> validation pattern for username and repo name

This should be done in https://github.com/coala/coala-bears/issues/2468

**Comment by ksdme** [comment]
Since the changes need to be made both in the issue and full issue regex patterns, should I merge both the issues into one?

**Comment by jayvdb** [comment]
no, see title of each issue.  They are two different issues, about different types of problems, with different complexities.  This one is the easiest.

fwiw, 'issue' and 'full issue' wasnt a suitable way to split the bugs.  The two problems affect both 'issue' and 'full issue'
