### ISSUE TITLE
generate_bear_requirements.py is very noisy

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2480]
`.ci/generate_bear_requirements.py` emits a lot of junk to the console, which is especially annoying for CI logs.

This might require some improvements upstream in coala.

**Comment by alirizwi** [comment]
@jayvdb I want to work on this issue. Could you please guide me. Thanks!

**Comment by alirizwi** [comment]
@jayvdb What do you exactly refer by junk. the print and assert statements?

**Comment by frextrite** [comment]
What junk are you referring to?

According to this [Travis log](https://travis-ci.org/coala/coala-bears/jobs/468660495#L7088), line [7088](https://travis-ci.org/coala/coala-bears/jobs/468660495#L7088), no print statements have been emitted by ```.ci/generate_bear_requirements.py```

**Comment by jayvdb** [comment]
I think this was improved last year as part of other tasks.  Find a merged PR from around the date of this issue , and see Travis logs of that PR.  very messy.
