### ISSUE TITLE
Provide option for comparison clauses in moban

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2505]
`bear-requirements.yaml` should have an option for comparison clauses like `==`, `>=`, `~=`, etc for python packages. After this `bear-requirements.txt.jj2` should be updated accordingly.

The current implementation is simply appending package with the version number.
For example generated requirement for pyflakes would be of the form =>
`pyflakes1.5.0` rather than `pyflakes~=1.5.0`

**Comment by jayvdb** [comment]
Which comparision type do you want?

Long term the comparison type needs to be understood by the Requirement class, but an interim hack is maybe ok.

**Comment by MacBox7** [comment]
The current practice looks good.
