### ISSUE TITLE
Update URL in CPDBear (copy/paste detector) docs

### ISSUE THREAD

**Issue by nemaniarjun** [coala/coala-bears#2518]
Old Url: https://pmd.github.io/pmd-5.4.1/usage/cpd-usage.html
New Url: https://pmd.github.io/pmd-6.4.0/pmd_userdocs_cpd.html

Diff: Newcomer
Importance: Low

**Comment by jayvdb** [comment]
@Hrithik19, please accept the org invite so we can merge your PR.

**Comment by Hrithik19** [comment]
@jayvdb Accepted
