### ISSUE TITLE
golint install error

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2534]
```
+go get -u github.com/golang/lint/golint
# golang.org/x/tools/go/internal/gcimporter
../../../gopath/src/golang.org/x/tools/go/internal/gcimporter/bimport.go:541: undefined: types.NewInterface2
../../../gopath/src/golang.org/x/tools/go/internal/gcimporter/iimport.go:540: undefined: types.NewInterface2
```
https://travis-ci.org/coala/coala-bears/jobs/391802261

**Comment by yukiisbored** [comment]
Sigh, why can't go use proper versioning like everyone else.

Can we vendor this to known last working version?

**Comment by yukiisbored** [comment]
Okay, it seems the official documentation states.

`go get -u golang.org/x/lint/golint`.

**Comment by yzgyyang** [comment]
We definitely should pin a commit for every Go dependencies IMO.

**Comment by jayvdb** [comment]
@yukiisbored , GitHub says it is a mirror, but I am not sure about that as development seems to be occurring at https://github.com/golang/lint/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc.

The source code hasnt changed in either https://github.com/golang/lint or golang.org/x/lint/golint for a long time --  https://golang.org/x/lint/golint redirects to gopkg pages which link back to GitHub source code.  `$ diff -r golang.org/x/lint/ github.com/golang/lint/` yields nothing; they have the same `HEAD`.

The problem is we are using an unsupported version of go in our CI.
golint depends on core libraries.  Those core libraries are breaking on unsupported versions of go.

We would need to pin all dependencies, not just our own direct dependencies.
There are package managers which can do this.  We need to use one, or upgrade our go version on the CI environments.
