### ISSUE TITLE
CPPLintBear violated one-based offset convention

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2562]
https://ci.appveyor.com/project/jayvdb/coala-bears/build/job/xhu5jueyyennp1u3#L678

**Comment by li-boxuan** [comment]
They use 0-based line number. 
See https://github.com/cpplint/cpplint/blob/master/cpplint.py#L1383 
```python
def Error(filename, linenum, category, confidence, message):
```

and https://github.com/cpplint/cpplint/blob/master/cpplint.py#L2133-L2135
```python
  for linenum, line in enumerate(lines):
    if unicode_escape_decode('\ufffd') in line:
      error(filename, linenum, 'readability/utf8', 5,
            'Line contains invalid UTF-8 (or Unicode replacement character).')
```
