### ISSUE TITLE
ClangBear.py: Rename variable range

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2585]
`range` is a python builtin and shouldn't be redefined. Rename occurrences at [1](https://github.com/coala/coala-bears/blob/master/bears/c_languages/ClangBear.py#L55) and [2](https://github.com/coala/coala-bears/blob/master/bears/c_languages/ClangBear.py#L103).

Difficulty: Newcomer

**Comment by kUSHAL0601** [comment]
I would like to work on this for a start.

**Comment by MacBox7** [comment]
Leave a comment on the group to get assigned.

**Comment by sinscary** [comment]
@MacBox7  Can i take this up?

**Comment by MorTD** [comment]
Hello

Is this issue available?

**Comment by MacBox7** [comment]
Yes. Ask for assignment on coala chat.

**Comment by jayvdb** [comment]
PR closed and issue unassigned because you've not been following the guideline or reading the bot messages.

**Comment by AKG001** [comment]
Hey, can i work on this issue?

**Comment by ANURADHAJHA99** [comment]
can you please assign  this issue to me?

**Comment by MacBox7** [comment]
Ask on group chat please

**Comment by jayvdb** [comment]
Assigned to @Karna98 as they have already accepted the invite to join @coala

**Comment by Karna98** [comment]
@jayvdb Since the issue states that the defined variable 'range' is coinciding with per-defined variable in python 'range'. So after changing the variable_name how to check whether is it working or not?. Do I have to the whole project in my system?
