### ISSUE TITLE
TextLintBearTest.test_bad_alex_no_dead_link uses http://httpstat.us/404 which is 503

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2588]
`tests/general/textlint_test_files/bad_alex_no_dead_link.md` contains a link to http://httpstat.us/404 , and `tests/general/TextLintBearTest.py` expects textlink to report `(404 Not Found)` , but http://httpstat.us/404 is reporting 404

Use http://httpbin.org/status/404 instead

**Comment by kriti21** [comment]
Please assign this to me.

**Comment by jayvdb** [comment]
Transient problem; disappeared.

**Comment by jayvdb** [comment]
Problem re-appeared at https://github.com/coala/coala/issues/5628 .

Lets use httpbin.org everywhere.

As then we can switch to using `pytest-httpbin` afterwards
