### ISSUE TITLE
MypyBear uses outdated version of mypy

### ISSUE THREAD

**Issue by mwolting** [coala/coala-bears#2601]
MypyBear currently depends on the package `mypy-lang~=0.4.6`. However, mypy has moved from `mypy-lang` to the `mypy` package and seen several releases since that version, and (among other things) is now fully compatible with Python 3.6. It would be helpful if the MypyBear could be migrated to the latest version to benefit from that.

**Comment by kUSHAL0601** [comment]
I would like to work on this one.

**Comment by jayvdb** [comment]
> I would like to work on this one.

No.  You need to finish you newcomer issue https://github.com/coala/coala-bears/issues/2585 first.

**Comment by sinscary** [comment]
@jayvdb Can I work on this?

**Comment by sinscary** [comment]
@jayvdb Can I take this up?

**Comment by daureg** [comment]
The version is still outdated and as a result I can't install `coala-bears` in my project:
```
[SolverProblemError]
Because no versions of coala-bears match !=0.12.0.dev99999999999999
 and coala-bears (0.12.0.dev99999999999999) depends on mypy (0.590), every version of coala-bears requires mypy (0.590).
So, because frad depends on both mypy (^0.761) and coala-bears (*), version solving failed.
```
