### ISSUE TITLE
Generate php composer dependencies

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2618]
`.ci/generate_bear_requirements.py` generates `bear-requirements.yaml` which [`moban`](https://github.com/moremoban/moban) uses to generate `package.json`, `bear-requirements.txt`, `Gemfile`, and `coala-bears.cabal`.

The same process should generate composer requirements in an format usable by php composer, using jinja2 templates.

**Comment by Dhiraj240** [comment]
@jayvdb I would like to work on this issue.Please assign it to me.

**Comment by anctartica** [comment]
Yes you should be able to use `~` operator. https://getcomposer.org/doc/articles/versions.md
Although none of the current composer requirements in bears specify a version.
