### ISSUE TITLE
Constants.py: Put VERSION inside __all__

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2623]
Put VERSION inside __all__. Run `pyflakes==2.0.0` and ensure no errors.
difficulty/newcomer

**Comment by ShashwatNigam99** [comment]
Can i be assigned this issue?
Also need a bit more elaboration on what needs to be done

**Comment by MacBox7** [comment]
Ask for assignment on coala gitter. Read about `__all__` in [here](https://stackoverflow.com/questions/44834/can-someone-explain-all-in-python). You need to place `VERSION` in `Constants.py` inside `__all__`. Install `pyflakes==2.0.0` and run it on `Constants.py` and see if any error is being generated.
