### ISSUE TITLE
Fix spelling mistake 

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala-bears#2629]
`parseable` ---> `parsable`
https://github.com/coala/coala-bears/blob/master/bears/python/requirements/PySafetyBear.py#L97

difficulty/newcommer

**Comment by prankshaw** [comment]
I will like to review this issue. Please tell me how can I achieve that

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/2299
