### ISSUE TITLE
Travis CI failing due to infer breakage with javalib

### ISSUE THREAD

**Issue by saksham189** [coala/coala-bears#2664]
Recent travis build for python 3.6 fail while trying to build infer.

```
Error: No implementations provided for the following modules:
         CamomileLibrary__UTF8 referenced from /home/travis/.opam/system/lib/javalib/javalib.cmxa(Javalib_pack)
         CamomileLibrary__UChar referenced from /home/travis/.opam/system/lib/javalib/javalib.cmxa(Javalib_pack)
         CamomileLibrary__ referenced from /home/travis/.opam/system/lib/javalib/javalib.cmxa(Javalib_pack)
Command exited with code 2.
make[2]: *** [build_java] Error 10
make[2]: Leaving directory `/home/travis/infer-linux64-v0.7.0/infer/src'
make[1]: *** [java] Error 2
make[1]: Leaving directory `/home/travis/infer-linux64-v0.7.0/infer'
make: *** [java] Error 2
  compilation failure; you can try running
    make clean
    ./build-infer.sh java
The command ".ci/deps.opam.sh" failed and exited with 1 during .
```

https://travis-ci.org/coala/coala-bears/jobs/413575180

**Comment by jayvdb** [comment]
@harshhx17, maybe you can take this one?

**Comment by harshhx17** [comment]
I will surely try🙂

**Comment by jayvdb** [comment]
This is now breaking all builds.

**Comment by jayvdb** [comment]
Unassigning due to inactivity

**Comment by li-boxuan** [comment]
infer v0.7.0 is quite old, maybe a newer version would be a free lunch

**Comment by jayvdb** [comment]
Travis doesnt support opam/ocaml.  TANSTAAFL.

Fixed in https://github.com/coala/coala-bears/pull/2910

I've created https://github.com/coala/coala-bears/issues/2931 for upgrading infer.

**Comment by jayvdb** [comment]
fwiw, https://github.com/facebook/infer/issues/325 and https://stackoverflow.com/questions/35157561/trying-and-failing-to-build-ocaml-package-javalib are where I got some of the hints on how to workaround this.  This one was very tricky.
