### ISSUE TITLE
CommitBear: Check proper use of `https` when referencing issues for GitHub

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala-bears#2683]
https://github.com/coala/coala-bears/blob/master/bears/vcs/CommitBear.py#L360 matches links and tags, e.g. `fix #123`, `fix https://github.com`

This would also pass the test `Closes http://github.com`. However, this would not trigger GitHub [autolinked reference feature](https://help.github.com/articles/autolinked-references-and-urls/). The commit message should be `Closes https://github.com` instead.

For those who are not familiar with autolinked reference feature, I did a simple experiment. I created an issue first https://github.com/li-boxuan/github-playground/issues/1

Then I create a pr, aiming to close that issue. See commit message https://github.com/li-boxuan/github-playground/pull/2/commits. However, after this pr gets merged, it doesn't close the corresponding issue automatically.

Finally, this pr https://github.com/li-boxuan/github-playground/pull/3/commits closes the corresponding issue automatically when it's merged. Check commit messages carefully to see the difference.

That means we should check proper usage of `https`, at least for GitHub. Not sure if GitLab has similar features.

**Comment by li-boxuan** [comment]
@RazvanMitrica Sounds good. This issue is reserved for GCI students though :)

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4719605319729152](https://codein.withgoogle.com/dashboard/tasks/4719605319729152).
