### ISSUE TITLE
The Language search feature on website is not working 

### ISSUE THREAD

**Issue by PrajwalM2212** [coala/coala-bears#2692]
<img width="1680" alt="screen shot 2018-09-21 at 8 59 44 am" src="https://user-images.githubusercontent.com/30733262/45858803-b5e3ce00-bd7c-11e8-9ef8-602b387eb070.png">

**Comment by AMR-KELEG** [comment]
I found that the problem is with the api: https://webservices.coala.io/list/bears
The request returns an empty json response!
I don't know whether this is a known problem with the api site or not.
