### ISSUE TITLE
PEP8NotebookBear.py: Correct the spelling mistake in docstring

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coala-bears#2703]
There is a spelling mistake at [Line 11](https://github.com/coala/coala-bears/blob/559c953e1b5787df9dddf96ece8449e50c945716/bears/python/PEP8NotebookBear.py#L11).

```
# Comments regarind Jupyter Notebooks:
```

This can be a `difficulty/newcomer` issue.

**Comment by Daronion** [comment]
I would like to be assigned to this issue.

**Comment by shivank1234** [comment]
Is this issue open?

**Comment by AditiKatiyar** [comment]
I would like to work on this issue.
