### ISSUE TITLE
Bump CheckstyleBear version

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala-bears#2711]
CheckstyleBear uses checkstyle version 6.19 https://github.com/coala/coala-bears/blob/c449f2725c220a3028373b776d17701b138ee3d3/bears/java/CheckstyleBear.py#L16

while the latest release is version 8.13 http://checkstyle.sourceforge.net/releasenotes.html

checkstyle v8.13 fixes a bug https://github.com/checkstyle/checkstyle/issues/6000. Thus, https://github.com/coala/coala-bears/commit/401fa883ffbe21b78a8a4899160592a293f3d4cd#diff-2da2a90312219c9c8a1609b340cd39c7R38 can be removed. But tests should be added to verify that.

**Comment by li-boxuan** [comment]
https://github.com/coala/coala/pull/5601 This may help to understand `remove_zero_numbers` linter bear option.

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/1675 ?

**Comment by li-boxuan** [comment]
> Duplicate of #1675 ?

Seems so, but this issue is talking about a workaround that can be removed when upgrading to checkstyle 8.13. Let me mention it in #1675 and close this issue.
