### ISSUE TITLE
Change C++ --> CPP at bears language

### ISSUE THREAD

**Issue by ayan-b** [coala/coala-bears#2715]
Following https://github.com/coala/coala/issues/5826.
Bears:
- ArtisticStyleBear
- CPPCheckBear
- CPPCleanBear
- CPPLintBear
- CSecurityBear
- ClangASTPrintBear
- ClangBear
- ClangCloneDetectionBear
- ClangComplexityBear
- ClangFunctionDifferenceBear
- GNUIndentBear
A `difficulty/newcomer` issue.

**Comment by bkhanale** [comment]
Assign me this issue please :)

**Comment by ayan-b** [comment]
Sorry, this is not up for grabs. :(

**Comment by bkhanale** [comment]
Okay, no problem. I'll take another issue. Is it kept for GCI?

**Comment by ayan-b** [comment]
The issue is yet to form properly.

**Comment by anctartica** [comment]
Could you explain why this is required?
I can't see any reason for doing so.

**Comment by anctartica** [comment]
CPP and C++ are treated as the same language in coala.
https://github.com/coala/coala/blob/master/coalib/bearlib/languages/definitions/CPP.py#L6
