### ISSUE TITLE
CommitBear: Check whether GitLab autoclose works with http as well as https

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2722]
CommitBear: Create a demo on GitLab, like @li-boxuan did at https://github.com/coala/coala-bears/issues/2683 , to prove whether autoclosing works with `http://` .

Then either fix GitLab in CommitBear, or add a comment to explain `http://` works.

**Comment by abhishalya** [comment]
@jayvdb I checked this on Gitlab and I confirm that the Gitlab behaves the same as Github.

Using `http` in the issue url won't close the issue after the PR is merged, whereas if `https` is used as the issue url in the PR, it will close the corresponding issue automatically.

These are the links where I tried this:

Issue: https://gitlab.com/abhishalya/gitlab_playground/issues/1
MR-1: https://gitlab.com/abhishalya/gitlab_playground/merge_requests/1 (http)
MR-2: https://gitlab.com/abhishalya/gitlab_playground/merge_requests/2 (https)
