### ISSUE TITLE
HgCommitBear: Make asciinema

### ISSUE THREAD

**Issue by sangamcse** [coala/coala-bears#2739]

**Comment by XLAR-8** [comment]
please @sangamcse assign this to me and please can you describe issue a little bit more .

**Comment by sangamcse** [comment]
@XLAR-8, this issue is reserved for GCI participants.

**Comment by XLAR-8** [comment]
@sangamcse yes i know.
@jayvdb assingned me to this.

**Comment by jayvdb** [comment]
It isnt reserved for GCI until it has the label. ;P

Yes, I did say @XLAR-8 should do this one.

**Comment by sangamcse** [comment]
@XLAR-8 Have a look at asciinema of [GitCommitBear](https://github.com/coala/coala-bears/blob/master/bears/vcs/git/GitCommitBear.py). This asciinema will also look same; the only thing that will change is you need to work on `mercurial` in place `git`.
IMO, create one dummy repo using `mercurial` and add `.coafile` to that. Then, add one bad commit there and run `coala`.

**Comment by XLAR-8** [comment]
@sangamcse working on it

**Comment by SerekKiri** [comment]
@XLAR-8 I see that you are assigned. Are you still working on this?

**Comment by CleverFool77** [comment]
I opened the PR before commenting here. Can you please assign this to me.
