### ISSUE TITLE
LineContinuationBear: Ignore backslashes in `from` imports inside doctest

### ISSUE THREAD

**Issue by Kiy4h** [coala/coala-bears#2806]
The bear should ignore the backslashes in `from` imports.

[Here's an example](https://github.com/coala/coala/blob/master/coalib/bearlib/languages/documentation/DocumentationComment.py#L260):

```python
"""
        >>> from coalib.bearlib.languages.documentation.DocumentationComment \
        ...     import DocumentationComment
"""
```

**Comment by rajdeepbharati** [comment]
That would mean the above code should result in
```
"""
        >>> from coalib.bearlib.languages.documentation.DocumentationComment
        >>> import DocumentationComment
"""
```
Am I right @Kiy4h ?

**Comment by Kiy4h** [comment]
@rajdeepbharati No, LineContinuationBear doesn't change codes, they are linters. This linter protests if there's a wrong line continuation method. (e.g. using a backslash) Which means, there should be an option to ignore backslashes in `from` imports inside a docstring.

**Comment by rajdeepbharati** [comment]
Okay, so do we need to modify the run() method in [LineContinuationBear.py](https://github.com/coala/coala-bears/blob/master/bears/general/LineContinuationBear.py) to add this option?

**Comment by Kiy4h** [comment]
@rajdeepbharati Yeah. You should add an if statement or something like that

**Comment by rajdeepbharati** [comment]
Please assign me this issue

**Comment by Anmolbansal1** [comment]
@jayvdb @li-boxuan Can I work on this issue?

**Comment by li-boxuan** [comment]
Assigned to @rajdeepbharati let me know if you are not going to do this

**Comment by rajdeepbharati** [comment]
I'm doing it 👍
