### ISSUE TITLE
Disable InferBear

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2816]
Due to https://github.com/coala/coala-bears/issues/2664 completely failing now, a quick workaround is to disable the opam & infer, so that travis CI doesnt try to set up the pre-reqs, and so that the coverage is still 100%

**Comment by sladyn98** [comment]
One possible way would be:
1) Remove ```opam``` under packages in the travis.yml so that i does not build.
2) Remove ```.ci/deps.opam.sh``` under before_install.
3) Remove ```- ~/infer-linux64-v$INFER_VERSION``` Under installed linters which would thereby make the path redundant.Correct me if i am wrong on this one.

**Comment by jayvdb** [comment]
That will fail the 100% coverage requirement.

**Comment by sladyn98** [comment]
Would adding them in the omit section of setup.cfg be a step in the right direction.Because then travis would not consider them for the test coverage.

**Comment by jayvdb** [comment]
setup.cfg is a generated file.

**Comment by sladyn98** [comment]
Executing Step 2 in the above comment would be one step taken in the right direction according to me.

**Comment by jayvdb** [comment]
You need to have green CI.  Otherwise we have another error.

**Comment by sladyn98** [comment]
Should I try submitting a PR and checking or should I try it locally.

**Comment by jayvdb** [comment]
You havent indicated you know how to solve the 100% coverage part of the problem mentioned as part of this issue.

**Comment by sladyn98** [comment]
Hey @jayvdb Could we try to do this ```opam reinstall -y core_kernel``` in the shell script. I googled a bit and i found this https://github.com/gfngfn/SATySFi/issues/46.
