### ISSUE TITLE
MarkdownBearTest.test_duplicate_headings failing

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2830]
MarkdownBearTest.test_duplicate_headings failing is failing because "per section" has been removed from the linter error message

**Comment by pavanrkadave** [comment]
Hi can i take up this issue? @jayvdb

**Comment by Anmolbansal1** [comment]
I want to work to this issue please assign this to me @li-boxuan

**Comment by li-boxuan** [comment]
@pavanrkadave @Anmolbansal1 Please find other issues to work on :) Obviously, this issue has an assignee with an open PR pending review.
