### ISSUE TITLE
Broken URL in URLHeadBear.py

### ISSUE THREAD

**Issue by frextrite** [coala/coala-bears#2833]
The default URL currently being used to check for internet connectivity, ```http://216.58.218.174``` appears to be broken. 

The ```HEAD``` request to this URL fails and hence the InvalidLinkBear, throwing an error ```[ERROR][14:16:23] The bear InvalidLinkBear does not fulfill all requirements. You are not connected to the internet.```

URL can be changed to ```1.1.1.1``` DNS IP by Cloudfare.

**Comment by frextrite** [comment]
Due to this error(as in the travis log) a couple of PRs are failing:
https://github.com/coala/projects/pull/693
https://github.com/coala/projects/pull/697

**Comment by jayantsudo24** [comment]
Could you please assign this to me? @jayvdb, @li-boxuan

**Comment by frextrite** [comment]
Hi @jayantsudo24, I'd already pinged the maintainers for assigning this to me, once they review the bug and the affected files. You can find and work on other issues marked 'difficulty/newcomer' :smile:

**Comment by sanchit48** [comment]
@frextrite My PR build is also failing due to URLHead bear.

**Comment by frextrite** [comment]
@sanchit48 Can you mention the Pull Request that is failing?

**Comment by sanchit48** [comment]
yes, here it is https://github.com/coala/community/pull/228

**Comment by frextrite** [comment]
I don't know if the whole build is failing due to this or not but found [this line](https://travis-ci.org/coala/community/jobs/475398307#L3375) where it throws the error

**Comment by sanchit48** [comment]
> I don't know if the whole build is failing due to this or not but found [this line](https://travis-ci.org/coala/community/jobs/475398307#L3375) where it throws the error

Yes, URLHeadbear is having some issues. plz fix it
