### ISSUE TITLE
README.rst: Typo in the words `newcomers' guide`

### ISSUE THREAD

**Issue by shashank-b** [coala/coala-bears#2838]
There is a link to newcomers' guide in README.rst, but it has been spelled as `newcomer guide`. To make it grammatically correct and to remain consistent with the rest of the docs and the website, it should be corrected.

This could be a suitable issue for newcomers.

**Comment by siddhantkhandelwal** [comment]
I would like to fix this as a newcomer

**Comment by shashank-b** [comment]
@siddhantkhandelwal, a maintainer would assign the issue to you soon. Meanwhile, you should go through the newcomers' guide if you haven't already.

**Comment by siddhantkhandelwal** [comment]
Sure, will do!
Thanks!
