### ISSUE TITLE
RELEASE_NOTES.rst: Expired Link

### ISSUE THREAD

**Issue by kapurm17** [coala/coala-bears#2840]
In the file, RELEASE_NOTES.rst , the link to the list of Major API changes, in the line 391, has expired and the list is not found.
The link needs to be updated.

**Comment by sanchit-ahuja** [comment]
@kapurm17 I would like to work on this issue as a newcomer. Thanks.

**Comment by uds5501** [comment]
Would love to work on this! @kapurm17

**Comment by kapurm17** [comment]
Hey @sanchit-ahuja @uds5501,
Please ask a maintainer to assign you the issue, after they've sent you the invite to the organisation!

**Comment by Mayank-gozu** [comment]
I would like to work on this issue! @kapurm17

**Comment by jayvdb** [comment]
We have users still on 0.8.0 .  And API changes are important to keep a record of.  We should look through the commits for 0.8.0 for anything obviously like

> Settings unification - most bears have seen API changes. Settings' names  are now consistent across bears. This supports backwards  compatibility, however (but with a deprecation notice). You can find the  whole list ...

It should be easy to re-create the list when we see some examples of what it was referring to.

**Comment by areebbeigh** [comment]
I browsed through the change logs for 0.8.0, seems like a [deprecate_settings](https://github.com/coala/coala/blob/fa8fe22562277762fd73ab3761ad1ec33263839a/coalib/bearlib/__init__.py#L15) decorator was introduced for backwards compatibility. 

Should be possible to list API changes solely by making a list of all the deprecated settings?

**Comment by areebbeigh** [comment]
Okay so this is the list of all the commits with the keyword `deprecate` prior to the release:

https://github.com/search?p=1&q=deprecate+author-date%3A2016-08+repo%3Acoala%2Fcoala-bears&type=Commits
