### ISSUE TITLE
TextLintBearTest.py failing tests

### ISSUE THREAD

**Issue by frextrite** [coala/coala-bears#2851]
A couple of tests, `test_bad_ng_words_acronym_list_item` and `test_bad_unexpanded_acronym` in `TextLintBearTest.py` are failing primarily due to a typo.

```
E               AssertionError: '"PSF" is unexpanded acronym. What does "PSF" stand for?' != '"PSF" is unexpanded acronym. What does "PSF" stands for?'
E               - "PSF" is unexpanded acronym. What does "PSF" stand for?
E               + "PSF" is unexpanded acronym. What does "PSF" stands for?
E               ?                                                   +
E                : message_base mismatch.
```

Check [Travis log](https://travis-ci.org/coala/coala-bears/jobs/487845422#L4247) for further details

`area/ci`
`difficulty/low`

**Comment by Naveenaidu** [comment]
@frextrite  This should be a `difficulty/newcomer` issues. The above isssue deals with only typo errors. Apparently the error message has been [changed by the TextLint](https://www.npmjs.com/package/textlint-rule-unexpanded-acronym)(from stands to stand) which caused the above assertion error.

**Comment by frextrite** [comment]
I tried to traceback the origin where `stand` was being emitted instead of `stands` but could not find that any file. So, just a plus one level due to traceback difficulty. XD

**Comment by jayvdb** [comment]
This is not a bug.  It worked perfectly before, so an external factor has changed, as @Naveenaidu mentioned above.
