### ISSUE TITLE
git-url-parse 1.2 support

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2869]
git-url-parse 1.2 has been released.  Our requirement should allow this version after it has been tested, and probably allow all future 1.x

**Comment by jayvdb** [comment]
And once that is done, also submit a new package version to https://build.opensuse.org/package/show/devel:languages:python/python-git-url-parse

**Comment by Naveenaidu** [comment]
Working  to submit a new package version of git-url-parse to  https://build.opensuse.org/package/show/devel:languages:python/python-git-url-parse
