### ISSUE TITLE
Replace dep munkres3 with munkres

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2871]
https://github.com/bmc/munkres now has Python 3 support, so we dont need to use https://github.com/datapublica/munkres

openSUSE already has the former, doesnt have the latter (c.f. https://github.com/coala/coala-bears/issues/2849)

https://packages.ubuntu.com/cosmic/python3-munkres appears to also be the former.

**Comment by KVGarg** [comment]
@jayvdb @li-boxuan I would like to work on this issue. Can anyone of you assign this to me ?
