### ISSUE TITLE
Pug Bear

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala-bears#290]
Seems Jade is a language to write templates for HTML.
https://www.npmjs.com/package/jade-lint

**Comment by mr-karan** [comment]
I'd like to take this up!

**Comment by Adrianzatreanu** [comment]
Hey @mr-karan we are currently trying to save some bears for the workshop you are holding in a few months, and this is quite an easy one. However, I can't stop you, it's up to you to decide and let me know if you want to get assigned! :)

**Comment by mr-karan** [comment]
Ah, cool. No probs

**Comment by Adrianzatreanu** [comment]
Great then, no worries :)

**Comment by Nosferatul** [comment]
Check http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html before this

**Comment by sahilarora535** [comment]
@Adrianzatreanu FYI Jade is now deprecated. It has changed to Pug. We should prefer a PugBear :dog:

**Comment by jayvdb** [comment]
There is a pug-lint
https://www.npmjs.com/package/pug-lint

**Comment by yash-nisar** [comment]
All the `pug-lint` commands available: 
```
~ pug-lint --help

  Usage: pug-lint [options] <file ...>

  An unopinionated and configurable linter and style checker for Pug (formerly Jade)

  Options:

    -h, --help                 output usage information
    -V, --version              output the version number
    -c, --config <path>        configuration file path
    -r, --reporter <reporter>  error reporter; console - default, inline
```
Sample output: 
```
~ pug-lint -r inline xyz
xyz:18:15 unexpected text "	
   "
```
Available rules: https://github.com/pugjs/pug-lint/blob/master/docs/rules.md
CC @jayvdb

**Comment by jayvdb** [comment]
@yash-nisar, and what is the config file format?

**Comment by yash-nisar** [comment]
Supports multiple formats, see https://github.com/pugjs/pug-lint#configuration-file

**Comment by jayvdb** [comment]
What is the benefit of coala linting these files?
How frequently are they stored in repos?
Are there any major orgs pushing this language?
Im concerned this is a fade language. I dont remember it being mentioned in any wikimedia tech evaluations.
Can this linter fix any problems?  Or just detect?  We need fixers.
