### ISSUE TITLE
lint for travis yaml config file

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#294]
https://github.com/pwmckenna/node-travis-lint

**Comment by mr-karan** [comment]
This linter has inconsisten error messages.

```
install:
script:
  - bash .ci/tests.sh
```
`value for "install" section is empty, dropping`

```
install
script:
  - bash .ci/tests.sh
```

`syntax error: (<unknown>): could not find expected ':' while scanning a simple key at line 13 column 1`

The line and col number is missing in the first error message

**Comment by sils1297** [comment]
It probably has *linting* and *parsing error* messages

**Comment by mr-karan** [comment]
Yep that's the case. Would make things difficult with regex

This is a good alternative: https://github.com/travis-ci/travis-yaml

**Comment by Nosferatul** [comment]
Check http://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html before this

**Comment by jayvdb** [comment]
https://github.com/pwmckenna/node-travis-lint uses https://github.com/pwmckenna/node-travis-ci to fetch lint results from the Travis CI web API.
And the Travis CI web API is likely to be using https://github.com/travis-ci/travis-yaml anyway, so yes we should be using the Ruby linter, not the Node wrapper.

**Comment by Mixih** [comment]
I'm taking this for now. I'll be using travis's package then

**Comment by Adrianzatreanu** [comment]
@Mixih CC

**Comment by Makman2** [comment]
as no progress yet and it's part of @yash-nisar 's gsoc, reassigning to him :)

**Comment by yash-nisar** [comment]
https://docs.travis-ci.com/user/travis-lint has a precise explanation for the steps to be followed.
Sample output: 
```
 ~  travis lint travis-yaml 
Warnings for travis-yaml:
[x] value for addons section is empty, dropping
[x] value for branches section is empty, dropping
[x] in addons section: unexpected key apt, dropping
[x] in branches section: unexpected key exclude, dropping
```
CC @jayvdb

**Comment by jayvdb** [comment]
@yash-nisar 

```
~  travis lint travis-yaml
```

I assume you mean `travis lint .travis.yml`.

No doubt you have seen in your analysis that this bear fails for coala and coala-bears repos.

How valuable is this linter if it fails?

Have you looked into whether those bugs have been raised upstream?
Is it likely they will be fixed soon?

Should this bear wait until those fixes are completed?

Will you add arguments to disable some checks so that it can be used on our repos?
