### ISSUE TITLE
Add Haskell ghc-mod Bear

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#297]
Add [ghc-mod](https://hackage.haskell.org/package/ghc-mod) support for `coala-bears`

**Comment by vijeth-aradhya** [comment]
I'm still new to Coala but I would like to work on this since I have recently learnt Haskell. I have written a couple of parsers and a Scheme Interpreter using Haskell, and it would be interesting to write a LintBear for `coala-bears`

**Comment by vijeth-aradhya** [comment]
IMO `ghc-mod` will be much more than a LintBear
