### ISSUE TITLE
KeywordBear: Add optional regex_keyword param

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#311]

**Comment by rubdos** [comment]
I merely suggested on some form of word detection, but regex variants are easily made too, I suppose. :)

**Comment by underyx** [comment]
It should then probably be renamed to MatchBear or something

**Comment by Makman2** [comment]
maybe we could add another parameter, `keyword_type='regex' | 'plain'` to change the matching behaviour^^

**Comment by Nosferatul** [comment]
@rubdos are you still on it?

**Comment by Nosferatul** [comment]
Unassigned because of inactivity

**Comment by Nosferatul** [comment]
Check bears/general/KeywordBear.py . Add optional param to `run` method( optional means that the param should have a default value, something like `regex_keyword = "Default"`)

**Comment by dracarys09** [comment]
@Nosferatul @sils All we need to do is to add a setting called ```regex_keyword``` and check all words in a file which matches this regex... So basically we need to modify the run function of KeywordBear...Am I on the right track ?

**Comment by underyx** [comment]
I think it would be nice by the way if we could plan the configuration
format in a way that would be extensible to also support substitutions
later.

**Comment by dracarys09** [comment]
we can have ```regex_keyword``` for finding certain keywords and each time a match happens we can prompt a user if he wants to change that word with something else or not... how does this sound ?

**Comment by underyx** [comment]
The use case I had in mind was auto-replacing wrongly written stuff when
running with coala -a, and sharing information via the coafile across a
team about how things are written correctly.

**Comment by dracarys09** [comment]
@underyx IMO the problem with using coala -a is even if we use regex to detect some wrongly written stuff, how will we know what should be the 'correct' phrase to replace the wrong phrase with ?

**Comment by underyx** [comment]
It should be specified in the coafile. As an example you could replace
'anything = logging.getLogger()' with 'logger = logging.getLogger()' to
have standard naming.

**Comment by dracarys09** [comment]
@underyx so finally what we would like to do is to find keywords using the regex specified in ```regex_keyword``` and each time a match occurs replace it with whatever is specified in coafile. So basically there should be two settings specified in coafile ```regex_keyword``` and ```replace_keyword```.
Is that it or do you want to add something more to this ?

**Comment by underyx** [comment]
Oh, to be clear, the scope of this issue is still just the regex keyword
functionality. I'll have to open a new issue about the replace/patch
suggestion feature. I just wanted to mention it in case we could save time
later by planning for it now.

**Comment by dracarys09** [comment]
@underyx so what's the point of just matching some keywords and not doing anything ?

**Comment by dracarys09** [comment]
I would like to work on this... however IMO there should be one more issue for the functionality that we discussed here... :smile:

**Comment by underyx** [comment]
The point is to warn that 'anything = logging.getLogger()' is wrong. It's
easier to implement just this warning so let's just start with that.

**Comment by dracarys09** [comment]
@underyx I have one more doubt... Do we still want to keep existing setting ```keywords``` because if we are introducing a setting ```regex_keyword``` it can already take care of matching the exact words (which is done currently using ```keywords```). So my point is that a user can do the following : 
```regex_keyword = word1|word2|word3``` and so on instead of ```keywords=word1, word2, word3``` 
and moreover if a user supplies a more complex regex, that can be handled by regex_keyword.
