### ISSUE TITLE
KeywordBear: Detect words for ci/cs keywords

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#312]
Make sure separators like `,#./` are around the word and change docs accordingly I guess?

difficulty/low

**Comment by rubdos** [comment]
`.,#/:<>;\\n\r`, you have more of them? Better make a good list :-)

Or I could do the reverse, split on everything but [a-zA-Z0-9] + characters in the actual thing we search for?

**Comment by rubdos** [comment]
`.,#/:<>;\\n\r`, you have more of them? Better make a good

**Comment by Adrianzatreanu** [comment]
is this still being worked on :) ?

**Comment by rubdos** [comment]
This will get worked on whenever my schedule allows this... Just be sure to ping me now and then. I started adding these kind of github and gitlab issues to my Thunderbird Lightning task list now though, that should help.

**Comment by sims1253** [comment]
@rubdos ping :)

**Comment by Nosferatul** [comment]
@rubdos ?

**Comment by Nosferatul** [comment]
Unasigned because of inactivity

**Comment by cosmin004** [comment]
Assign me to this issue.

**Comment by sils** [comment]
we decided with @cosmin004 and @Adrianzatreanu that this issue is stupid and nobody needs it
