### ISSUE TITLE
LocalBearTestHelper: Missing doc_string for ``execute_bears``

### ISSUE THREAD

**Issue by srisankethu** [coala/coala-bears#321]
Update doc_string [here](https://github.com/coala-analyzer/coala-bears/blob/master/tests/LocalBearTestHelper.py#L20) area/documentation difficulty/newcomer

**Comment by heijligen** [comment]
Then I'll try this one

**Comment by FyXtreMe** [comment]
let me fix this one

**Comment by sils** [comment]
@FyXtreMe still working on this?

**Comment by manu-chroma** [comment]
@sils can I take up this issue now ? @FyXtreMe seems to be inactive.

**Comment by sils** [comment]
There you go @manu-chroma :)
