### ISSUE TITLE
DocumentationFormatBear

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#34]
_From @Makman2 on December 16, 2015 23:34_

The documentation extraction routines are ready now, what needs to be done next:
1. documentation parsing machinery:
   This should work with regexes or similar. Also this shall be configured for each language inside a coafile!
2. documentation reassembling:
   Shouldn't be problematic using the current `DocumentationComment` class. Just a nice function like `assemble_documentation_comment`/similar.
3. The actual `DocumentationFormatBear`
- extract documentation from given source code
- parse it
- check it against the user defined style/regex
- for patching: reassemble the wanted documentation comment

See #919.

_Copied from original issue: coala-analyzer/coala#1140_

**Comment by sils1297** [comment]
actually it would be nice to do things like add/remove periods after the end of a parameter description or capitalize/uncapicalize the first char of a description. This way we can get rid of https://github.com/coala-analyzer/coala/issues/173 in the same run.

**Comment by AbdealiJK** [comment]
@SanketDG @Makman2 Was this done as part of GSoC ? Can you update this if it was partially addressed or close if it's completed ?

**Comment by Makman2** [comment]
gets implemented here: https://github.com/coala-analyzer/coala-bears/pull/699

**Comment by damngamerz** [comment]
@jayvdb This is complete can be closed :)
The only thing remaining is adding DocStyleBear to .coafile with doc fixes to overall project. I will create and issue about it.
