### ISSUE TITLE
JSONFormatBear: Parse exception message

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#35]
_From @sils1297 on December 13, 2015 13:31_

Would be a nice feature to show line and column automatically, instead of having it in the message:

`This file does not contain parsable JSON. 'Expecting property name enclosed in double quotes: line 2 column 7 (char 8)'`

_Copied from original issue: coala-analyzer/coala#1130_

**Comment by sils1297** [comment]
_From @SanketDG on January 27, 2016 19:5_

What is the intended behaviour for this? What do you mean by:
> Would be a nice feature to show line and column automatically

**Comment by sils1297** [comment]
_From @Makman2 on January 27, 2016 19:18_

@SanketDG I think @sils1297 means parsing the message to extract the position where the JSON style error occurred. So you get a result with position values and the message would just be `Expecting property name enclosed in double quotes`. @sils1297 Did I understand that right?

**Comment by sils1297** [comment]
Yes. To express it more complicated but IMO exact, the exception contains
that info in the message as text, we want it as result metadata.

**Comment by sils1297** [comment]
@jjsg hey, need help?

**Comment by sils1297** [comment]
Until further notice I'm assuming you're not interested anymore, simply ping me otherwise.

**Comment by sils1297** [comment]
_From @jjsg on February 15, 2016 8:25_

@sils1297 hey i m little slow, but working on it

**Comment by Adrianzatreanu** [comment]
Unassigned due to inactivity

**Comment by Nosferatul** [comment]
Check `bears/js/JSONFormatBear.py` line 42. repr(str(err)) - will return a string containing a printable representation of an object. repr(str(err)) = `Expecting property name enclosed in double quotes: line 2 column 7 (char 8)`
Instead that line, print only `Expecting property name enclosed in double quotes.` get the number of the line, column and char and parse them.
