### ISSUE TITLE
HaskellLintBear.py: Imports should be in alphabetical order

### ISSUE THREAD

**Issue by tushar-rishav** [coala/coala-bears#355]
Imports must be sorted aplhabetically
bears/haskell/HaskellLintBear.py

**Comment by sils1297** [comment]
this should happen everywhere, best to use PyImportSortBear with the latest isort for that and do it all at once, set up a gitmate check

**Comment by AbdealiJK** [comment]
Note that there are a few places where this is not applicable, because in some places order of import matters. Example setup.py

**Comment by gs0510** [comment]
@sils1297 I'd like to work on this. :)
