### ISSUE TITLE
Make LocalBearTestHelper robust

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#36]
_From @AbdealiJK on December 8, 2015 13:31_

Currently, `LocalBearTestHelper` simply checks if there are results that are yielded or not.
Would be considerably better is we give it a list of line, cols where the result should yield in a given file.

_Copied from original issue: coala-analyzer/coala#1111_

**Comment by sils1297** [comment]
@AbdealiJK I think we should support both, it's nice to have those simple tests sometimes IMO

**Comment by sils1297** [comment]
_From @AbdealiJK on December 8, 2015 13:59_

Yes, i meant it as an optional thing

**Comment by sils1297** [comment]
The helper should also create the actual files so it can be used well with linters that use file input.

**Comment by SanketDG** [comment]
What would be the best way to specify the line and column numbers for each invalid file?

**Comment by AbdealiJK** [comment]
Simple list of line,col tuple?


-----Original Message-----

**Comment by SanketDG** [comment]
So something like:
```
    valid_files=(valid_xml_file, valid_xml_chars),
    invalid_files=(invalid_xml_file, invalid_xml_chars),
    positions=([(start_line, end_line, start_col, end_col), ...], [....])
```

**Comment by abhsag24** [comment]
@SanketDG @sils1297  i have an `assertRange`  function iin  #227 that does exaclty this

**Comment by Makman2** [comment]
I think we should check against `Results`, then we can check for everything yielded, like severity etc.

**Comment by abhsag24** [comment]
This issue was moved to coala/coala#2862
