### ISSUE TITLE
Use golang dependency manager to go get the dependencies

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#43]
_From @sudheesh001 on February 15, 2016 13:10_

Similar to how we have `requirements.txt` for `pip` and `package.json` for `npm` we can also have a file holding the dependencies for golang

_Copied from original issue: coala-analyzer/coala#1501_

**Comment by sils1297** [comment]
Thought about that too, is there already a file format designed for that?

**Comment by sils1297** [comment]
_From @sudheesh001 on February 15, 2016 13:38_

I think `godep` takes a `json` in a specified format, i'll fix this once #1499 lands into master

**Comment by sils1297** [comment]
#1499 has landed :)

**Comment by sils1297** [comment]
_From @AbdealiJK on February 19, 2016 14:24_

not fixed yet :( Goopfile didnt work as expected in circleci

**Comment by Adrianzatreanu** [comment]
no progress so unassigning :(

**Comment by jayvdb** [comment]
I think this should be closed.  I've opened https://gitlab.com/coala/package_manager/issues/129 , which is where we would add new Go package managers, so they can be used here.
