### ISSUE TITLE
Add link to install instructions in missing prerequisites messages

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#432]

**Comment by sils1297** [comment]
not only to the tool

**Comment by sils1297** [comment]
Bluntly assigning @Adrianzatreanu as this is a very simple thing but related to your project which then will automate the installation, right?

**Comment by Adrianzatreanu** [comment]
I guess so.

**Comment by Adrianzatreanu** [comment]
im not so sure where to add which links..

**Comment by sils1297** [comment]
Bears have the prerequisite checking method which has a message, that message should ideally contain instructions how to fix it. Linter has a parameter for it I think? Maybe we need to introduce one here? Something like `install_instructions` CC @Makman2

**Comment by Adrianzatreanu** [comment]
Bear.py has @classmethod
    def check_prerequisites(cls): which returns whether a bear has or not satisfied the prerequisites. i guess i could check using this method for each bear to see if they are satisfied, in which case i throw a link if they arent?

**Comment by Adrianzatreanu** [comment]
ah never mind, linter has @classmethod
        def check_prerequisites(cls): too

**Comment by Adrianzatreanu** [comment]
after discussions, it's been clear what i have to do, ill do this soon :)

**Comment by Adrianzatreanu** [comment]
is this still relevant now that we use cib?

**Comment by sils1297** [comment]
more than ever, we should generate those messages from the Requirement set
instead of manually providig it!

**Comment by arush0311** [comment]
Can I take this?

**Comment by sils** [comment]
@Adrianzatreanu @arush0311 sure, I think the most important thing to address is that the Bear class should generate the installation instructions from the DEPENDENCIES metadata

**Comment by sils** [comment]
though @fneu might have a word to say

**Comment by sils** [comment]
he's about to refactor it. At least he's saying it...

**Comment by fneu** [comment]
No objections from me. Dependency checking will stay in the requirements. I'm not touching those kinds of messages. 


@sils I'm busy driving to Harburg, the GitMate Hangouts call later and our meetup this evening. 
I want the cib stuff done this week. I now there will be GitMate feedback so I'm counting on Sunday.

**Comment by sils** [comment]
but the commands won't be generated by the classes, right? I think it makes sense to wait for your changes and then get as much info as possible about installation and ideally a doc link from whatever you do. E.g. if your function can make sure that an APT package does the job maybe we can generate a URL to the package or so.

**Comment by fneu** [comment]
Commands for checking will be generated by the classes. For system packages I.e. by `shutil.which()` as we don't care who provides it in that case.

**Comment by arush0311** [comment]
@sils Just a clarification there are two types of dependencies system and bear. Do we have to show a message for both?

**Comment by sils** [comment]
closing this in favour of https://github.com/coala/coala/issues/3219

**Comment by sils** [comment]
it shouldn't matter for deps if it's a local or global bear @arush0311

**Comment by arush0311** [comment]
So only system deps should be checked?

**Comment by sils** [comment]
I don't get you

**Comment by arush0311** [comment]
same here :laughing:

**Comment by arush0311** [comment]
I mean do the dependencies in in BEAR_DEPS need to be checked also (checking if the required bears are also installed?)

**Comment by sils** [comment]
certainly! As described in the new issue
