### ISSUE TITLE
Cleanup GoReturnsBearTest by removing unnecessary information

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#44]
_From @sudheesh001 on February 15, 2016 19:48_

the GoReturnsBearTest contains the following which needs to be removed

``` python
a = ['import "errors"', '',
     'func F() (*MyType, int, error) { return nil, 0, errors.New("foo") }']
b = ['package main', '', 'import "os"', '',
     'func main() {', '\tf, _ := os.Open("foo")', '}']
```

Put the good_files in the same line like the bad_files

``` py
(good_file1,
     good_file2,),
    (bad_file1, bad_file2,))
```

Also correct GoReturnsBear's `run()` documentation to show `using goreturns` instead of `using gofmt`

difficulty/newcomer

_Copied from original issue: coala-analyzer/coala#1516_

**Comment by sils1297** [comment]
_From @satyamamrev on February 16, 2016 7:39_

I want to contribute to this

**Comment by sils1297** [comment]
_From @sudheesh001 on February 16, 2016 8:24_

@satyamamrev You could get started with http://coala.readthedocs.org/en/latest/Users/Install.html#installing-coala-from-source

Here are the contribution guidelines http://coala.readthedocs.org/en/latest/Getting_Involved/README.html

**Comment by sils1297** [comment]
_From @AbdealiJK on February 21, 2016 11:22_

@satyamamrev is doing this in https://github.com/coala-analyzer/coala/pull/1533

@sils1297 he needs to be added to the org

**Comment by sils1297** [comment]
Invitation pending to satyamamrev and hypothesist

2016-02-21 12:22 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sils1297** [comment]
Assigning @hypothesist since he accepted the invitation.

**Comment by Adrianzatreanu** [comment]
unassigning due to numerous contributions?

**Comment by sarthak268** [comment]
assign me this

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by mihai-burduselu** [comment]
Assign me this!

**Comment by OctavianGuzu** [comment]
Assign me this!

**Comment by sils** [comment]
Both of you are already assigned to another newcomer issues. We only have a limited number of them and they take a lot of time to review etc, consier doing a coala.io/low issue instead if you want more!

**Comment by dracarys09** [comment]
I would like to get assigned to this.

**Comment by sils** [comment]
there you go

**Comment by dracarys09** [comment]
I need some clarification

a = ['import "errors"', '',
     'func F() (*MyType, int, error) { return nil, 0, errors.New("foo") }']
b = ['package main', '', 'import "os"', '',
     'func main() {', '\tf, _ := os.Open("foo")', '}']

Instead of 'a' and 'b' variable names are 'good_file1' and 'good_file2' 

(1) Should I remove those lines ?
