### ISSUE TITLE
Gherkin Linter

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#447]
https://www.npmjs.com/package/gherkin-lint

> Gherkin is the language that Cucumber understands. It is a Business Readable, Domain Specific Language that lets you describe software’s behaviour without detailing how that behaviour is implemented.

https://github.com/cucumber/cucumber/wiki/Gherkin

Used in a very popular python module `behave` to write feature files for doing BDD.

**Comment by jayvdb** [comment]
Solved already because of a duplicate ;-(
