### ISSUE TITLE
Show stdout and stderr for linter bears

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#455]
Print the stdout and stderr from linter based bears when tests fail.

Gets difficult to debug things like: https://ci.appveyor.com/project/coala/coala-bears/build/1.0.1152/job/itn0bcmo387clohn

I can see that the code for the old API is here : https://github.com/coala-analyzer/coala-bears/blob/master/tests/LocalBearTestHelper.py#L27

We need to add appropriate code for the new API too !
It's been immensely helpful for me to debug

**Comment by arafsheikh** [comment]
@AbdealiJK Can you please elaborate a little on what has to be done? L29 & L32 in `LocalBearTestHelper` already handle stderr and stdout.

**Comment by Makman2** [comment]
This can be easily achieved with mocking `process_output` that retrieves the output to the test helper and forwards it then for further execution to linter again :+1:

**Comment by Makman2** [comment]
@arafsheikh ping me if you need help with this, overriding `process_output` is not yet documented for Linter v2 API^^

**Comment by Nosferatul** [comment]
@arafsheikh ping

**Comment by Mixih** [comment]
@arafsheikh it seem that you are not working on this currently. I am reassigning the issue because another person has shown interest and I do not see a pr here.

**Comment by Vamshi99** [comment]
Is this responsible for failing of builds in https://github.com/coala/coala-bears/pull/1409 ? 😟
https://travis-ci.org/coala/coala-bears/jobs/214619678#L3510-L3524

**Comment by yash-nisar** [comment]
Nope @Vamshi99 , this issue is an enhancement to the testing API of bears so there isn't supposed to be any problem. :)

**Comment by yash-nisar** [comment]
Proof that the patch works : 
http://paste.ubuntu.com/25155867/

To summarize, we have : 
```
E           Running bear MarkdownBear...
E           Running 'remark /tmp/tmpx12h5fev --no-color --quiet --setting "ruleRepetition": 3, "bullet": "-", "incrementListMarker": true, "fences": true, "fence": "`", "setext": false, "closeAtx": false, "ruleSpaces": false, "entities": false, "looseTable": false, "listItemIndent": "1", "emphasis": "*", "rule": "*", "spacedTable": true, "strong": "*" --use lint="firstHeadingLevel": null, "noDuplicateDefinitions": true, "codeBlockStyle": "consistent", "noShortcutReferenceImage": true, "maximumHeadingLength": 60, "noShortcutReferenceLink": true, "noDuplicateHeadingsInSection": true, "noEmptyURL": true, "checkboxContentIndent": true, "noHTML": true, "noUnusedDefinitions": true, "noUndefinedReferences": true, "noFileNameIrregularCharacters": "\\.a-zA-Z0-9-_", "noTabs": true, "finalDefinition": true, "noHeadingPunctuation": ".,;:!?", "blockquoteIndentation": 2, "headingIncrement": false, "noDuplicateHeadings": true --use validate-links'
E           The program yielded the following output:
E           
E           Stdout:
E           <h1>Hello</h1>
E           
E           Stderr:
E           ../../../tmp/tmpx12h5fev
E             1:1-1:15  warning  Do not use HTML in markdown  no-html  remark-lint
E           
E           ⚠ 1 warning

../coala/coalib/testing/LocalBearTestHelper.py:50: AssertionError

```
