### ISSUE TITLE
Add star destroyer

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#471]
`pip install star_destroyer`

from https://twitter.com/zestyping , looks promising

**Comment by sils1297** [comment]
Looking a bit at this right now. Maybe I can meet the developer later this week.

**Comment by sils1297** [comment]
see also https://github.com/zestyping/star-destroyer/issues/1

**Comment by Adrianzatreanu** [comment]
the tool is unmaintained, it has no active community, doesnt even have an entry point, imo drop it. we could rather have a bear written by ourselves that does the same thing :)

**Comment by sils** [comment]
ok
