### ISSUE TITLE
Feedback from PyCon

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#479]
We got some feedback. Here is it. TODO: file single issues out of this.
# COAST

high level extensible AST will blow up into lots of specific things
-> go lower level
# API

proper API documentation
# Worries

Same warnings from different tools -> eliminate
# Results

add interpreter version to result
# Globbing/file collection

shebangs instead of file endings? or on top
# coala logo feedback
- Incorporate typography
- Make it simpler

Make the ear the c of coala?

**Comment by AbdealiJK** [comment]
@sils1297 Have issues been created yet ?

**Comment by sils1297** [comment]
don't think so

**Comment by Adrianzatreanu** [comment]
outdated.
