### ISSUE TITLE
Add C to supported languages in README

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#481]

**Comment by underyx** [comment]
Can I get this assigned? I've heard people say 'oh, it does not support C then?' before :D

**Comment by Makman2** [comment]
sure :3

**Comment by underyx** [comment]
@Makman2 actually, could you unassign me? :D

The workshop we had is over now, so I'd rather just leave this for an actual newcomer to do.

**Comment by Makman2** [comment]
alright :P

**Comment by HarshaLaxman** [comment]
I'd like to do this!

**Comment by sils1297** [comment]
go for it :)

**Comment by Adrianzatreanu** [comment]
unassigning due to long inactivity

**Comment by jjhonson** [comment]
I'll do it ... you're talking about just updating the table to include C?  Do you need to assign it to me or can I just do the pull request?

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/! (Especially with newcomer issues some people are doing double work, assignments help preventing this)

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by Mariatta** [comment]
Is this still open? Can I work on this?

Thanks :smiley:

**Comment by Asnelchristian** [comment]
well @jjhonson seems to be working on it

**Comment by Mariatta** [comment]
cool no prob :) I'll keep looking. Thanks for the quick reply.

**Comment by jjhonson** [comment]
I am working on it ... just confirming.  Turning a very easy project into a hard one but I'll get it figured out.  Thanks for your patience
