### ISSUE TITLE
MarkdownBear seems to be incomplete?

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#498]
I have a file with the following content:

``` md
# dotfiles

## Installation

1.  Install `git`, `zsh`, and the `en_US.UTF-8` locale
2.  Run `git clone https://github.com/underyx/dotfiles && dotfiles/install`

Whee! :tada:
```

Running `coala --bears=MarkdownBear` on it gives me no errors, but `remark README.md -u remark-lint` gives me the following output:

```
        5:4  warning  Incorrect list-item indent: add 1 space  list-item-indent
        6:4  warning  Incorrect list-item indent: add 1 space  list-item-indent
```

I want coala to tell me these messages :(

**Comment by yash-nisar** [comment]
This can be closed since the issue has been fixed. We use `list_indent` in our bear that reformats the file for us. See the patch that MarkdownBear offers below : 

```
**** MarkdownBear [Section: cli] ****

!    ! [Severity: NORMAL]
!    ! The text does not comply to the set style.
[----] /home/yash/gsoc/xyz.md
[++++] /home/yash/gsoc/xyz.md
[    ] Line affected 2
[    ] 
[----] 1.  Install `git`, `zsh`, and the `en_US.UTF-8` locale
[    ] Line affected 2
[    ] 
[----] 2.  Run `git clone https://github.com/underyx/dotfiles && dotfiles/install`
[++++] 1. Install `git`, `zsh`, and the `en_US.UTF-8` locale
[++++] 2. Run `git clone https://github.com/underyx/dotfiles && dotfiles/install
```

CC @Makman2 @underyx (We need to close the issue.)

**Comment by Makman2** [comment]
@underyx If you want the same messages appearing in coala too, feel free to file a new issues, as this is a general problem of linters not providing both at once, help text and patch.

**Comment by Makman2** [comment]
Ah this is more or less addressed in https://github.com/coala/coala-bears/issues/502.
