### ISSUE TITLE
PHPCodeSniffer

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#504]
We should have that!
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting

Should be difficulty/low to do reporting only with everything configurable, maybe report an issue for getting fixes together with the issues possibly in a json or so.

**Comment by sils1297** [comment]
CC @Makman2 @tushar-rishav

**Comment by AbdealiJK** [comment]
`everything configurable` Nope, difficulty/medium most probably. PHPCS is **super** configurable

**Comment by sils1297** [comment]
lets add it with basic configuration first? I'd love to have it ASAP so we have at least *something* to offer to those users

**Comment by Asnelchristian** [comment]
I am on it :)

**Comment by sils** [comment]
@Asnelchristian any progress? Important stuff.

**Comment by sils** [comment]
this is done!

**Comment by sils** [comment]
18178789a24aeeb27753a57309d857716346f991
