### ISSUE TITLE
Categorize Bears

### ISSUE THREAD

**Issue by fneu** [coala/coala-bears#508]
We need to know which analysis features we can offer for which languages, 

the idea so far is to **categorize all routines into attributes** and add (a group of) **attributes to each bear**.

I would like some input as to which catefories make sense,

`CAN_FIX` for example should definitely be an attribute.

**Comment by Makman2** [comment]
hmm... something like `CAN_FIX` can be meaningless if a bear only fixes a certain kind of issues, while others don't have a patch. I think the documentation of each bear should state that accordingly^^

**Comment by fneu** [comment]
Well, certainly, but it would be really nice to have an overview about the features of coala, for us as well as for potential users.

Since the numbers and abilities of our bears are evolving rapidly, @sils1297 asked for a mechanism that would automatically determine and update the list of abilities.

**Comment by sils1297** [comment]
also users will want to filter stuff on the website

**Comment by Makman2** [comment]
@sils1297 
when I'm looking for a bear, I usually start with the language, nobody starts searching for something like `CAN_FIX` (even if there's a checkbox list of features bears shall include), as the ability to fix stuff is not the prerequisite for using coala, it's the ability to look over *your* code in *your language*. Fixes are just a nice bonus.

@fneu yes, though imo abilities can be so fine graded, we don't gain something meaningful from it^^ if you would for example introduce `CAN_DETECT_CYCLIC_COMPLEXITY`, and set it together with `CAN_FIX` and `CAN_DETECT_STYLE_ISSUES` (which is so super generic, just too generic), these abilities would tell me nearly nothing, only that something with cyclic-complexity can be analyzed, something can be fixed and generic style issues are detected. Especially for more complex abilities there are limits, these need to be described properly, a simple flag is imo too vague.

**Comment by fneu** [comment]
So how would you write or capabilities down on the website?

**Comment by sils1297** [comment]
Like github issues, you should be able to filter bears for different properties and sort and so on, we'll want as much metadata as possible.

**Comment by Adrianzatreanu** [comment]
outdated, done by aspects tbh.
