### ISSUE TITLE
FormatRBear: Allow to disable parameter-options for formatR

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#514]
Sometimes certain style rules shall not be checked at all, we should allow to disable them (like `r_use_arrows`).

CC @Asnelchristian

**Comment by Asnelchristian** [comment]
can i work on this one ?

**Comment by sils1297** [comment]
sure!

**Comment by Makman2** [comment]
Ah in the PR message this issue was referenced... but it's not solved yet

**Comment by gs0510** [comment]
@Makman2  @sils1297 I see the issue is still open, but using  r_use_arrows = true/false did exactly what it was supposed to do.  Are there other style rules that should be allowed to be disabled?

**Comment by Makman2** [comment]
I think `r_use_arrows = False` (for example) forced to use no arrows at all. So it's either the one or other extreme when using such a setting. Though I could be wrong with this (long time ago when this issue was opened :3)

**Comment by gs0510** [comment]
@Makman2 Yes what you are saying is true. So is the requirement that in some places we should  use the arrow and in other places we should still be using equal to sign? For example if we have r_use_arrows=true start_line_num=10 end_line_num=20, we can have arrows in line numbers from 10 to 20. Is that what is required? Can you please explain in a little detail what the requirements are? Thanks!

**Comment by Makman2** [comment]
If the setting is not touched inside a coafile, no check shall happen at all.

For example:
```
# inside coafile:
bears = FormatRBear
# some settings regarding FormatRBear except 'r_use_arrows',
# meaning we don't want to care whether '=' or '<-' is used.
```

This can be achieved via setting the default value for `r_use_arrows` to `None` (here -> https://github.com/coala/coala-bears/blob/master/bears/r/FormatRBear.py#L36)  and omitting the according command-line-parameter if `r_use_arrows = None` (here -> https://github.com/coala/coala-bears/blob/master/bears/r/FormatRBear.py#L83).

(Though this setting is only allowed to be either `True` or `False`, coala doesn't check the default value, that's why `None` does not make any problem inside the declaration as a default value.)

**Comment by gs0510** [comment]
If I do not modify the r_use_arrows, and have both = and <- in my r file, nothing changes. The <- and = are both still intact. Here's an [asciinema](https://asciinema.org/a/88016) recording that I made. Hope this closes this issue.

**Comment by Makman2** [comment]
Oh than I was wrong :3
But does this work for all other parameters too? If so we can happily close this one indeed :)

(Btw it's interesting what patch is applied in your asciinema as I can't see any change in the file :3)

**Comment by gs0510** [comment]
Are you talking about Applied 'ApplyPatchAction' on 'test.r' from 'FormatRBear' ? I just did a diff before and after the change. The bear adds a newline at the end of the file.

**Comment by Makman2** [comment]
ah alright, nothing serious then :D

**Comment by incorrectusername** [comment]
What else was needed in this ?

**Comment by Makman2** [comment]
seems like it just wasn't continued^^

**Comment by incorrectusername** [comment]
If I have  understood the issue then we have to remove functionalities such as  r_keep_comments , r_use_arrows. Do we have to remove r_braces_on_next_line ? 
Is there anything else than i would like to know . I think i can solve this.

**Comment by Makman2** [comment]
No don't remove them, allow the bear to "ignore" the settings.

> I think r_use_arrows = False (for example) forced to use no arrows at all. So it's either the one or other extreme when using such a setting.

And we want by default having sth like `r_use_arrows = None` and we just don't pass the argument to the R formatter. This applies for other settings as well, not only for `r_use_arrows`.
