### ISSUE TITLE
FormatRBear: Rename _map_to_r_bool

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala-bears#539]

**Comment by AbdealiJK** [comment]
@Asnelchristian what would you like it to be named ?

**Comment by manu-chroma** [comment]
Hey, I'd like to work on this one.
@Asnelchristian have you thought of a name for the function ?

**Comment by manu-chroma** [comment]
cc: @sils1297 @AbdealiJK

**Comment by Makman2** [comment]
Actually the renaming was not @Asnelchristian's idea, have forgotten who mentioned this :D

I think myself that the name is okay, it hits more or less the point. If you agree I would close this issue, if not, feel free to come up with a name on your own :)

**Comment by manu-chroma** [comment]
@Makman2 Feel free to close the issue. I also feel that the function name is fine given that it has one line implementation :smile: 

Can you suggest any other ``newcomer`` issue I could possibly work on ? This was supposed to my first issue on coala. 
Thanks! :)

**Comment by Makman2** [comment]
There are some left you can take :)

https://github.com/coala/coala-bears/issues?q=is%3Aopen+is%3Aissue+label%3Adifficulty%2Fnewcomer+no%3Aassignee

https://github.com/coala/coala/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adifficulty%2Fnewcomer
