### ISSUE TITLE
FilenameBear: Not aware of ``space_case`` 

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala-bears#556]
This bear is not aware of the space_case naming convention that was added.
For example:
    ``Hello World``
will produce an error

**Comment by AbdealiJK** [comment]
It's interesting to note that you put space case in snake_case in the title :P

So, I can't find any reference to space case from my brief googling.
I can fine snake case - https://en.wikipedia.org/wiki/Snake_case and camel case https://en.wikipedia.org/wiki/CamelCase

Could you give a reference to space case being used or a reference to what exactly it is ?
I'm not sure which ones from: "a b" or "A b" or "a B" or "A B"  are in space case and which are not, are numerals and spl. chars allowed, etc.

**Comment by Makman2** [comment]
"Space case" is our inofficial name for styles like:
```
Hello World
My Super File Name With Spaces
```
@AbdealiJK for further examples see https://github.com/coala-analyzer/coala/blob/aef8ec970af021397e8b13feda26574c87b6f448/coalib/bearlib/naming_conventions/__init__.py#L96

how numbers and such are handled I don't know now, you can just try to run the algorithm on such ones :) But I don't think we specified it that perfectly, so if you have ideas you can share them :D

**Comment by Makman2** [comment]
So what needs to be done:
1. Add an entry for `spacecase` so the bear recognizes the spacecase convention: https://github.com/coala-analyzer/coala-bears/blob/master/bears/general/FilenameBear.py#L18
2.  Write tests :+1:

**Comment by AbdealiJK** [comment]
I'm sorry, but this seems weird to me. We're *creating* a new standard of casing (naming convention) which isn't being used anywhere as of now ?

Is there any usecase where this is useful ? Is there any language using this sort of a convention ?
As I see it, based on my understanding right now, the `to_spacecase()` function would be considered dead code as it's not used anywhere and I'd vote to remove it from coalib.

**Comment by Makman2** [comment]
maybe for text files (with documentation)? Though you are right, I don't know why I wanted this naming conention :/
But I mean it's a feature, it doesn't harm to have it :3

**Comment by AbdealiJK** [comment]
I disagree. Features that don't have a usecase in mind are evil, and it wastes time of devs in terms of writing it and maintaining it.

I remember @sils1297 shared a nice blog post which explained this well a long long time ago (Share if you still have it)

**Comment by amrandahvur** [comment]
Please Assign me this

**Comment by amrandahvur** [comment]
@Makman2 I have added the ``spacecase`` convention and have also written the corresponding tests. I still am having trouble with the "tests" though. Could you please review ? Thanks :)

**Comment by Makman2** [comment]
@amrandahvur see comment in PR. Btw if you have issues that are related to your PR, post there, as this issue is just for discussion about the task (ideally) :)
