### ISSUE TITLE
GitCommitBear: Change ``returns`` to ``return``

### ISSUE THREAD

**Issue by Asnelchristian** [coala/coala-bears#571]
[line](https://github.com/coala-analyzer/coala-bears/blob/master/bears/vcs/git/GitCommitBear.py#L147)
difficulty/newcomer

**Comment by tushar-rishav** [comment]
Haha! The Irony!

**Comment by Asnelchristian** [comment]
yeah this is really funny :)

**Comment by MichalCab** [comment]
I want to do this

**Comment by sils** [comment]
unassigning due to PR inactivity

**Comment by Adrianzatreanu** [comment]
unassigning due to long inactivity

**Comment by sahildua2305** [comment]
@Adrianzatreanu please assign this to me :)
