### ISSUE TITLE
Add httpolice bear

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#596]
https://github.com/vfaronov/httpolice 

> HTTPolice is a lint for HTTP requests and responses. It checks them for conformance to standards and best practices.

Looks a neat tool

**Comment by sils1297** [comment]
Yesyesyes!

**Comment by Adrianzatreanu** [comment]
ping @mr-karan

**Comment by mr-karan** [comment]
I'd do it once i have some free time but i don't really know when. Maybe a week or so? If anyone else wants to take this, please do so I'll unassign myself else will complete in next few days.

**Comment by Shade5** [comment]
Hey, still working on this?

**Comment by Makman2** [comment]
as no further progress yet and it's part of @yash-nisar 's gsoc, reassigning to him :)

**Comment by jayvdb** [comment]
How will this fit within the linter framework?

Is it only going to be a linter for `.har` files?

Or something else?  If so, much more details please.

**Comment by yash-nisar** [comment]
Yes, this is mainly targetted at `.har` files. However, the tool can be used for raw [TCP streams](http://httpolice.readthedocs.io/en/stable/streams.html#), [combined format](http://httpolice.readthedocs.io/en/stable/streams.html#combined-format) as well.
 Output format of Httpolice: 
```
------------ request: GET http://президент.рф/
E 1045 Syntax error in request target
```

**Comment by jayvdb** [comment]
What is the benefit of coala linting .har files?
How frequently are they stored in repos?
