### ISSUE TITLE
[Bear Proposal] Rust Bears

### ISSUE THREAD

**Issue by sims1253** [coala/coala-bears#611]
We don't have any bears for rust at the moment. 
@justuswilhelm you like rust. Wanna write some bears?

**Comment by rubdos** [comment]
See #50 for a linter (rust-clippy).

**Comment by rubdos** [comment]
https://github.com/coala/coala-bears/pull/1467 (rust-clippy merge request WIP)

**Comment by Makman2** [comment]
I guess this can be closed as duplicate of https://github.com/coala/coala-bears/issues/50

**Comment by Makman2** [comment]
In case someone wants to implement a bear using the rust-compiler `rustc`, please file a new issue for this specific tool :+1:
