### ISSUE TITLE
Add CSSCombBear for CSS 

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#634]
https://github.com/csscomb/csscomb.js

also was featured in https://github.com/showcases/clean-code-linters

**Comment by Nosferatul** [comment]
Hi! I wanna try it!

**Comment by Adrianzatreanu** [comment]
feel free to

**Comment by Makman2** [comment]
as no further progress yet and it's part of @yash-nisar 's gsoc, reassigning to him :)

**Comment by jayvdb** [comment]
What does this linter do that other css bears do not?

**Comment by yash-nisar** [comment]
Damn, I was almost half way through and noticed that this bear is blocked on https://github.com/csscomb/csscomb.js/issues/451.

To summarise, there is no way at present to get the corrected file as the output from `stdout` on which we can apply the diff. Also, there are no error messages reported that can be parsed by our regex. As of now it abruptly flags an error in `-v` and without `-v` it runs `csscomb` over the file but doesn't make any changes.

I've tested this behaviour.
Related issues : 
* https://github.com/csscomb/csscomb.js/issues/351
* https://github.com/coala/coala-bears/issues/28
* https://github.com/csscomb/csscomb.js/issues/451

IMO, we should add the status/blocked and an upstream label to this issue.
CC @Makman2
