### ISSUE TITLE
Add HTMLHint for HTML 

### ISSUE THREAD

**Issue by mr-karan** [coala/coala-bears#635]
https://github.com/yaniswang/HTMLHint

**Comment by Asnelchristian** [comment]
i am on it :)

**Comment by yash-nisar** [comment]
Can I be assigned to this @meetmangukiya @Asnelchristian @aptrishu ? I'll try to accomplish this within a week. :smile:

**Comment by meetmangukiya** [comment]
@yash-nisar sorry it seems @Asnelchristian has a PR up already, that is already almost ready :)

**Comment by meetmangukiya** [comment]
https://github.com/coala/coala-bears/pull/1350

**Comment by yash-nisar** [comment]
Okay, the PR doesn't have an issue reference so I thought this was untouched.

**Comment by yash-nisar** [comment]
I'm taking this over with @Makman2 and @Asnelchristian 's permission :smile: 
Can I be assigned to this ?
