### ISSUE TITLE
IndentationBear - Ignore doc comments/doc strings

### ISSUE THREAD

**Issue by abhsag24** [coala/coala-bears#644]
Doc comments don't usually follow standards and we are trying to ignore doc comments within the indentationBear, till then it is best if we tell people to ignore the IndentationBear over doc comments in the inline doc for the IndentationBear

**Comment by Makman2** [comment]
we already have doc-extraction algorithms, it should be possible to implement that inside `IndentationBear` constructing ignore ranges out of the extracted comments^^

**Comment by kriti21** [comment]
@Makman2 Could you tell me what doc-extraction algorithms are you referring to in https://github.com/coala/coala-bears/issues/644#issuecomment-236375590?

**Comment by bkhanale** [comment]
This issue is reserved under the GSoC project [Improve Generic Bear Quality](https://summerofcode.withgoogle.com/projects/#4866569388163072).
