### ISSUE TITLE
InvalidLinkBear: domain-timeout-map

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#686]
If I know a server is slow, I might need a higher timeout just for that server.

Not sure if it pays off to do this but it might. CC @maweki

**Comment by AbdealiJK** [comment]
Do you think it's really important to do a domain based timeout ?
Isn't increasing the timeout for the whole project OK ?

**Comment by maweki** [comment]
When we talked about this, we had the issue that some w3c servers responded within 30 seconds while the default timeout would be one or two seconds with the average response time being way below that.
A general timeout increase might increase the bear-time by a huge factor if something is down you expect shouldn't be.

I think it would be nice to override the timeout on a per domain-basis.

**Comment by AbdealiJK** [comment]
@maweki that makes sense.
But the increase in bear-time would be only if a lot of the links actually failed (Which for a routine user of coala should be rare ^_^)

But yeah, I agree it makes sense to have it.

**Comment by Makman2** [comment]
should be quite easy to implement with a `defaultdict` :+1:

**Comment by meetmangukiya** [comment]
I'd like to work on this one. @Makman2 what do you mean by a `deafultdict`?

**Comment by sils1297** [comment]
google `defaultdict`

**Comment by meetmangukiya** [comment]
Should we add an extra option for this, something like
`coala --files somefile --bears InvalidLinkBear --timeout x` where `x` would be the number of seconds.

**Comment by meetmangukiya** [comment]
Btw, who would be mentoring this issue? So that I'd know who should I approach. :wink:

**Comment by Makman2** [comment]
the community can help you with any concern (see gitter-channel), if you want you can ping me if needed :D (slowly getting into coala again)

**Comment by Makman2** [comment]
and the option would ideally be a dictionary, where you can specify the domain(-prefix, or maybe regex) which maps onto the right timeout.
The option should have a more specific name, maybe like `network_timeout` or similar? At least `timeout` is too generic (especially as bears do share settings).

**Comment by Makman2** [comment]
So for example:
```
# inside the .coafile
[Default]
bears = InvalidLinkBear
network_timeout = https://github.com: 1.2 # <-- in seconds
```
