### ISSUE TITLE
False postive collection for invalidlinkbear

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#691]
- [x] From https://github.com/coala-analyzer/coala-bears/issues/685: `http://www.w3.org/Consortium/Legal/</h3`
- [x] `http://cran.rstudio.com').install_command()`
- [x] `http://www.spice-space.org/download.html\">http://www.spice-space.org/`
- [x] `http://cran.rstudio.com\`
- [x] A URL with `xmln(s|s:\S+)=` directly in front isn't necessarily valid.
- [ ] `//domain.com/img/logo.png` should be tried with `http` and `https` I think
- [x] In XML:

``` diff
-      <image>http://people.gnome.org/~zeeshanak/screenshots/gnome-boxes-selection.png</image>
+      <image>https://people.gnome.org/~zeeshanak/screenshots/gnome-boxes-selection.png%3C/image>
```

**Comment by sils1297** [comment]
So also we should do something about templates:

```
plugins/steam/src/steam-cover.vala
|  26| »   »   var•uri•=•@"http://cdn.akamai.steamstatic.com/steam/apps/$game_id/header.jpg";
|    | [NORMAL] InvalidLinkBear:
|    | Broken link - unable to connect to http://cdn.akamai.steamstatic.com/steam/apps/$game_id/header.jpg (HTTP Error: 404)
```

**Comment by jack17529** [comment]
Any big developers working on this ?

**Comment by jack17529** [comment]
[ ] 1. write a python code to make URL with xmln(s|s:\S+)= directly in front invalid.
[ ] 2.//domain.com/img/logo.png should be tried with http and https and make a Python code.

Can't understand xml point can someone please elaborate?

**Comment by jack17529** [comment]
please assign me this if I am right.

**Comment by jayvdb** [comment]
@refeed, can you check which of these examples are still a problem.
Create separate issues for any obvious distinct problems, and we'll discuss any of the less clear problems.
Then we can close this "omnibus" issue.

**Comment by refeed** [comment]
> //domain.com/img/logo.png should be tried with http and https I think

Opened an issue for this on https://github.com/coala/coala-bears/issues/1827

> A URL with xmln(s|s:\S+)= directly in front isn't necessarily valid.

That issue has been fixed in https://github.com/coala/coala-bears/commit/7f99537f706dca5c1144607e558af2fab9f51a61 by reducing the severity.

```diff
-      <image>http://people.gnome.org/~zeeshanak/screenshots/gnome-boxes-selection.png</image>
+      <image>https://people.gnome.org/~zeeshanak/screenshots/gnome-boxes-selection.png%3C/image>
```
Also has been fixed, (when I run InvalidLinkBear to analyze that file, it runs correctly) I think it's fixed in https://github.com/coala/coala-bears/commit/a8e4babdde9369ada2034c0f39036af75c7767b3

> So also we should do something about templates:

Fixed in https://github.com/coala/coala-bears/commit/25493f6096a2195df4bb05bf04230f76b0c824c7

**Comment by sils** [comment]
ok then this can be closed with only https://github.com/coala/coala-bears/issues/1827 left right? Thanks a lot for the investigation, that's what was needed here.

**Comment by refeed** [comment]
Right :)
