### ISSUE TITLE
InvalidLinkBearTest: Add test with a mix of both valid and invalid links

### ISSUE THREAD

**Issue by adtac** [coala/coala-bears#694]

**Comment by dracarys09** [comment]
@SanketDG  still working on this or should I go ahead and add a test case ?

**Comment by Makman2** [comment]
@adtac don't we test that already?

**Comment by adtac** [comment]
@Makman2 I don't think so. At least when I filed the issue, there wasn't any particular test with both. I just quickly took a glance and it still doesn't seem to have one. I dunno, if I'm wrong, we can close this.

@dracarys09 let's just wait to see if this issue is still valid.

**Comment by Makman2** [comment]
https://github.com/coala/coala-bears/blob/master/tests/general/InvalidLinkBearTest.py#L79

There I see different links referring to "valid" and "invalid"^^

**Comment by dracarys09** [comment]
@adtac  I thinks @Makman2 is right about this... ```valid_file``` has all valid links whereas ```invalid_file``` has invalid links... So we should close this issue right ?

**Comment by adtac** [comment]
That's what I mean - there's no single file with both valid and invalid links. That is there is no file like

```
http://httpbin.org/status/200
http://httpbin.org/status/404
```

Every link in `valid_file` is valid (ignore lines like the template one; they aren't actually links). Every link in `invalid_file` is invalid.

**Comment by sils** [comment]
What's the problem with that?

**Comment by dracarys09** [comment]
@adtac some time back I added a test case in PR for https://github.com/coala/coala-bears/issues/1106
Check this : https://github.com/coala/coala-bears/blob/master/tests/general/InvalidLinkBearTest.py#L208
I think that would suffice...

**Comment by adtac** [comment]
@sils problem with what? Didn't get you there. I meant to say we should have a test with both.

@dracarys09 ah didn't notice that test; this issue can now be closed.
