### ISSUE TITLE
Automatically sync bear dependency attributes and requirements.txt

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#743]

**Comment by AbdealiJK** [comment]
@underyx Could you elaborate ? Do you mean that the REQUIREMENTS of a bear should be used and populate the requirements.txt ?

**Comment by underyx** [comment]
Needs design — all I wanted to have is no more cases of bear REQUIREMENTS & requirements getting out of sync. I'm fine with syncing like that, or syncing the other way, or just having CI check it.

**Comment by AbdealiJK** [comment]
So, I believe that eventually, we will be completely removing the requirements.txt when `cib` is stable.
Because then after that each bear will have it's own pypi package, and we will simply have coala-bears as a meta package which depends on all of them

**Comment by Adrianzatreanu** [comment]
agreed.

**Comment by jayvdb** [comment]
Oh whoops; https://github.com/coala/coala-bears/issues/1044 was created as a dup, and completed.
