### ISSUE TITLE
CI: cache ruby gems

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#749]
You can specify bundler's install directory, and then cache it.

**Comment by AbdealiJK** [comment]
Don't we already do this ? We are directly caching the default directory - `~/.rvm/gems/ruby-2.1.5/gems/` according to the circle.yml file

**Comment by underyx** [comment]
@AbdealiJK I opened this issue cause of this build failure https://circleci.com/gh/coala-analyzer/coala-bears/2887

**Comment by AbdealiJK** [comment]
Hm, you're right. Seems like what we're caching is wrong as it gets re-installed for other build too - Example: https://circleci.com/gh/coala-analyzer/coala-bears/2893

**Comment by Adrianzatreanu** [comment]
ping @underyx :p

**Comment by underyx** [comment]
@Adrianzatreanu fixed in https://github.com/coala/coala-bears/commit/14ba8643232c2cf15569cd347fdd02c1b5625bd2, closing
