### ISSUE TITLE
stylint bear

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#754]
https://www.npmjs.com/package/stylint

I happen to know that some of our users are using stylint, maybe we could make their life easier with the next release :)

area/lintbears difficulty/low

**Comment by ivange94** [comment]
assign to me

**Comment by ivange94** [comment]
Can I be unassigned from this? I have not even found the time to read stylint link you provided. My internship just got more tense. And pursuing personal adventures seem to really impossible now. I was hoping I would work on this over weekends but I just got informed that Saturday is a normal working day. When I finish my internships I'll take this back if nobody works on it.

**Comment by sils1297** [comment]
@ivange94 did you delete a comment here? I got an email but nothing's here

**Comment by ivange94** [comment]
Hmm sorry about that. Maybe I deleted thinking I was deleting something else. I would like to be unassigned. My internships have become more tense and going on personal adventures is proving difficult. I have not even found the time to follow the link about stylint at the top. When I find some free time I'll pick it back if no one works on it.

**Comment by Makman2** [comment]
feel free to come back any time :)

**Comment by yash-nisar** [comment]
I can do this @Makman2 @meetmangukiya @aptrishu .
