### ISSUE TITLE
GitCommitBear: Check commits down to a certain base commit

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#757]
would be nice if we could give the GitCommitBear the name of an env variable (which some CI services expose) and if it exists it checks more than just the HEAD commit but all commits down to the one given by that variable!

type/feature difficulty/medium

**Comment by jayvdb** [comment]
Inspecting multiple commits is out of scope for GitCommitBear.  It should be done in GitMate, which is already looking at multiple commits, and/or in another tool (I am interested in a `git coala` which would do this).
