### ISSUE TITLE
KeywordBear: add possibility to remove line, if it's a comment

### ISSUE THREAD

**Issue by netman92** [coala/coala-bears#761]
It would be nice to add possibility to remove that line.

```bash
file.py
|  96| ••••••••••••#•TODO:•NOTE
|    | [INFO] KeywordBear:
|    | The line contains the keyword `todo`.
|    | The following actions are applicable to this result:
|    |  0: Apply no further actions.
|    |  1: Open the affected file(s) in an editor.
|    | Please enter the number of the action you want to execute (Ctrl-D to exit). 
```

**Comment by sils1297** [comment]
@abhsag24 you did something similar, can we use coalang here to find where the comment starts and generate a patch? Though if coalang isn't available for the language the bear should still detect the keyword so we can't have a dependency on one of the comment detection bears e.g. :/

**Comment by abhsag24** [comment]
So the correct way should be to use the `AnnotationBear` but we cant use it for languages which dont have coalang, so maybe there should be a setting in `coala` which should suppress the call to `get_dependencies`?

**Comment by sils1297** [comment]
As discussed on gitter: I think a conditional call of the dependencies is super complicated. Instead the dependency could return a hidden result with error info and the bear using it can decide to error out or to proceed without the info.

**Comment by Makman2** [comment]
For keywords imo it's highly situation dependent. When I have TODOs I actually look at them thoroughly again. Then I also got the time to open my (presumably already opened) IDE/editor and remove the line by hand.

Especially it gets complicated for lines like:
```
    this_is_code = 3  # TODO 3 --> 4
```

I'm voting for a `wontfix/not-happening`, as it's complicating up stuff and extremely usecase dependent^^

**Comment by sils1297** [comment]
Well we can offer the patch, the user can just not take it. I think the PR
for this is definitely sane.

**Comment by Makman2** [comment]
but if we say "there's a patch", the user (especially me) would think that this would be some kind of solution which works. Not that someone thinks coala can read the comment and addresses its contents :P

And for my code example above where code is in the same line as the comment, the patch would just be totally wrong. Imo it doesn't fulfill the purpose of a patch at all^^

**Comment by sils1297** [comment]
@Makman2 please read the commit, it'll detect where the comment starts and keep the code, removing only the comment.

**Comment by Makman2** [comment]
still I think that having a patch to delete the comment is not a fix/patch^^
also these style of comments came to my mind:
```
# FIXME
# I need to do something
# Go to file X and 3 --> 4
```
There's where the current bear would not really work^^

**Comment by Adrianzatreanu** [comment]
unassigning due to huge inactivity.

**Comment by sils** [comment]
@netman92 any news? @Adrianzatreanu wanna quickly finish this? There was only minorities left IIRC.

**Comment by netman92** [comment]
@sils Already pushed.

**Comment by sils** [comment]
:+1: thanks!

**Comment by sils** [comment]
@netman92 I can't seem to find your PR anymore :/

**Comment by netman92** [comment]
@sils It's here, but closed https://github.com/coala/coala-bears/pull/778.

Should I create new one? I assume, that reopening will be better.

**Comment by sils** [comment]
We don't care. But you can't reopen after pushing to the branch so you'll
have to make a new one. GitHub won't let you.

**Comment by netman92** [comment]
Ok, https://github.com/coala/coala-bears/pull/884
