### ISSUE TITLE
RadonBear settings are radon specific

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#772]
all our compelxity analysis bears should use the same setting, we probably want to have one threshold for normal issues and _maybe_ another optional one for major issues?

difficulty/low importance/medium

**Comment by sils1297** [comment]
CC @Asnelchristian

**Comment by Asnelchristian** [comment]
i am on it

**Comment by MacBox7** [comment]
Want to work on this.

**Comment by Makman2** [comment]
Reassigning due to inactivity.
