### ISSUE TITLE
PuppetLintBear - Make an AsciiCinema

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#784]
We need a ascii cinema for puppet lint bear. This should be added to the bear

difficulty/newcomer

**Comment by gs0510** [comment]
Hi! I'd like to do this. Just wanted to confirm if the ASCII cinema being talked about here is the one described here: https://github.com/asciinema/asciinema . Thanks!

**Comment by sils1297** [comment]
yes :)

Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)
