### ISSUE TITLE
SpellCheckBear - Make an AsciiCinema

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#785]
newcWe need a ascii cinema for spell check bear. This should be added to the bear

**Comment by gs0510** [comment]
Hi! I'm working on issue #784 as well which is similar to this. Can I be assigned to this issue as well? Thanks!

**Comment by sils1297** [comment]
Sure, please don't do more than two newcomer issues though (and if you see typos or such things please *file* newcomer issues! We're running out of those I think.)
