### ISSUE TITLE
ci/appveyor.yml: Remove `setup.py --help` command

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#800]
Remove these two lines:
https://github.com/coala-analyzer/coala-bears/blob/master/.ci/appveyor.yml#L57-L58

**Comment by sils1297** [comment]
Add this info to the commit message but please rephrase it well: it was
needed back when setup.py was implicitly downloading dependent jars and so
on.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by ivange94** [comment]
https://github.com/coala-analyzer/coala-bears/pull/827
