### ISSUE TITLE
Usability: deafult parameters for various bears

### ISSUE THREAD

**Issue by adtac** [coala/coala-bears#819]
I'm testing out the practicality of coala-quickstart and I have a few points:

* In FilenameBear, should we make snake-casing the default or should we make it a mandatory input from the user?
* In KeywordBear, should we set `["TODO", "FIXME"]` as the default value of `keywords`?

I'll keep adding more as I find stuff. If you have anything else to add, please add a comment. I think this issue should act as the umbrella issue for all these things instead of making several tiny issues.

**Comment by Makman2** [comment]
1. I would say mandatory user input, e.g. .NET has PascalCase convention, C often uses snake case, so it's highly language dependent.
2. yes, would say so

**Comment by Makman2** [comment]
@Adrianzatreanu what about

> In FilenameBear, should we make snake-casing the default or should we make it a mandatory input from the user?

**Comment by Adrianzatreanu** [comment]
you gave your statement as a no, i think "no" too and lasse has no opinion on it, so .. didnt do it.

**Comment by Makman2** [comment]
ah okay yeah :3
