### ISSUE TITLE
Add PyFlakesBear

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#825]

**Comment by jayvdb** [comment]
See https://github.com/coala-analyzer/coala-bears/issues/753#issuecomment-247118765 (and earlier).

**Comment by SanketDG** [comment]
This has repeating functionality with [flake8](https://duckduckgo.com/?q=pyflakes+flake8&ia=web)

**Comment by jayvdb** [comment]
> This has repeating functionality with flake8

See also #169 for request for a flake8 bear.

Note that it is possible for a Flake8 bear to not run pyflakes.

An important consideration with pyflakes (and flake8 which uses it) is that it reports errors based on the version of Python that it is run it.  i.e. it uses the python interpreter's tokenizer, ast, and it has its own Python-version-specific rules.  Thus the pyflakes package needs to be run on multiple versions of Python to catch all bugs.  This also means that it cant only be imported and run as a python module within the coala environment , if it is going to be used to find Python 2 bugs, as coala is Python 3 only.

**Comment by Nosferatul** [comment]
Please tell us when do you want to work on something.

**Comment by srisankethu** [comment]
@Nosferatul I took this up after discussion on the https://gitter.im/coala/coala-bears
