### ISSUE TITLE
Circle CI trusty image does not pass

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#829]
My first CI build of master  is very broken

https://circleci.com/gh/jayvdb/coala-bears/1

**Comment by SanketDG** [comment]
So this was like all things failing at once:

* debc4d2 is the first issue, it is definitely not being done in the right way. CC @underyx 

* `CSSAutoPrefixBear` was failing, primarily because `-webkit-flex` is no more in usage, so there was result generation in the good file testing.

* `DockerfileLintBear`'s executable is actually broken for about, um, 15 days. https://github.com/projectatomic/dockerfile_lint/issues/54

The first two have a way out, I have no idea how to fix the third one. Maybe we will have to use a specific version or skip the test until the upstream bug gets fixed.

**Comment by sils1297** [comment]
Sanket can you look into making the fixes?

**Comment by SanketDG** [comment]
Fix is at https://github.com/coala/coala-bears/pull/832. Apparently debc4d2 works, sorry for all the confusion though

**Comment by jayvdb** [comment]
It is still broken for me. https://circleci.com/gh/jayvdb/coala-bears/4

**Comment by sils1297** [comment]
IIUC dockerfile_lint has fixed their issue and the tests should pass. However caching might hinder circleci from getting the new version, can't we bump the version in our package.json to force it to get the new fixed version?

Also the TSLintBear seems to fail. Maybe for similar reasons?

**Comment by jayvdb** [comment]
On Travis it is easy to clear the cache. Can't that be done on Circle?

**Comment by SanketDG** [comment]
Yeah I have already cleared the cache. But there are other breaking changes in other tools. I am looking into it.

**Comment by SanketDG** [comment]
Fixed in 18defb4 94c7897 3ba5bbd.

If your tests are failing in your PR, please rebase.

Feel free to reopen if the tests fail again after rebasing.

**Comment by jayvdb** [comment]
I did rebuild master and it failed. Trying again with the cache cleared.  https://circleci.com/gh/jayvdb/coala-bears/tree/master (builds 9 & 10)

**Comment by SanketDG** [comment]
https://circleci.com/gh/jayvdb/coala-bears/10 The tests pass for `DockerlintFileBear` but other tests time out. Could you rebuild again?

**Comment by sils1297** [comment]
we should change our config to allow larger runtimes if the timeout is the
problem

**Comment by jayvdb** [comment]
Still failing

**Comment by SanketDG** [comment]
The master branch is supposedly fix ( no failed builds on the latest commits ).

For the failing builds, I ssh'd into one of them and found the old version being used.

The thing is every branch/PR has its own cache[[1]], so we have to first restart every build without cache for every PR.

Or find a saner way to fix this.

[1]: https://circleci.com/docs/how-cache-works/

**Comment by sils1297** [comment]
fix the version of the cached dependency explicitly?

**Comment by sils1297** [comment]
to force upgrade

**Comment by jayvdb** [comment]
https://circleci.com/gh/jayvdb/coala-bears/12 was a retry without cache.  I've restarted without cache again (not rebased, so I am missing 3ba5bbd..4926dc0 which includes a requirements bump for coala).

**Comment by jayvdb** [comment]
https://circleci.com/gh/jayvdb/coala-bears/15 using tip

```
> install.packages('formatR', dependencies=TRUE, quiet=TRUE, verbose=FALSE)
> 
> 
+ go get -u github.com/golang/lint/golint
# cd /home/ubuntu/.go_workspace/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Connection timed out
package golang.org/x/tools/go/gcimporter15: exit status 1

bash .ci/deps.sh returned exit code 1
```

https://go.googlesource.com/tools/ of course works well normally.  Why does it fail in Circle CI?

**Comment by sils1297** [comment]
Maybe the build just needs to be restarted?

**Comment by jayvdb** [comment]
Restarted; another failure, and the build log is too large to dispay the error.

**Comment by SanketDG** [comment]
this is a serverside issue. Can you restart again?

**Comment by jayvdb** [comment]
Up to #17 red builds now. https://circleci.com/gh/jayvdb/coala-bears

**Comment by SanketDG** [comment]
@jayvdb Sorry for stretching this out, but this hasn't appeared in the master branch or any other PR in this repo for a while, do you still have this?

**Comment by jayvdb** [comment]
I dont understand your comment, in light of #852, which says master is broken.

**Comment by SanketDG** [comment]
@jayvdb oh yes that is a different issue, but the issues with respective to this fail were fixed.

**Comment by jayvdb** [comment]
This is not about a specific issue.  It is now 16 days that the master has not been green on my fork, despite building it repeatedly after various fixes have been applied.  Several of those times the main repo was green by I wasnt able to reproduce it, rebuilding master with a clean cache.  The master commit hasnt changed many times in this period, so I keep rebuilding the same commit because I am asked to, but I am struggling to understand why I should get a different result when none of the inputs has changed.

**Comment by jayvdb** [comment]
Current problem is #859

**Comment by jayvdb** [comment]
@SanketDG, have you tried running a build on your own fork yet?  Did it work?

**Comment by jayvdb** [comment]
The next problem is #865

**Comment by SanketDG** [comment]
I haven't had the time, but looks like https://circleci.com/gh/coala/coala-bears/3316 is another failure, even after retrying three times

**Comment by jayvdb** [comment]
@sils1297 commented 17 days ago:
> Also the TSLintBear seems to fail. Maybe for similar reasons?

Yes, now that I have disabled Julia Lint, I am seeing this again.

```
>           raise AssertionError(str(err) + " \n" + "\n".join(msg))
E           AssertionError: 0 == 0 : The local bear 'TSLintBear' yields no result although it should. 
E           Running bear TSLintBear...
E           Running 'tslint --format json --rules-dir / /tmp/tmpwvrw3u_9.ts'
```

This occurs in `TSLintBearOtherOptions.test_invalid_files`, `TSLintBearWithoutConfig.test_invalid_files` and `TSLintBearTestWithConfig.test_invalid_files`.

**Comment by jayvdb** [comment]
^ raised as #866 

@SanketDG commented 3 hours ago:
> ...looks like https://circleci.com/gh/coala/coala-bears/3316 is another failure...

raised as #868 as I have also reproduced that now with #867.  Ironically I think it is the opposite problem.
the `coala/coala-bears` cache probably needs to be cleared, or the faulty object in the cache invalidated by changing a requirement version somewhere.

**Comment by jayvdb** [comment]
Ah!

Maybe many of my problems are that `coala/coala-bears` is using the Ubuntu 12.04 image, whereas `jayvdb/coala-bears` is on the **default** trusty 14.04 image.
