### ISSUE TITLE
Remove deprecated link in the document string from the `Lint` class in the `Lint.py` file

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-bears#837]
http://coala.readthedocs.io/en/latest/Users/Tutorials/Linter_Bears.html is the link in the file, it is 404'd, it needs to be updated.

difficulty/low

**Comment by meetmangukiya** [comment]
difficulty/newcomer

**Comment by Makman2** [comment]
@meetmangukiya why did you close again?

**Comment by meetmangukiya** [comment]
Moved to https://github.com/coala/coala/issues/2774 @Makman2
