### ISSUE TITLE
Make bear settings even more awesome

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala-bears#838]
So right now we almost unified the bear settings thanks to @Asnelchristian's amazing effort. But the param descriptions are still not the most helpful there are, because they are not unified completely. I think we should maintain a unity among all settings, such as this one:

```
:param color_case:
      Description: Changes the color case.
      Values: Upper: Makes all colors with upper-case letters.
              Lower: Makes all colors with lower-case letters.
      Examples:
            (Upper):
                 .a {
                       color: #fff;
                  }
                 Turns into:
                 .a {
                       color: #FFF;
                  }
             (Lower): analog

```

CC @Asnelchristian as you are the master of these

**Comment by Asnelchristian** [comment]
this is awesome :)

**Comment by Adrianzatreanu** [comment]
i feel like this helps just looking up and knowing what possible values each thing has, instead of guessing, and knowing what each one does.

**Comment by jayvdb** [comment]
`color_case` is only used by one bear.

This concept became aspects, has been partially done, and thus has outgrown this issue.
