### ISSUE TITLE
Create coala --bear-details <bear_name>

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/coala-bears#839]
Considering we accept this https://github.com/coala/coala-bears/issues/838, i think we should have a nice option like : ``coala --bear-details PEP8Bear`` which parses the new settings format and shows what the bear does, possible values and stuff. it would be truly helpful.

CC @Asnelchristian

**Comment by sils1297** [comment]
This should be in cib instead, not in coala

**Comment by sils1297** [comment]
@Adrianzatreanu can we close it and do this in cib please

**Comment by Adrianzatreanu** [comment]
:(
