### ISSUE TITLE
help(bears) isnt very helpful

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-bears#85]
Currently `import bears` followed by `help(bears)` is not very useful. It just gives a list of modules inside. We should ideally have a description of coala/coala-bears there too.

I think we need to add a doc-comment  in bears.__init__.py which gives better information.

We could also use this in the `setup.py` maybe ?

**Comment by mr-karan** [comment]
I would like to work on this.

**Comment by AbdealiJK** [comment]
@mr-karan aren't you already working on https://github.com/coala-analyzer/coala-bears/issues/71 ?

**Comment by mr-karan** [comment]
Yes I am. I'll be completing #71 in a bit.

**Comment by sidn77** [comment]
I would like to be assigned to this issue
