### ISSUE TITLE
master failing

### ISSUE THREAD

**Issue by SanketDG** [coala/coala-bears#852]
https://circleci.com/gh/coala/coala-bears/3278

Probable cause: Apparently, lots of other files are being picked up by the test suite I think.

Probable solution: We should ignore the `vendor` and other 3rd-party folders in the `py.test` config.

difficulty/low

**Comment by SanketDG** [comment]
Also, pydocstyle changed its API, there is a test failing because of a newly added rule.
Changing line 36 of `PyDocStyleBearTest`:

```diff
-    settings={'pydocstyle_ignore': 'D400, D200, D103'},
+    settings={'pydocstyle_ignore': 'D400, D200, D103, D212'},
```

**Comment by srisankethu** [comment]
I have made 2 different commits
