### ISSUE TITLE
julia add package Lint fails on Circle CI trusty images using ppa:staticfloat/juliareleases

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#859]
https://circleci.com/gh/jayvdb/coala-bears/19 fails on trusty images with the following at the end of the build log.

```
...
 + julia -e 'Pkg.add("Lint")'
WARNING: Error during initialization of module GMP:
ErrorException("The dynamically loaded GMP library (version 5.1.3 with __gmp_bits_per_limb == 64)
does not correspond to the compile time version (version 6.1.0 with __gmp_bits_per_limb == 64).
Please rebuild Julia.")
INFO: Initializing package repository /home/ubuntu/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:EINVALIDSPEC, Class:Net, Malformed URL 'ssh://git@github.com:/JuliaLang/METADATA.jl')
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at ./pkg/dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at ./file.jl:59
 in init(::String, ::String) at ./pkg/dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:28
 in add(::String) at ./pkg/pkg.jl:100
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318

bash .ci/deps.sh returned exit code 1

Action failed: bash .ci/deps.sh
```

**Comment by sils1297** [comment]
@SanketDG can you help out? Who wrote the julia stuff? That was a bit messy IIRC.

**Comment by Makman2** [comment]
I've added the julia deps, though this looks like a problem in julia itself. This error doesn't occur in our builds :/
@jayvdb Could you ssh into the build and try to install the package yourself with `julia -e 'Pkg.add("Lint")'`? And maybe print some versions of julia and related stuff?

**Comment by jayvdb** [comment]
I suspect if you clear the cache in a rebuild of the main repo, it will fail also.

You already have the output of `julia -e 'Pkg.add("Lint")'` above.
I have run it with `ppa:staticfloat/julianightlies` and that also fails, with the same error.

**Comment by Makman2** [comment]
I suspect that too ...

hmmm... I'll look into it making my own fork :+1:

**Comment by jayvdb** [comment]
The key problem is the colon in `ssh://git@github.com:/JuliaLang/METADATA.jl`
I've tried quite a few things to be rid of it, but havent been lucky yet.  https://circleci.com/gh/jayvdb/coala-bears/tree/gh-859

**Comment by jayvdb** [comment]
Also strange, the following from my log doesnt appear in https://circleci.com/gh/coala/coala-bears/3310 

```
WARNING: Error during initialization of module GMP:
ErrorException("The dynamically loaded GMP library (version 5.1.3 with __gmp_bits_per_limb == 64)
does not correspond to the compile time version (version 6.1.0 with __gmp_bits_per_limb == 64).
Please rebuild Julia.")
```
(And is another indicator that this bug is being avoided by `coala/coala-bears` because its builds are using a cached `~/.julia`)

**Comment by Makman2** [comment]
Very strange. Still wondering how we achieved to get a working version into our cache though^^

**Comment by jayvdb** [comment]
This may be only a problem with the trusty builds, which is still strange because the [trusty image] (https://circleci.com/docs/build-image-trusty/) doesnt provide a Julia, so it would be some lower level difference.

**Comment by jayvdb** [comment]
The 'fix' was a good workaround, but the problem remains somewhere upstream, and means we cant use this PPA until it is found and fixed.

**Comment by jayvdb** [comment]
While we have a workaround due to 13046dea1d , this is still a problem upstream and should be tracked as using these PPAs will be necessary in the future.

**Comment by sils** [comment]
@jayvdb btw. can we switch our builds now? Or did you even already do it?

**Comment by jayvdb** [comment]
That is answered at https://github.com/coala/coala-bears/issues/869#issuecomment-253729075 : I have no idea why it failed.

**Comment by jayvdb** [comment]
Now unnecessary, as Circle CI is not used, and Julia is working quite well on Travis + tox.
