### ISSUE TITLE
InvalidLinkBear: URLs wrapped within backticks `https://coala.io` are parsed wrong

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#860]
Try running the bear on a file which contains:

    `https://coala.io`

It will try to connect to

    https://coala.io`

**Comment by manu-chroma** [comment]
Tried testing this error and InvalidLinkBear parsed link correctly, 

Test file: ``error_file.txt``
'http://coala.io'
'http://fojg.cc'

Tried executing this command 
``coala --files=test_error.txt --bears=InvalidLinkBear``
```
Executing section Default...

test_error.txt
|   2| 'http://fojg.cc'
|    | [MAJOR] InvalidLinkBear:
|    | Broken link - unable to connect to http://fojg.cc
|    | *0: Do nothing
|    |  1: Open the affected file(s) in an editor.
|    | Enter number (Ctrl-D to exit):
```

**Comment by underyx** [comment]
I'm reading this in an email on my phone so I'm not sure, but isn't it
because you are using apostrophes instead of backticks there?

**Comment by sils** [comment]
Yes, this is about backticks specifically. Single quotes are already
handled, backticks apparently not.

**Comment by manu-chroma** [comment]
oh sorry, I confused backticks with apostrophes here.

**Comment by manu-chroma** [comment]
Test for this bug should be added in https://github.com/coala/coala-bears/blob/master/tests/general/InvalidLinkBearTest.py#L72 if I'm not wrong. 

Also, should the test be added in a new commit ?

**Comment by Asnelchristian** [comment]
nope.. it should be  in the same commit
