### ISSUE TITLE
GitCommitBear: Check for sequential duplicate messages at tip of commit history

### ISSUE THREAD

**Issue by underyx** [coala/coala-bears#861]
Excerpt of a commit log which should not pass CI:

```
96aa116 update of gitlab-ci.yml to include elasticsearch with icu plugin
293bc28 update of gitlab-ci.yml to include elasticsearch with icu plugin
82b6099 update of gitlab-ci.yml to include elasticsearch with icu plugin
2506abb update of gitlab-ci.yml to include elasticsearch with icu plugin
198a8a8 update of gitlab-ci.yml to include elasticsearch with icu plugin
fc0d7c3 update of gitlab-ci.yml to include elasticsearch with icu plugin
```

Depends on https://github.com/coala/coala-bears/issues/757

**Comment by sils1297** [comment]
Neat idea

**Comment by pjhampton** [comment]
Hey @underyx & @sils

I would love to take this forward. Can you please assign me?

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by meetmangukiya** [comment]
I would like to do this one..

**Comment by meetmangukiya** [comment]
What I was thinking is.. I check the last two commit shortlogs...
If they match, then I'll check deeper one more level... until they don't match.
And then print the number of commits that were same ?

**Comment by jayvdb** [comment]
Ya, I think that is sensible, and is valid even if the previous commit is merged.

**Comment by meetmangukiya** [comment]
> Ya, I think that is sensible, and is valid even if the previous commit is merged.

Ya, we will have to assume that it is rebased with `upstream/master `

**Comment by meetmangukiya** [comment]
Ohh.. I missed the _branch off point _ from the issue title.

**Comment by underyx** [comment]
@meetmangukiya how about this then? :D

**Comment by jayvdb** [comment]
Actually, `git log` can search the logs for you. See the help for relevant command line arguments.

**Comment by meetmangukiya** [comment]
I didn't find a way to find the branch off commit...

But I think I can do it this way:
1. `git log --pretty=%h <currrent branch>`
2. `git log --pretty=%h master`
3.  Check from the head commit hash backwards until I find matching hashes, thats the branch off point.
4. Then I check for duplicates until that hash only and not all the *commits*

**Comment by underyx** [comment]
Would this help? https://git-scm.com/docs/git-merge-base

**Comment by meetmangukiya** [comment]
How does this look?
```py
    def check_duplicate_shortlogs(self, no_yield= False):
        head_commit, stderr = run_shell_command('git commit -1 HEAD --oneline')
        trailing_commit, trailing_commit_stderr = \
                            run_shell_command('git commit -1 HEAD~1 --oneline')
        duplicate_commit_hashes = []
        trailing_commit_index = 1
        while trailing_commit[8:] == head_commit[8:]:
            trailing_commit_index += 1
            duplicate_commit_hashes.append(trailing_commit[:7])
            trailing_commit, trailing_commit_stderr = \
                run_shell_command(
                    'git commit -1 HEAD~{} --oneline'.format(
                                                        trailing_commit_index))
        if duplicate_commit_hashes:
            if not no_yield:
                yield Result(self, 'Commits {} have the same shortlog as that of head commit'.format(duplicate_commit_hashes))

        return duplicate_commit_hashes

```

**Comment by meetmangukiya** [comment]
Another possible approaches: 
1. I think https://git-scm.com/docs/git-merge-base#_discussion_on_fork_point_mode might help regarding that issue
we can use `git merge-base --fork-point <current branch> master` and `git merge-base --fork-point <current branch> origin/master` and see whichever one is later and check until that commit
The problem would occur, when it is being ran on master branch 

2. or we can, you know hard limit git log --max-count=20(default value) and see if it is repeated
we can, you know even ask it from the user, we can have a section for that ?

**Comment by jayvdb** [comment]
Inspecting multiple commits is out of scope for GitCommitBear.  It should be done in GitMate, which is already looking at multiple commits, and/or in another tool (I am interested in a `git coala` which would do this).
