### ISSUE TITLE
RLintBear - Make an AsciiCinema 

### ISSUE THREAD

**Issue by gs0510** [coala/coala-bears#864]
We need a ascii cinema for R lint bear. This should be added to the bear

difficulty/newcomer

**Comment by raghav16179** [comment]
assign me this

**Comment by AshwatKumar** [comment]
assign me this

**Comment by kaustavvats** [comment]
assign me this

**Comment by sils** [comment]
Assigning @raghav16179 as you asked first. Please tell us if you're no longer interested in helping, IIUC this was likely part of a workshop.

**Comment by raghav16179** [comment]
Currently I'm interested

**Comment by SanketDG** [comment]
unassigned due to inactivity

**Comment by khashf** [comment]
Since `corobo` is current not working in gitter. I comment here to indicate I'm working on this

**Comment by khashf** [comment]
PR merged. Please close this issue.

**Comment by Makman2** [comment]
It's not merged.
