### ISSUE TITLE
tslint not installed

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#866]
`tslint` is not being installed, resulting in the tests expecting an error to fail.

```
>           raise AssertionError(str(err) + " \n" + "\n".join(msg))
E           AssertionError: 0 == 0 : The local bear 'TSLintBear' yields no result although it should. 
E           Running bear TSLintBear...
E           Running 'tslint --format json --rules-dir / /tmp/tmpwvrw3u_9.ts'
```

This occurs in `TSLintBearOtherOptions.test_invalid_files`, `TSLintBearWithoutConfig.test_invalid_files` and `TSLintBearTestWithConfig.test_invalid_files`.

Unfortunately the tests for valid files are silently failing when `tslint` doesnt exist.

Here is the deps install log component showing that tslint isnt being installed in https://circleci.com/gh/jayvdb/coala-bears/33
```
$ npm install
coala-bears@0.8.0 /home/ubuntu/coala-bears
├── tslint@3.13.0 
└── UNMET PEER DEPENDENCY typescript@>=1.7.3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-happiness@5.3.1 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
npm WARN eslint-config-happiness-jsx@1.2.1 requires a peer of eslint@^2.1.0 but none was installed.
npm WARN tslint@3.13.0 requires a peer of typescript@>=1.7.3 but none was installed.
npm WARN coala-bears@0.8.0 No repository field.
npm WARN coala-bears@0.8.0 No license field.
```

**Comment by Makman2** [comment]
Interesting the test should be skipped if TSLint does not exist... And the message indicates that TSLint exists somehow, though the actual results differ from the expected ones.
CI goes crazy nowadays :3

**Comment by jayvdb** [comment]
You can test it yourself. It does not install unless the peer dependency is also installed. I sshed to the circleci vm to be sure, and it was not present.
This possibly depends on a npm version.
