### ISSUE TITLE
go get lint fails undefined: types.ImportMode

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#868]
go lint isnt installing atm

```
+ go get -u github.com/golang/lint/golint
# github.com/golang/lint
../.go_workspace/src/github.com/golang/lint/lint.go:250: undefined: types.ImportMode
```

**Comment by jayvdb** [comment]
First reported as https://github.com/coala/coala-bears/issues/829#issuecomment-251421910

When I built on my fork, with a recently build cache, this bug doesnt occur.  It seems to only be a problem with the coala/coala-bears cache.

It occurred for me on #867 when I turned off my CircleCI.

**Comment by jayvdb** [comment]
This usage of `types.ImportMode` was added to `golint` in the commit https://github.com/golang/lint/commit/a428635c58fe which is "Drop support for Go 1.5."

Ah, the difference is that `coala/coala-bears` is using the Ubuntu 12.04 image, [which comes](https://circleci.com/docs/build-image-precise/#go) with go 1.5.3 , whereas `jayvdb/coala-bears` is on the trusty 14.04 image, [which comes](https://circleci.com/docs/build-image-trusty/#go) with go 1.6.2 .
See https://discuss.circleci.com/t/switch-to-golang-1-6-for-builds/2608/10 for some background.

The most obvious solution is for `coala/coala-bears` to use the trusty image .... #869

**Comment by sils1297** [comment]
yep, let's upgrade the image to trusty. I see that's a setting in CircleCI,
I can change that in our builds when needed.

**Comment by jayvdb** [comment]
Im working on this. Nearly ready...I hope.
