### ISSUE TITLE
Use Circle CI trusty image

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#869]
The `coala/coala-bears` (and `coala/coala`) builds on Circle CI use its Ubuntu precise image.
The Ubuntu trusty image provides many important updates, and is better maintained, and the maintenance of the Ubuntu trusty image is public in https://github.com/circleci/image-builder.
See https://circleci.com/docs/differences-between-trusty-and-precise/

**Comment by jayvdb** [comment]
And in August 2016, trusty became the default.
https://circleci.com/blog/ubuntu-14-04-trusty-is-the-default-os-for-new-projects/
Anyone creating their circleci project now will have a trusty image now.

**Comment by SanketDG** [comment]
I have updated the build environment, thanks @jayvdb

**Comment by SanketDG** [comment]
The only problem is that we have to push an actual commit, to get the build changes, and I think doing a coala version bump in `requirements.txt` is the best way right now.

**Comment by jayvdb** [comment]
@SanketDG , all builds on trusty will fail with the problems I have been fighting for several weeks. I very strongly suggest that you undo whatever you have done until you have tested it will work on your own fork.

**Comment by jayvdb** [comment]
Note: I have two working solutions for this, however one creates unittest failures for cppcheck, and they both have much higher elapsed build times than precise builds, which is a show stopper IMO.
I want to isolate those failures into a reproducible bug, and hopefully fix them, so the two approaches can be compared for build elapsed times.

**Comment by jayvdb** [comment]
Note I havent been able to find a way to reduce the time spent in `.ci/deps.sh` on trusty, vs precise.
Including xenial for Julia causes most of the additional time.
As a result, we may as well install the other deps from xenial.
If increased build times are a problem, the main project can continue to use precise, and devs can use trusty occasionally to check it keeps working.
The real fix for #859 is upstream somewhere, and that is how we will decrease the trusty build times.

**Comment by jayvdb** [comment]
I've switched `coala/coala-bears` Circle CI to using trusty.  Revert if anything goes wrong or build times are excessive.

**Comment by sils** [comment]
can you trigger another build? (Not a rebuild, that won't pick up the new settings)

**Comment by jayvdb** [comment]
Done.

**Comment by jayvdb** [comment]
And failed.
```
opam init --y
Checking for available remotes: rsync and local, git, mercurial.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.

[WARNING] Recommended external solver aspcud not found.
[ERROR] No OCaml compiler found in path. You should use:

            opam init --comp=VERSION

[ERROR] Initialisation failed
```
Investigating on my Circle CI.

**Comment by sils** [comment]
then please put the builds back to the old setting

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by jayvdb** [comment]
Done.

**Comment by jayvdb** [comment]
Note I rebuilt my commit without cache and the build was green: https://circleci.com/gh/jayvdb/coala-bears/144
So I have started a rebuild without cache : https://circleci.com/gh/coala/coala-bears/3434 to see if that was the problem.

**Comment by jayvdb** [comment]
And it failed without cache.

**Comment by jayvdb** [comment]
https://circleci.com/gh/jayvdb/coala-bears/829 is a new build on trusty without cache.

**Comment by jayvdb** [comment]
The trusty builds worked, so it was enabled on coala/coala-bears due to precise not working atm.
