### ISSUE TITLE
Upgrade ESLint to version 3

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#872]
CC @oreqizer

**Comment by sudoankit** [comment]
I would like to work on this. 

Changing line `ESLintBear.py` to version 3 and adding  
```
    "extends": "eslint:recommended",
    "rules": {
        "no-unsafe-finally": "off",
        "no-native-reassign": "off",
        "complexity": ["off", 11],
        "comma-dangle": "error",
        "require-yield": "error"
    }
``` 
to `return` of `generate_config` method to retain how `eslint:recommended` worked in v2.x.

Am I on the right track? Please correct and guide me if I'm wrong.

**Comment by oreqizer** [comment]
IMO altering the rules is not a good idea - I'd personally just go with their flow of things.

**Comment by sudoankit** [comment]
Okay. Better just leave `  "extends": "eslint:recommended"` as said by [ELint v3 migration guide. ](http://eslint.org/docs/user-guide/migrating-to-3.0.0)

**Comment by sudoankit** [comment]
This reverted pull request #https://github.com/coala/coala-bears/commit/3397018e9e1435d87ac3b53c607c6847dfcd9734
 was required as changing the requirements created this error: 
```
The package eslint@3.7.1 does not satisfy its siblings'
peerDependencies requirements!

Peer eslint-plugin-import@1.15.0 wants eslint@2.x-3.x
Peer eslint-config-happiness@5.3.1 wants eslint@^2.0.0-rc.0
Peer eslint-config-happiness-jsx@1.2.1 wants eslint@^2.1.0
```
Can't we add theses dependencies in `package.json` and change it?

**Comment by AbdealiJK** [comment]
Try it, if it works then cool. If not, back to the ol' drawing board
As I see it it won't work... because some package seems to need eslint-config-happiness and eslint-config-happiness needs eslint v2 but you're telling eslint to install v3. Hence the dependency error.

**Comment by jayvdb** [comment]
IMO the correct solution is to talk with upstream, to find out why they have those version dependencies, and find upstream solutions.

**Comment by blazeu** [comment]
happiness now uses [eslint v3](https://github.com/JedWatson/happiness/blob/8d99bc3eb3eab22b61ed1cbda8acaba4ee59e54a/package.json#L22).

eslint-plugin-import also has [` "eslint": "2.x - 4.x"`](https://github.com/benmosher/eslint-plugin-import/blob/98acd6afd04dcb6920b81330114e146dc8532ea4/package.json#L59) which might indicate that they're supporting eslint v3 as well.
