### ISSUE TITLE
PyImportSortBear: Make asciinema

### ISSUE THREAD

**Issue by Udayan12167** [coala/coala-bears#876]

**Comment by yajurahuja** [comment]
assign me this

**Comment by ishaanbassi** [comment]
i poened it first

**Comment by sils** [comment]
Assigning @yajurahuja  as you asked first. Please tell us if you're no longer interested in helping, IIUC this was likely part of a workshop.

**Comment by SanketDG** [comment]
unassigned due to inactivity

**Comment by ysahil97** [comment]
I would like to take up this issue. What do we need to do here?

**Comment by harshhx17** [comment]
Please assign this issue to me.😁
