### ISSUE TITLE
cppcheck 1.72 requires --language parameter for C++ for unrecognised file extensions

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#887]
Ubuntu [`precise` `cppcheck` 1.52](http://packages.ubuntu.com/precise/cppcheck) to [`trusy-backports` `cppcheck` 1.66](http://packages.ubuntu.com/trusty-backports/cppcheck) raises errors on `CPPCheckBearTest.py`'s `bad_file`:

```c++
#define f(c) { \
    char *p = new char[10];  \
    p[c] = 42; \
}
int main() {
    f(100);
    return 0;
}
```

However [`xenial` `cppcheck` 1.72](http://packages.ubuntu.com/xenial/cppcheck), Fedora 24's 1.75, and the [github repo](https://github.com/danmar/cppcheck)'s `master` all show no errors unless `--language=c++` is added to the command line, or the file extension is a known c++ file extension.

```bash
$ cppcheck --version
Cppcheck 1.75
$ cppcheck /tmp/bad_file
Checking /tmp/bad_file...
$ echo $?
0
$ cppcheck --language=c++ /tmp/bad_file
Checking /tmp/bad_file...
[/tmp/bad_file:6]: (error) Array 'p[10]' accessed at index 100, which is out of bounds.
[/tmp/bad_file:7]: (error) Memory leak: p
[/tmp/bad_file:6]: (error) Memory leak: p
$ cp /tmp/bad_file /tmp/bad_file.cpp
$ cppcheck /tmp/bad_file.cpp
Checking /tmp/bad_file.cpp...
[/tmp/bad_file.cpp:6]: (error) Array 'p[10]' accessed at index 100, which is out of bounds.
[/tmp/bad_file.cpp:7]: (error) Memory leak: p
[/tmp/bad_file.cpp:6]: (error) Memory leak: p
```

The `--language` option was only added in 1.57 (https://github.com/danmar/cppcheck/commit/87131f6105a210), so it cant be used unconditionally, otherwise it will break earlier versions of cppcheck, such as Ubuntu precise.

**Comment by jayvdb** [comment]
The filename extension is used by default, as determined by [`Path::isC`](https://github.com/danmar/cppcheck/blob/29e1fe136a6e48122362d35c4df15ad3fa0a06c0/lib/path.cpp#L239) and `Path::isCPP`, with only `.c` being a registered `.c` extension, and the following being valid C++ extensions: .cpp, .cxx, ,cc, .c++, .hpp, .hxx, .hh, .tpp and .txx.

Test suite at https://github.com/danmar/cppcheck/blob/master/test/testpath.cpp#L152 .

As most normal code will have the correct extension, the main problem is that `CPPCheckBearTest.py` runs cppcheck using a file without an exception - previously this defaulted to C++ ; as of ~1.72 it is defaulted no language.

**Comment by sils** [comment]
Nice there should be a parameter mktmpfileargs or something like that where we can pass a file extension

**Comment by jayvdb** [comment]
Note that while #890 fixes the problem for the test suite, there is still the possibility that someone uses a non-standard C/C++ file extension , in which case CPPCheckBear silently discards the file because `cppcheck` also silently discards the file if it is not recognised.
I am digging into this a little bit, as I believe this is a bug best fixed upstream in `cppcheck`.

**Comment by jayvdb** [comment]
> because `cppcheck` also silently discards the file if it is not recognised.

I was wrong.  It does process all files, essentially as C if unrecognised.  The problem is that the two types of cppcheck errors that our current `bad_file` emits are "BufferOverrun" and "MemoryLeak".
These two checkers both bail out without any debugging info, both because `new char[10];` isnt valid C, and the relevant code is not entered due to `Path::isCPP` conditions.

That said, there is still a problem with C++ syntax not triggering C++ checks.
This already exists upstream as http://trac.cppcheck.net/ticket/6084
