### ISSUE TITLE
[Bear Proposal] gettext localisation file linter

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#892]
I dont know what are good tools for this.

Here are some possible tools:
- https://github.com/pedromorais/gettext-lint ( unmaintained )
- https://pypi.python.org/pypi/Babel (supports several formats, but is only a parser, not a linter.)
- https://github.com/willkg/dennis

**Comment by sils** [comment]
Nice indeed, I had that in mind as well. We might want to lint proper internationalization as well, checking for some common pitfalls.

**Comment by jayvdb** [comment]
https://github.com/nijel/weblate is a Python project that has a Web UI.  It does some checks, so could have dependencies that are usable for this.

**Comment by jayvdb** [comment]
`dennis` looks like a good lint tool to be the first bear.
Ignoring rule W302 (translation same as source) seems to make its error output list reasonable.

**Comment by jayvdb** [comment]
https://github.com/phpmyadmin/localized_docs/pull/2 has examples of some real problems that `dennis` catches.

**Comment by jayvdb** [comment]
Dennis should wait until https://github.com/willkg/dennis/pull/82 is released.

**Comment by adtac** [comment]
@jayvdb that PR seems to have been merged. Removing status/blocked if that's okay with you.

**Comment by Flap-Py** [comment]
I would like to work on this. Please assign me.

**Comment by Flap-Py** [comment]
So this is about linting .po and .pot files. Am I correct?

**Comment by jayvdb** [comment]
Correct. There are several existing tools, and we probably want to analyse all of them, and possibly implement all of them if they provide different errors (and I believe they do).
I know dennis is especially good for translation strings which [include html](https://github.com/willkg/dennis/blob/master/dennis/translator.py#L595).

[translate-toolkit](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/index.html#quality-assurance) is harder to wrap, but is the most established OSS tool in this space.

**Comment by Flap-Py** [comment]
So I tried to make linter bear using Dennis. I went through https://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html
Till now what I can think of is http://pastebin.com/tG1RBUZK
Now first am I going in right?
Further I needed help with the `add ignore comment` option.

**Comment by jayvdb** [comment]
Yea, that looks good.

I am not sure what you mean with "`add ignore comment` option" .

The remaining problem is that `W302: unchanged: Makes sure string is actually translated` is not like the other warnings.  unchanged translations cant be fixed by a technical person; it requires finding someone who can write that language, which isnt always solvable.

There are two ways to approach this.
Either adjust the severity map so that `W302` is level INFO, which means users can choose to show it or not by using severity NORMAL or INFO.

The other way is to add configuration, like so

```python
    def create_arguments(filename, file, config_file, allow_untranslated=True):
        if allow_untranslated:
             return ('lint', filename, '--excluderules', 'W302')
        else:
             return ('lint', filename)
```

`allow_untranslated` is then a generic flag, and we could use the same flag for a linter that used translate-toolkit, or any other similar tool; the implementation of that flag would differ for each.

**Comment by Flap-Py** [comment]
By `add ignore comment` I meant that on lint error, we have 3 choices, 
```0. Do nothing
1. Open editor.....
2. Add ignore comment```
And on choosing 2, it asks for language. SO was confused which language to put there?

**Comment by Flap-Py** [comment]
I came up with http://pastebin.com/bXM0uGkD
I wanted to confirm
- In metadata attribute Language, what to put? (right now I have `{"po", "pot"}` there. 
Also how shall I send pull request for this. Is it like put the bear.py file in `coala-bears/bears` folder and push it? or something else.
thanks :)

**Comment by jayvdb** [comment]
Looks good so far.
Put the code in `bears/gettext/DennisBear.py` , create a `__init__.py` in the same directory (see other dirs).
Create a unit test in `tests/gettext/DennisBearTest.py` (see other test files).

Create a branch, commit it, push it, PR it.  See http://coala.io/newcomer and http://api.coala.io/en/latest/Developers/Git_Basics.html, especially the commit message guideline.
