### ISSUE TITLE
CheckstyleBear should error when use_spaces is False or indent_size is not 2

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#898]
If `checkstyle_configs = Google`, indentation checking using 2 spaces, according to https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

`use_spaces=False` must emit an error
`indent_size` must be set to 2, otherwise emit an error.

**Comment by gs0510** [comment]
Can you assign this task to me?

**Comment by sils** [comment]
@jayvdb shouldn't we rather use like "google" as base and then modify according to the given settings?

**Comment by jayvdb** [comment]
@sils , checkstyle *will* error if indent is not 2 spaces or tabs are used.  It is *not* configurable.

**Comment by jayvdb** [comment]
> It is not configurable.

Well, `checkstyle` is configurable, but we are not giving it a custom config file.  We are giving it *the* google configuration.  To allow overrides, we would need to create a custom config file, using the google xml file as the basis.  That sounds like a large chunk of work, and is unlikely to be done quickly, so this is best handled as a bug fix for the current problem, and create a enhancement request for someone to rebuild this bear to support custom settings.
