### ISSUE TITLE
Make each bear an own PyPI package

### ISSUE THREAD

**Issue by sils1297** [coala/coala-bears#9]

**Comment by AbdealiJK** [comment]
For the record - I'm against this.
It's just way too many bears :(

**Comment by sils1297** [comment]
you'd rather group them?

**Comment by AbdealiJK** [comment]
I would.
But I don't know how ...
Grouping based on language seems redundant because people would use only 1 specific tool for a language.
For eg: People using pep8 won't use pylint and flake8



-----Original Message-----

**Comment by sils1297** [comment]
groups by languages make sense IMO but the borders are fuzzy, we might have C tools and tools that support C and Java because they have similar syntactic elements. The only atomic unit we can come up with is a bear which is why I think we should make each bear available individually - though we *definitely* should have an automated process for releasing them.

**Comment by Makman2** [comment]
we should part them, if someone wants to use a specific - let's say - C-linter, he doesn't want to get all C-linters just because we group all bears together that operate on C. Even though we get many bears, why should this be a problem? Everyone gets a unique name, it's up to PyPi to handle this (and I really believe that shouldn't be a problem ;D).
I'm in for additional grouping of bears into packages, but keeping single ones allows for better customization.
It's a bit like latex packages, you can get it completely (...), or you download the specific stuff you need, or some subgroups (like base packages). We would do exactly the same and I think this is a good approach^^

**Comment by Makman2** [comment]
Yeah I know this requires quite some packaging and publishing infrastructure, but I believe it's worth the effort^^

**Comment by AbdealiJK** [comment]
Then do we keep all these bears together in a single repo or in different ones ?


-----Original Message-----

**Comment by Makman2** [comment]
I would keep them here, then we need the deployment infrstructure only once and we have a single address when we need to deal with bears -> this repo :)

**Comment by sils1297** [comment]
We definitely need something smart, we cannot do a development release of 50 packages if only one of them changes.

**Comment by sils1297** [comment]
So we could make rultor look at the git commits since master when doing a merge and just releasing bears that have changed. And each bear should get an own directory or something. That could work.

**Comment by AbdealiJK** [comment]
Conversation on IRC (freenode #distutils)

```
<sils_> Cool, hi everyone! I and ajk_ are from the coala project (coala-analyzer.org) and we're currently in the process of heavily modularizing our application. We're looking into several ways and some of them would involve creating 40 to 50 new pypi packages. We're a bit worried about flooding pypi so we'd rather want to check up with a few people who know a bit
<sils_> more about this than we do.
<sils_> Secondly, this is more of a general question, our modules use linters which are not necessarily pullable from pypi so we're looking for a way to install e.g. npm/bower/go dependencies properly on the users system *and also* providing a clean way to remove them on uninstallation.
<sils_> We're thinking about building a wrapper around pip to make that happen and conform a bit with our specific requirements.
<sils_> ajk_ forgot anything?
<ajk_> Currently we ask the user to install it manually - we want to automate it
<ajk_> sils_, That's about it :)
<sils_> Maybe important to notice that we're freetime developers and don't have the resources to maintain an own pypi server.
<CarlFK> do each of these packages deserve a spot on pypi?
<sils_> So each package is a plugin for a linter, so one package might be the CheckstyleBear which allows you to analyze your code using Checkstyle
<sils_> I'm not sure what "deserves a spot".
<sils_> I think they might be comparable to all the pytest-... and django-... packages
<ajk_> The easiest analogy would be django. You have a core django and many django-xyz packages
<CarlFK> hmm
<CarlFK> my thought is: who cares if you add 50 more things to pypi?
<CarlFK> I rarely use pypi's search.   cluttering search results is the only reason I can see for it it being a problem
<sils_> So there was somebody who actually complained about us doing development releases because they "clutter his view" (i.e. the timeline on the home page), this is a whole other scale and we don't want to upset anybody or waste resources. Still it seems the best viable option.
<CarlFK> how about one big package that contains 50 modules?
<ajk_> CarlFK, we already have that - we want to modularize it
<sils_> the whole reason we do this is so the user doesn't have to install hundreds of MB when he just has java code to analyze
<ajk_> A typical user wouldn't need more than 3-4 of these packages
<sils_> those are the only atomic thing, we thought about grouping them but it doesn't really make sense
<CarlFK> if the only reason to break them up is to save disk space.. pfft.  not worth the hassle
<CarlFK> sounds like it is work for you, and will make (a little) more work for the user to pip install more packaged
<CarlFK> packages
<sils_> and bandwidth, we had complaints when people tried to use it during FOSDEM.
<ajk_> We currently force then to download over 100 MB for any simple usage
<ajk_> With modularization it wouldn't be more than 2MB
<dstufft> 40-50 packages on PyPI is no problem
```

**Comment by AbdealiJK** [comment]
I was doing a bunch of stuff and came across conda again. I had mentioned this earlier - https://github.com/coala-analyzer/coala/issues/1047#issuecomment-183591167 https://github.com/coala-analyzer/coala/issues/1304#issuecomment-181678529
I was against it earlier, but now I realize that conda/miniconda seems to be better than pip/python when dealing with non-python packages.

It helps setup complete environments easily. it's essentially similar to `arch`'s package manager and provides "recipes" to make a package (I think). Only issue I see with conda is that it's like maven - if you're using conda you can't use any other tool, as using them together gets pretty complicated.

In conda you can have packages for any type of package. For example:
 - vlfeat (a C/C++ package with python bindings) - https://anaconda.org/menpo/vlfeat
 - OpenCV (uses cmake) - https://anaconda.org/menpo/opencv
 - pytest (python package) - https://anaconda.org/anaconda/pytest
 - lintr (R package) - https://anaconda.org/r/r-lintr
 - jshint (nodejs package) - https://anaconda.org/tswicegood/jshint

Note: Some package are understandably not there. Example: coala (:P), Rubocop
Also, there seems to be some direct relation between conda and pypi - https://anaconda.org/pypi But I'm not sure how it's related.

**Comment by sims1253** [comment]
@Adrianzatreanu didn't you do this during europython?

**Comment by Adrianzatreanu** [comment]
More or less this is my project, so i can't say i've fully done it, but yes, it will be done :d ive made each bear a package but the installation tool is in progress and they are kind of dependant
