### ISSUE TITLE
[Bear Proposal] rstcheck

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#902]
[Write a bear](http://docs.coala.io/en/latest/Developers/Writing_Bears.html) for https://pypi.python.org/pypi/rstcheck to check [reStructuredText](https://en.wikipedia.org/wiki/reStructuredText).

**Comment by sourabhtk37** [comment]
An rstcheck need to done right to all .py files?

**Comment by jayvdb** [comment]
No. On [reStructuredText](https://en.wikipedia.org/wiki/reStructuredText) files.
See `bears/rest/` for one existing reStructuredText bear.

**Comment by sils** [comment]
@jayvdb writing a bear is usually difficulty/low not newcomer. Was there a particular reason you chose newcomer?

**Comment by jayvdb** [comment]
Sorry
