### ISSUE TITLE
Incorrect indent in RELEASE_NOTES.rst 

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#919]
```bash
$ rstcheck RELEASE_NOTES.rst 
RELEASE_NOTES.rst:179: (ERROR/3) Unexpected indentation.
```

The problem is that there is an extra space (` `) in the second line of

```
-  ``ClangComplexityBear`` (Calculates cyclomatic complexity of each function
    for C, C++ and other Clang supported languages.)
```

The `for` should be aligned under the first character of the first line of the list item. 

This problem is part of the patch at #904 , which may be abandoned in an unmergable state.

**Comment by jayvdb** [comment]
(Waiting for a response from @sourabhtk37)

**Comment by nemaniarjun** [comment]
I am an absolute newbie, can i try this?
