### ISSUE TITLE
MarkdownBear: Add remark-validate-links plugin 

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#924]
`remark` has many plugins.  One is remark-validate-links , that checks that the local files exist relative to the markdown file.

**Comment by jayvdb** [comment]
See https://github.com/imsky/PocketEuler/blob/master/.travis.yml for an example

**Comment by namanyadav12** [comment]
Hey , Assign this is to me. I recently worked on https://github.com/coala/coala-bears/issues/1181 in which i had to add remark-lint plugin to MarkdownBear, so i guess this will be easy for me.

**Comment by yash-nisar** [comment]
@Makman2 I can do this one. Can I get assigned ?
