### ISSUE TITLE
MarkdownBear: use remark-lint to report meaningful messages

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#926]
Using the revised output of remark is helpful for tidying the markdown automatically, however that means there are no descriptions of the problems.

The remark-lint plugin reports error messages.

When in CI mode, and the tidying of the file is useless, and descriptive messages are critical.

e.g. https://github.com/imsky/PocketEuler/blob/master/.travis.yml

**Comment by jayvdb** [comment]
So, the introduction of `remark-lint>=5.1.0` was done in #1204.

Rather urgently, we need to test what happens with remark reformats and remark-lint emits an error.  I expect both will happen, resulting in duplication of sorts, which may be confusing.

**Comment by yash-nisar** [comment]
With reference to 
> Rather urgently, we need to test what happens with remark reformats and remark-lint emits an error. I expect both will happen, resulting in duplication of sorts, which may be confusing.

I've tested that both happen and there is a duplication. i.e. `remark-lint` emits an error even after the file is reformatted after the patch is applied.

**Comment by yash-nisar** [comment]
One workaround can be to avoid using duplicated settings, i.e. higher preference should be given to code correcting capabilities instead of `remark-lint` plugins which only emit a message.
