### ISSUE TITLE
YapfBear.check_prerequisites isnt reachable

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#928]
YapfBear.check_prerequisites emits a warning that `Yapf only supports Python 2.7 and Python 3.4+`.

Except it isnt possible, as coala supports only python 3.4 or later, and wont install on lower versions.

**Comment by aptrishu** [comment]
This issue is solved I think.
https://github.com/ragnerok/coala-bears/pull/1

**Comment by jayvdb** [comment]
> This issue is solved I think. ragnerok#1

No quite.  Please read *this* issue carefully.  It is broader than the other issue.

**Comment by ragnerok** [comment]
Yeah so I only have to change this
return 'Yapf only supports Python 2.7 and Python 3.4+'

to 
return 'Yapf only supports Python 3.4+' and change the if statement too right
and could you please also tell me the mistake in my previous commit message . 
PS I am a noob so any help will be appreciated ! Thanks

**Comment by jayvdb** [comment]
@ragnerok , please try to run this bear on Python 3.3.

**Comment by sils** [comment]
according https://github.com/google/yapf#python-versions they don't support python 3.3 @jayvdb

**Comment by jayvdb** [comment]
@sils : from the issue description ... "Except it isnt possible, as coala supports only python 3.4 or later, and wont install on lower versions."

`YapfBear.check_prerequisites` is *unreachable*.  It needs to be burnt with fire, not fiddled with.

**Comment by sils** [comment]
Right, only check if yapf is available and be done.

**Comment by jayvdb** [comment]
> Right, only check if yapf is available and be done.

@sils, does `PipRequirement.is_installed` need to be called, or is that checked automatically?

**Comment by sils** [comment]
I actually wanted that to happen automatically. There's an issue somewhere - but @fneu was working on a refactoring of the requirement stuff so that was postponed a bit. He's rather busy with lots of stuff...

**Comment by nikhilsingh291** [comment]
Is this issue still available?  I'm a newcomer.

**Comment by jayvdb** [comment]
Previous attempts were https://github.com/coala/coala-bears/pull/936 and https://github.com/coala/coala-bears/pull/937 - repository deleted.

@nikhilsingh291 , make sure you follow http://api.coala.io/en/latest/Developers/Git_Basics.html , especially creating a branch : do not use "master" for your development - that is the most common mistake .  And then when you are ready to commit, also read http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html .

**Comment by nikhilsingh291** [comment]
@jayvdb I tried installing bears on python 3.3. Bears already checks for python 3.4 or greater. So  there is no need of this YapfBear.check_prerequisites function. Should I delete the whole check_prerequisites function? Suggest.

**Comment by jayvdb** [comment]
Yes, delete the whole `check_prerequisites`.
