### ISSUE TITLE
Simplify YapfBear python version check

### ISSUE THREAD

**Issue by adtac** [coala/coala-bears#934]
https://github.com/coala/coala-bears/blob/master/bears/python/YapfBear.py#L181

`if sys.version_info < (3,4):`

**Comment by jayvdb** [comment]
I think this is a dup of https://github.com/coala/coala-bears/issues/928

**Comment by aptrishu** [comment]
You should close https://github.com/coala/coala-bears/issues/928 . @jayvdb 
This issue was a duplicate. :P

**Comment by adtac** [comment]
@jayvdb not exactly the same, but I guess they can be merged into one issue. I'll close this.

**Comment by Makman2** [comment]
@jayvdb as the other issue is a bit broader and this is just a little codestyle issue, wanna reopen this one?
then @ragnerok can at least get something merged :)
