### ISSUE TITLE
CSVLintBear: Get line and (text) column of the issue

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#967]
Right now it just associates the result with the file and shows more info in additional_info, that's really bad :/ Having good result info is critical.

CC @stefanbalas

**Comment by sahildua2305** [comment]
@sils since it uses `csvlint`, I'm not sure how we can change this behaviour. Can you give me some pointer for this?

**Comment by sils** [comment]
I have no idea. Asl @stefanbalas . I bet csvlint already has the info and outputs it and we just discard it!

**Comment by nemaniarjun** [comment]
I can take this up.
