### ISSUE TITLE
YAMLLintBear: Wrong argument "--config"

### ISSUE THREAD

**Issue by rafidaslam** [coala/coala-bears#979]
There is a wrong argument in `YAMLLintBear.py`

```py
        if yamllint_config:
            args += ('--config=' + yamllint_config,)
```

At line 53, `--config` there should be `--config-file`, because there is no `--config` argument in yamllint.

Probably the unit test passed because `coala` didn't return any warning (zero code), however if I check it manually using `yamllint`, it will returns:
```
$ yamllint --config=conf.yml test.yml usage: yamllint [-h] [-c CONFIG_FILE] [-d CONFIG_DATA]
                [-f {parsable,standard}] [-v]
                FILE_OR_DIR [FILE_OR_DIR ...]
yamllint: error: ambiguous option: --config=conf.yml could match --config-file, --config-data
```

**Comment by Nosferatul** [comment]
Thx for the report!

**Comment by meetarora29** [comment]
I would like to do this. Please assign me this :)

**Comment by SanketDG** [comment]
@meetarora29 You are assigned!
