### ISSUE TITLE
SASSLintBear 

### ISSUE THREAD

**Issue by AsnelChristian** [coala/coala-bears#982]
https://github.com/sasstools/sass-lint
Seemingly scss-lint won't be maintain in a near future, this is an alternative for that.

**Comment by marian-ald** [comment]
@Asnelchristian Could you give me some details how can this bear could be created? It would be my first bear, so I need some information :)

**Comment by marian-ald** [comment]
Anyway, I'll try to make it :))

**Comment by Shade5** [comment]
Hey, still working on this?
